import type { LanguageCode } from '@/lib/i18n';
export interface AdBreakEvenCopy { title:string; description:string; saleOn:string; price:string; cpc:string; conversion:string; budget:string; listSize:string; emailConversion:string; shopRevenue:string; offsite:string; offsiteUnder:string; offsiteOver:string; offsiteBody:string; budgetVerdict:string; channels:string; emailBaseline:string; bestPaid:string; noPaid:string; emailWins:string; netSale:string; ordersDay:string; maxCpc:string; roas:string; }
const en:AdBreakEvenCopy={title:'Ad Break-Even Lab',description:'The ceiling a click is worth before you buy it: channel break-even CPC, ROAS, and the Offsite Ads haircut against an email baseline.',saleOn:'Sale completes on',price:'Pattern price',cpc:'Typical CPC (Etsy digital)',conversion:'Click → order rate',budget:'Daily ad budget',listSize:'Email list size',emailConversion:'Email conversion',shopRevenue:'Annual shop revenue',offsite:'Offsite Ads tier',offsiteUnder:'15% (under $10k/yr)',offsiteOver:'12% (≥$10k/yr — mandatory for the lifetime of the shop)',offsiteBody:'Any Etsy sale within 30 days of an Offsite Ad click loses this share on top of standard fees; every channel row prices it in.',budgetVerdict:'Budget verdict',channels:'Channels, ordered by projected daily profit',emailBaseline:'Email baseline (one warm send)',bestPaid:'Best paid channel',noPaid:'No paid channel clears at the assumed conversion.',emailWins:'Your email list outsells a month of paid spend — grow it first.',netSale:'Net / sale',ordersDay:'Projected orders/day',maxCpc:'Max break-even CPC',roas:'Break-even ROAS'};
const de:AdBreakEvenCopy={...en,title:'Werbe-Break-even-Labor',description:'Der Höchstwert eines Klicks vor dem Kauf: Break-even-CPC, ROAS und Offsite-Ads-Abzug im Vergleich zur E-Mail-Basislinie.',saleOn:'Verkauf erfolgt auf',price:'Musterpreis',cpc:'Typischer CPC (digitale Etsy-Produkte)',conversion:'Klick-zu-Bestellung-Rate',budget:'Tägliches Werbebudget',listSize:'Größe der E-Mail-Liste',emailConversion:'E-Mail-Konversion',shopRevenue:'Jahresumsatz des Shops',offsite:'Offsite-Ads-Stufe',offsiteUnder:'15 % (unter 10.000 $/Jahr)',offsiteOver:'12 % (≥10.000 $/Jahr — für die gesamte Shoplaufzeit verpflichtend)',offsiteBody:'Jeder Etsy-Verkauf innerhalb von 30 Tagen nach einem Offsite-Ads-Klick verliert diesen Anteil zusätzlich zu den Standardgebühren.',budgetVerdict:'Budgeturteil',channels:'Kanäle, geordnet nach erwartetem Tagesgewinn',emailBaseline:'E-Mail-Basislinie (eine warme Aussendung)',bestPaid:'Bester bezahlter Kanal',noPaid:'Bei der angenommenen Konversion erreicht kein bezahlter Kanal die Gewinnschwelle.',emailWins:'Deine E-Mail-Liste schlägt einen Monat bezahlter Werbung — baue sie zuerst aus.',netSale:'Netto / Verkauf',ordersDay:'Erwartete Bestellungen/Tag',maxCpc:'Max. Break-even-CPC',roas:'Break-even-ROAS'};
const fr:AdBreakEvenCopy={...en,title:'Labo du seuil de rentabilité publicitaire',description:'La valeur maximale d’un clic avant achat : CPC et ROAS de rentabilité, avec la retenue Offsite Ads face à la base e-mail.',saleOn:'La vente se termine sur',price:'Prix du patron',cpc:'CPC habituel (produit numérique Etsy)',conversion:'Taux clic → commande',budget:'Budget publicitaire quotidien',listSize:'Taille de la liste e-mail',emailConversion:'Conversion e-mail',shopRevenue:'Chiffre d’affaires annuel',offsite:'Niveau Offsite Ads',offsiteUnder:'15 % (moins de 10 000 $/an)',offsiteOver:'12 % (≥10 000 $/an — obligatoire pendant toute la vie de la boutique)',offsiteBody:'Toute vente Etsy dans les 30 jours d’un clic Offsite Ads perd cette part en plus des frais standards.',budgetVerdict:'Verdict du budget',channels:'Canaux, classés par bénéfice quotidien projeté',emailBaseline:'Base e-mail (un envoi à une audience chaude)',bestPaid:'Meilleur canal payant',noPaid:'Aucun canal payant n’atteint le seuil avec la conversion supposée.',emailWins:'Votre liste e-mail rapporte plus qu’un mois de publicité — développez-la d’abord.',netSale:'Net / vente',ordersDay:'Commandes prévues/jour',maxCpc:'CPC maximal de rentabilité',roas:'ROAS de rentabilité'};
const es:AdBreakEvenCopy={...en,title:'Laboratorio de punto de equilibrio publicitario',description:'El valor máximo de un clic antes de comprarlo: CPC y ROAS de equilibrio por canal frente a una base de correo.',saleOn:'La venta se completa en',price:'Precio del patrón',cpc:'CPC habitual (producto digital de Etsy)',conversion:'Tasa clic → pedido',budget:'Presupuesto diario de anuncios',listSize:'Tamaño de la lista de correo',emailConversion:'Conversión de correo',shopRevenue:'Ingresos anuales de la tienda',offsite:'Nivel de Offsite Ads',offsiteUnder:'15 % (menos de 10.000 $/año)',offsiteOver:'12 % (≥10.000 $/año — obligatorio durante toda la vida de la tienda)',offsiteBody:'Toda venta de Etsy dentro de los 30 días de un clic de Offsite Ads pierde este porcentaje además de las tarifas estándar.',budgetVerdict:'Veredicto del presupuesto',channels:'Canales, ordenados por beneficio diario previsto',emailBaseline:'Base de correo (un envío a audiencia cálida)',bestPaid:'Mejor canal de pago',noPaid:'Ningún canal de pago alcanza el equilibrio con la conversión asumida.',emailWins:'Tu lista de correo supera un mes de publicidad pagada — hazla crecer primero.',netSale:'Neto / venta',ordersDay:'Pedidos previstos/día',maxCpc:'CPC máximo de equilibrio',roas:'ROAS de equilibrio'};
const pt:AdBreakEvenCopy={...en,title:'Laboratório de ponto de equilíbrio dos anúncios',description:'O valor máximo de um clique antes de o comprar: CPC e ROAS de equilíbrio por canal face à base de e-mail.',saleOn:'A venda é concluída em',price:'Preço do padrão',cpc:'CPC habitual (produto digital Etsy)',conversion:'Taxa clique → encomenda',budget:'Orçamento diário de anúncios',listSize:'Tamanho da lista de e-mail',emailConversion:'Conversão de e-mail',shopRevenue:'Receita anual da loja',offsite:'Nível de Offsite Ads',offsiteUnder:'15% (menos de 10 000 $/ano)',offsiteOver:'12% (≥10 000 $/ano — obrigatório durante toda a vida da loja)',offsiteBody:'Qualquer venda Etsy nos 30 dias após um clique Offsite Ads perde esta percentagem além das taxas padrão.',budgetVerdict:'Veredicto do orçamento',channels:'Canais, ordenados pelo lucro diário projetado',emailBaseline:'Base de e-mail (um envio para audiência quente)',bestPaid:'Melhor canal pago',noPaid:'Nenhum canal pago atinge o ponto de equilíbrio com a conversão assumida.',emailWins:'A sua lista de e-mail supera um mês de publicidade paga — faça-a crescer primeiro.',netSale:'Líquido / venda',ordersDay:'Encomendas previstas/dia',maxCpc:'CPC máximo de equilíbrio',roas:'ROAS de equilíbrio'};
export const COPY: Record<LanguageCode, AdBreakEvenCopy> = { en, de, fr, es, pt };
export const AD_BREAK_EVEN_COPY = COPY;

export function getAdVerdictLabel(locale: string, verdict: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  const labels: Record<LanguageCode, Record<string,string>> = {
    en:{strong:'Fund it',avoid:'Avoid',baseline:'Baseline',marginal:'Marginal'},
    de:{strong:'Finanzieren',avoid:'Vermeiden',baseline:'Basislinie',marginal:'Grenzwertig'},
    fr:{strong:'Financer',avoid:'Éviter',baseline:'Référence',marginal:'Limite'},
    es:{strong:'Financiar',avoid:'Evitar',baseline:'Base',marginal:'Marginal'},
    pt:{strong:'Financiar',avoid:'Evitar',baseline:'Referência',marginal:'Marginal'},
  };
  return labels[language]?.[verdict] ?? labels.en[verdict] ?? verdict;
}
export function getAdBudgetLabel(locale: string, verdict: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  const labels: Record<LanguageCode, Record<string,string>> = {
    en:{fund:'Fund the budget',skip:'Skip — feed the list instead',test_small:'Test small (≤$5/day)'},
    de:{fund:'Budget finanzieren',skip:'Überspringen — Liste ausbauen',test_small:'Klein testen (≤5 $/Tag)'},
    fr:{fund:'Financer le budget',skip:'Ignorer — développer la liste',test_small:'Tester petit (≤5 $/jour)'},
    es:{fund:'Financiar el presupuesto',skip:'Omitir — haz crecer la lista',test_small:'Probar poco (≤5 $/día)'},
    pt:{fund:'Financiar o orçamento',skip:'Ignorar — aumentar a lista',test_small:'Testar pouco (≤5 $/dia)'},
  };
  return labels[language]?.[verdict] ?? labels.en[verdict] ?? verdict;
}

export function getAdChannelLabel(locale: string, channel: string, fallback: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  const labels: Record<LanguageCode, Record<string,string>> = {
    en:{etsy_onplatform:'Etsy Ads (on-platform CPC)',etsy_offsite:'Etsy Offsite Ads',google_search:'Google Search',meta_prospecting:'Meta prospecting (IG/FB)',meta_retargeting:'Meta retargeting',pinterest:'Pinterest promoted pins',ravelry_featured_source:'Ravelry Featured Source',email_list:'Email list send'},
    de:{etsy_onplatform:'Etsy Ads (CPC auf der Plattform)',etsy_offsite:'Etsy Offsite Ads',google_search:'Google-Suche',meta_prospecting:'Meta-Prospecting (IG/FB)',meta_retargeting:'Meta-Retargeting',pinterest:'Beworbene Pinterest-Pins',ravelry_featured_source:'Ravelry Featured Source',email_list:'E-Mail-Aussendung'},
    fr:{etsy_onplatform:'Etsy Ads (CPC sur la plateforme)',etsy_offsite:'Etsy Offsite Ads',google_search:'Recherche Google',meta_prospecting:'Prospection Meta (IG/FB)',meta_retargeting:'Retargeting Meta',pinterest:'Épingles Pinterest sponsorisées',ravelry_featured_source:'Ravelry Featured Source',email_list:'Envoi à la liste e-mail'},
    es:{etsy_onplatform:'Etsy Ads (CPC en plataforma)',etsy_offsite:'Etsy Offsite Ads',google_search:'Búsqueda de Google',meta_prospecting:'Prospección Meta (IG/FB)',meta_retargeting:'Retargeting de Meta',pinterest:'Pins promocionados de Pinterest',ravelry_featured_source:'Ravelry Featured Source',email_list:'Envío a la lista de correo'},
    pt:{etsy_onplatform:'Etsy Ads (CPC na plataforma)',etsy_offsite:'Etsy Offsite Ads',google_search:'Pesquisa Google',meta_prospecting:'Prospecção Meta (IG/FB)',meta_retargeting:'Retargeting Meta',pinterest:'Pins promovidos do Pinterest',ravelry_featured_source:'Ravelry Featured Source',email_list:'Envio para a lista de e-mail'},
  };
  return labels[language]?.[channel] ?? fallback;
}

export function getAdReason(locale: string, channel: string, fallback: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  const reasons: Record<LanguageCode, Record<string,string>> = {
    en:{email_list:'Email is the benchmark, not an ad channel; warm-list sends should be established before paid launch.',etsy_offsite:'Offsite Ads is a fee on attributed sales, not an ad placement you control; price the margin haircut into every order.',ravelry_featured_source:'Ravelry promotes the designer page rather than individual patterns; use it for brand building, not direct response.',etsy_onplatform:'Etsy sets the CPC and provides no keyword targeting; compare the click ceiling with net revenue before spending.',google_search:'Google Search has high intent and controllable keywords; approve it only when the pattern margin clears the break-even benchmark.',meta_prospecting:'Meta prospecting reaches cold audiences and is rarely viable for low-priced patterns without strong margin.',meta_retargeting:'Meta retargeting reaches warm audiences and should be judged against the pattern’s own break-even ROAS.',pinterest:'Pinterest can support discovery at lower CPCs; compare the expected order value with the channel ceiling.'},
    de:{email_list:'E-Mail ist die Basislinie, kein Werbekanal; wärme die Liste auf, bevor du bezahlte Werbung startest.',etsy_offsite:'Offsite Ads ist eine Gebühr auf zugerechnete Verkäufe, keine kontrollierbare Platzierung; rechne den Margenabzug ein.',ravelry_featured_source:'Ravelry bewirbt die Designer-Seite statt einzelne Muster; nutze es für Markenaufbau, nicht für Direktantworten.',etsy_onplatform:'Etsy setzt den CPC ohne Keyword-Targeting; vergleiche vor dem Ausgeben die Klickgrenze mit dem Nettoerlös.',google_search:'Google Search hat hohe Kaufabsicht und steuerbare Keywords; gib nur frei, wenn die Marge den Break-even-Wert übersteigt.',meta_prospecting:'Meta-Prospecting erreicht kalte Zielgruppen und ist für günstige Muster selten tragfähig.',meta_retargeting:'Meta-Retargeting erreicht warme Zielgruppen und sollte am eigenen Break-even-ROAS gemessen werden.',pinterest:'Pinterest unterstützt Entdeckung oft mit niedrigeren CPCs; vergleiche Bestellwert und Kanalgrenze.'},
    fr:{email_list:'L’e-mail est la référence, pas un canal publicitaire ; établissez la liste avant de lancer du payant.',etsy_offsite:'Offsite Ads est une commission sur les ventes attribuées, pas un emplacement contrôlable ; intégrez la baisse de marge.',ravelry_featured_source:'Ravelry met en avant la page de la créatrice plutôt que les patrons ; utilisez-le pour la marque, pas la réponse directe.',etsy_onplatform:'Etsy fixe le CPC sans ciblage par mots-clés ; comparez la limite du clic au revenu net avant de dépenser.',google_search:'Google Search offre une forte intention et des mots-clés contrôlables ; validez seulement si la marge dépasse le seuil.',meta_prospecting:'Meta en prospection touche des audiences froides et convient rarement aux patrons peu chers.',meta_retargeting:'Le retargeting Meta touche des audiences chaudes ; mesurez-le avec le ROAS de rentabilité du patron.',pinterest:'Pinterest peut favoriser la découverte à CPC plus bas ; comparez la valeur de commande au plafond du canal.'},
    es:{email_list:'El correo es la referencia, no un canal publicitario; calienta la lista antes de lanzar publicidad de pago.',etsy_offsite:'Offsite Ads es una comisión sobre ventas atribuidas, no una colocación que controles; incluye el recorte de margen.',ravelry_featured_source:'Ravelry promociona la página de la diseñadora, no cada patrón; úsalo para marca, no para respuesta directa.',etsy_onplatform:'Etsy fija el CPC sin segmentación por palabras clave; compara el límite del clic con el ingreso neto antes de gastar.',google_search:'Google Search tiene alta intención y palabras clave controlables; apruébalo solo si el margen supera el equilibrio.',meta_prospecting:'La prospección de Meta llega a audiencias frías y rara vez funciona para patrones baratos.',meta_retargeting:'El retargeting de Meta llega a audiencias cálidas; mídelo con el ROAS de equilibrio del patrón.',pinterest:'Pinterest puede impulsar el descubrimiento con CPC menor; compara el valor del pedido con el límite del canal.'},
    pt:{email_list:'O e-mail é a referência, não um canal de anúncios; aqueça a lista antes de lançar publicidade paga.',etsy_offsite:'Offsite Ads é uma comissão sobre vendas atribuídas, não uma colocação controlável; inclua a redução da margem.',ravelry_featured_source:'O Ravelry promove a página da designer, não cada padrão; use-o para marca, não para resposta direta.',etsy_onplatform:'A Etsy define o CPC sem segmentação por palavras-chave; compare o limite do clique com a receita líquida.',google_search:'A Pesquisa Google tem intenção elevada e palavras-chave controláveis; aprove apenas se a margem superar o equilíbrio.',meta_prospecting:'A prospeção Meta alcança públicos frios e raramente compensa para padrões baratos.',meta_retargeting:'O retargeting Meta alcança públicos quentes; avalie-o pelo ROAS de equilíbrio do padrão.',pinterest:'O Pinterest pode apoiar a descoberta com CPC mais baixo; compare o valor da encomenda com o limite do canal.'},
  };
  return reasons[language]?.[channel] ?? fallback;
}

export function getAdBudgetReason(locale: string, verdict: string, fallback: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  const reasons: Record<LanguageCode, Record<string,string>> = {
    en:{skip:'No paid channel clears the assumed economics; redirect this budget into growing the email list.',test_small:'Test a small capped budget and keep the listing only if measured ROAS repays the production cost.',fund:'The strongest paid channel clears the economics; scale cautiously and keep a strict ROAS floor.'},
    de:{skip:'Kein bezahlter Kanal erreicht die angenommene Wirtschaftlichkeit; investiere das Budget in die E-Mail-Liste.',test_small:'Teste mit einem kleinen begrenzten Budget und behalte das Angebot nur bei ausreichendem ROAS.',fund:'Der stärkste bezahlte Kanal erfüllt die Wirtschaftlichkeit; skaliere vorsichtig mit einer festen ROAS-Untergrenze.'},
    fr:{skip:'Aucun canal payant n’atteint l’équilibre supposé ; investissez plutôt dans la liste e-mail.',test_small:'Testez un petit budget plafonné et gardez l’annonce seulement si le ROAS rembourse la production.',fund:'Le meilleur canal payant atteint l’équilibre ; augmentez prudemment avec un seuil de ROAS strict.'},
    es:{skip:'Ningún canal de pago alcanza la economía asumida; dirige el presupuesto a hacer crecer la lista de correo.',test_small:'Prueba un presupuesto pequeño y conserva el anuncio solo si el ROAS recupera el coste de producción.',fund:'El mejor canal de pago supera la economía asumida; escala con prudencia y un suelo de ROAS estricto.'},
    pt:{skip:'Nenhum canal pago atinge a economia assumida; direcione o orçamento para aumentar a lista de e-mail.',test_small:'Teste um orçamento pequeno e mantenha o anúncio apenas se o ROAS pagar a produção.',fund:'O melhor canal pago atinge a economia assumida; escale com cautela e um limite de ROAS rigoroso.'},
  };
  return reasons[language]?.[verdict] ?? fallback;
}
