import { LanguageCode } from './i18n';

export const COPY: Record<LanguageCode, any> = {
  en: {
    assetsTitle: 'Project Assets',
    assetsDescription: 'Manage photos, swatches, schematics, and reference attachments.',
    addAsset: 'Add Asset',
    noAssets: 'No assets attached to this project.',
    assetLabel: 'Label',
    assetCategory: 'Category',
    assetFile: 'File',
    assetLimit: 'File size limit: 2MB (Base64 storage)',
    categoryPhoto: 'Photo',
    categorySwatch: 'Swatch',
    categorySchematic: 'Schematic',
    categoryEvidence: 'Evidence',
    categoryOther: 'Other',
    confirmDelete: 'Are you sure you want to delete this asset?',
    viewAsset: 'View asset',
    downloadAsset: 'Download asset',
    deleteAsset: 'Delete asset',
    cancel: 'Cancel',
    save: 'Save',
    assetTypeImage: 'Image',
    assetTypeDoc: 'Document',
    assetTypeOther: 'Other',
    finishedWorkTitle: 'Finished work',
    finishedWorkDescription: 'Keep the piece you made beside the grading record.',
    addFinishedPhoto: 'Add finished photo',
    finishedEmpty: 'Your finished piece will live here.',
    finishedEmptyBody: 'Add a clear photo after knitting to build a private project gallery and carry it into your PDF.',
    caption: 'Caption',
    captionPlaceholder: 'e.g. Front view after blocking',
    includeInPdf: 'Include in project PDF',
    featured: 'Featured view',
    markFeatured: 'Make featured view',
    unmarkFeatured: 'Remove featured view',
    pdfIncluded: 'Included in PDF',
  },
  de: {
    assetsTitle: 'Projekt-Assets',
    assetsDescription: 'Verwalte Fotos, Proben, Schemata und Referenzanhänge.',
    addAsset: 'Asset hinzufügen',
    noAssets: 'Keine Assets an dieses Projekt angehängt.',
    assetLabel: 'Bezeichnung',
    assetCategory: 'Kategorie',
    assetFile: 'Datei',
    assetLimit: 'Dateigrößenbeschränkung: 2MB (Base64-Speicher)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Maschenprobe',
    categorySchematic: 'Schema',
    categoryEvidence: 'Nachweis',
    categoryOther: 'Sonstiges',
    confirmDelete: 'Bist du sicher, dass du dieses Asset löschen möchtest?',
    viewAsset: 'Asset anzeigen',
    downloadAsset: 'Asset herunterladen',
    deleteAsset: 'Asset löschen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    assetTypeImage: 'Bild',
    assetTypeDoc: 'Dokument',
    assetTypeOther: 'Sonstiges',
    finishedWorkTitle: 'Fertiges Stück',
    finishedWorkDescription: 'Bewahre dein fertiges Stück neben dem Prüfprotokoll auf.',
    addFinishedPhoto: 'Foto des fertigen Stücks hinzufügen',
    finishedEmpty: 'Dein fertiges Stück wird hier gesammelt.',
    finishedEmptyBody: 'Füge nach dem Stricken ein klares Foto hinzu, um eine private Projektgalerie aufzubauen und sie in dein PDF zu übernehmen.',
    caption: 'Bildunterschrift',
    captionPlaceholder: 'z. B. Vorderansicht nach dem Spannen',
    includeInPdf: 'In Projekt-PDF aufnehmen',
    featured: 'Hauptansicht',
    markFeatured: 'Als Hauptansicht markieren',
    unmarkFeatured: 'Hauptansicht entfernen',
    pdfIncluded: 'Im PDF enthalten',
  },
  fr: {
    assetsTitle: 'Actifs du projet',
    assetsDescription: 'Gérez les photos, les échantillons, les schémas et les pièces jointes de référence.',
    addAsset: 'Ajouter un actif',
    noAssets: 'Aucun actif attaché à ce projet.',
    assetLabel: 'Étiquette',
    assetCategory: 'Catégorie',
    assetFile: 'Fichier',
    assetLimit: 'Limite de taille de fichier : 2 Mo (stockage Base64)',
    categoryPhoto: 'Photo',
    categorySwatch: 'Échantillon',
    categorySchematic: 'Schéma',
    categoryEvidence: 'Preuve',
    categoryOther: 'Autre',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet actif ?',
    viewAsset: 'Voir l’actif',
    downloadAsset: 'Télécharger l’actif',
    deleteAsset: 'Supprimer l’actif',
    cancel: 'Annuler',
    save: 'Enregistrer',
    assetTypeImage: 'Image',
    assetTypeDoc: 'Document',
    assetTypeOther: 'Autre',
    finishedWorkTitle: 'Ouvrage terminé',
    finishedWorkDescription: 'Conservez la pièce réalisée avec son dossier de gradation.',
    addFinishedPhoto: 'Ajouter une photo de l’ouvrage',
    finishedEmpty: 'Votre ouvrage terminé sera conservé ici.',
    finishedEmptyBody: 'Ajoutez une photo après le tricot pour créer une galerie privée et l’inclure dans votre PDF.',
    caption: 'Légende',
    captionPlaceholder: 'ex. Vue de face après blocage',
    includeInPdf: 'Inclure dans le PDF du projet',
    featured: 'Vue principale',
    markFeatured: 'Définir comme vue principale',
    unmarkFeatured: 'Retirer la vue principale',
    pdfIncluded: 'Inclus dans le PDF',
  },
  es: {
    assetsTitle: 'Activos del proyecto',
    assetsDescription: 'Administre fotos, muestras, esquemas y archivos adjuntos de referencia.',
    addAsset: 'Agregar activo',
    noAssets: 'No hay activos adjuntos a este proyecto.',
    assetLabel: 'Etiqueta',
    assetCategory: 'Categoría',
    assetFile: 'Archivo',
    assetLimit: 'Límite de tamaño de archivo: 2 MB (almacenamiento Base64)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Muestra',
    categorySchematic: 'Esquema',
    categoryEvidence: 'Evidencia',
    categoryOther: 'Otro',
    confirmDelete: '¿Estás seguro de que quieres eliminar este activo?',
    viewAsset: 'Ver activo',
    downloadAsset: 'Descargar activo',
    deleteAsset: 'Eliminar activo',
    cancel: 'Cancelar',
    save: 'Guardar',
    assetTypeImage: 'Imagen',
    assetTypeDoc: 'Documento',
    assetTypeOther: 'Otro',
    finishedWorkTitle: 'Trabajo terminado',
    finishedWorkDescription: 'Guarda la pieza que hiciste junto a su registro de gradación.',
    addFinishedPhoto: 'Agregar foto terminada',
    finishedEmpty: 'Tu pieza terminada vivirá aquí.',
    finishedEmptyBody: 'Añade una foto clara después de tejer para crear una galería privada e incluirla en tu PDF.',
    caption: 'Descripción',
    captionPlaceholder: 'p. ej., Vista frontal después del bloqueo',
    includeInPdf: 'Incluir en el PDF del proyecto',
    featured: 'Vista destacada',
    markFeatured: 'Marcar como vista destacada',
    unmarkFeatured: 'Quitar vista destacada',
    pdfIncluded: 'Incluida en el PDF',
  },
  pt: {
    assetsTitle: 'Ativos do projeto',
    assetsDescription: 'Gerencie fotos, amostras, esquemas e anexos de referência.',
    addAsset: 'Adicionar ativo',
    noAssets: 'Nenhum ativo anexado a este projeto.',
    assetLabel: 'Rótulo',
    assetCategory: 'Categoria',
    assetFile: 'Arquivo',
    assetLimit: 'Limite de tamanho de arquivo: 2 MB (armazenamento Base64)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Amostra',
    categorySchematic: 'Esquema',
    categoryEvidence: 'Evidência',
    categoryOther: 'Outro',
    confirmDelete: 'Tem certeza de que deseja excluir este ativo?',
    viewAsset: 'Ver ativo',
    downloadAsset: 'Baixar ativo',
    deleteAsset: 'Excluir ativo',
    cancel: 'Cancelar',
    save: 'Salvar',
    assetTypeImage: 'Imagem',
    assetTypeDoc: 'Documento',
    assetTypeOther: 'Outro',
    finishedWorkTitle: 'Trabalho concluído',
    finishedWorkDescription: 'Guarde a peça que criou junto do respetivo registo de graduação.',
    addFinishedPhoto: 'Adicionar foto do trabalho',
    finishedEmpty: 'A sua peça concluída ficará aqui.',
    finishedEmptyBody: 'Adicione uma foto nítida depois de tricotar para criar uma galeria privada e incluí-la no PDF.',
    caption: 'Legenda',
    captionPlaceholder: 'ex.: Vista frontal depois de bloquear',
    includeInPdf: 'Incluir no PDF do projeto',
    featured: 'Vista principal',
    markFeatured: 'Definir como vista principal',
    unmarkFeatured: 'Remover vista principal',
    pdfIncluded: 'Incluída no PDF',
  }
};

export const ASSETS_COPY = COPY;
