import { LanguageCode } from './i18n';

export const COPY: Record<LanguageCode, any> = {
  en: {
    assetsTitle: 'Project Assets',
    assetsDescription: 'Manage photos, swatches, schematics, and reference attachments.',
    addAsset: 'Add Asset',
    noAssets: 'No assets attached to this project.',
    assetLabel: 'Label',
    assetCategory: 'Category',
    assetFile: 'File',
    assetLimit: 'File size limit: 2MB (Base64 storage)',
    categoryPhoto: 'Photo',
    categorySwatch: 'Swatch',
    categorySchematic: 'Schematic',
    categoryEvidence: 'Evidence',
    categoryOther: 'Other',
    confirmDelete: 'Are you sure you want to delete this asset?',
    viewAsset: 'View asset',
    downloadAsset: 'Download asset',
    deleteAsset: 'Delete asset',
    cancel: 'Cancel',
    save: 'Save',
    assetTypeImage: 'Image',
    assetTypeDoc: 'Document',
    assetTypeOther: 'Other',
  },
  de: {
    assetsTitle: 'Projekt-Assets',
    assetsDescription: 'Verwalte Fotos, Proben, Schemata und Referenzanhänge.',
    addAsset: 'Asset hinzufügen',
    noAssets: 'Keine Assets an dieses Projekt angehängt.',
    assetLabel: 'Bezeichnung',
    assetCategory: 'Kategorie',
    assetFile: 'Datei',
    assetLimit: 'Dateigrößenbeschränkung: 2MB (Base64-Speicher)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Maschenprobe',
    categorySchematic: 'Schema',
    categoryEvidence: 'Nachweis',
    categoryOther: 'Sonstiges',
    confirmDelete: 'Bist du sicher, dass du dieses Asset löschen möchtest?',
    viewAsset: 'Asset anzeigen',
    downloadAsset: 'Asset herunterladen',
    deleteAsset: 'Asset löschen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    assetTypeImage: 'Bild',
    assetTypeDoc: 'Dokument',
    assetTypeOther: 'Sonstiges',
  },
  fr: {
    assetsTitle: 'Actifs du projet',
    assetsDescription: 'Gérez les photos, les échantillons, les schémas et les pièces jointes de référence.',
    addAsset: 'Ajouter un actif',
    noAssets: 'Aucun actif attaché à ce projet.',
    assetLabel: 'Étiquette',
    assetCategory: 'Catégorie',
    assetFile: 'Fichier',
    assetLimit: 'Limite de taille de fichier : 2 Mo (stockage Base64)',
    categoryPhoto: 'Photo',
    categorySwatch: 'Échantillon',
    categorySchematic: 'Schéma',
    categoryEvidence: 'Preuve',
    categoryOther: 'Autre',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet actif ?',
    viewAsset: 'Voir l’actif',
    downloadAsset: 'Télécharger l’actif',
    deleteAsset: 'Supprimer l’actif',
    cancel: 'Annuler',
    save: 'Enregistrer',
    assetTypeImage: 'Image',
    assetTypeDoc: 'Document',
    assetTypeOther: 'Autre',
  },
  es: {
    assetsTitle: 'Activos del proyecto',
    assetsDescription: 'Administre fotos, muestras, esquemas y archivos adjuntos de referencia.',
    addAsset: 'Agregar activo',
    noAssets: 'No hay activos adjuntos a este proyecto.',
    assetLabel: 'Etiqueta',
    assetCategory: 'Categoría',
    assetFile: 'Archivo',
    assetLimit: 'Límite de tamaño de archivo: 2 MB (almacenamiento Base64)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Muestra',
    categorySchematic: 'Esquema',
    categoryEvidence: 'Evidencia',
    categoryOther: 'Otro',
    confirmDelete: '¿Estás seguro de que quieres eliminar este activo?',
    viewAsset: 'Ver activo',
    downloadAsset: 'Descargar activo',
    deleteAsset: 'Eliminar activo',
    cancel: 'Cancelar',
    save: 'Guardar',
    assetTypeImage: 'Imagen',
    assetTypeDoc: 'Documento',
    assetTypeOther: 'Otro',
  },
  pt: {
    assetsTitle: 'Ativos do projeto',
    assetsDescription: 'Gerencie fotos, amostras, esquemas e anexos de referência.',
    addAsset: 'Adicionar ativo',
    noAssets: 'Nenhum ativo anexado a este projeto.',
    assetLabel: 'Rótulo',
    assetCategory: 'Categoria',
    assetFile: 'Arquivo',
    assetLimit: 'Limite de tamanho de arquivo: 2 MB (armazenamento Base64)',
    categoryPhoto: 'Foto',
    categorySwatch: 'Amostra',
    categorySchematic: 'Esquema',
    categoryEvidence: 'Evidência',
    categoryOther: 'Outro',
    confirmDelete: 'Tem certeza de que deseja excluir este ativo?',
    viewAsset: 'Ver ativo',
    downloadAsset: 'Baixar ativo',
    deleteAsset: 'Excluir ativo',
    cancel: 'Cancelar',
    save: 'Salvar',
    assetTypeImage: 'Imagem',
    assetTypeDoc: 'Documento',
    assetTypeOther: 'Outro',
  }
};

export const ASSETS_COPY = COPY;
