import type { LanguageCode } from '@/lib/i18n';
export interface BodySchematicCopy { heading:string; description:string; aria:string; labels:Record<string,string>; }
const en:BodySchematicCopy={heading:'Measurement Reference',description:'Where each measurement below is taken from, at a glance.',aria:'Body measurement reference diagram',labels:{bust:'Bust',waist:'Waist',hip:'Hip',upperArm:'Upper Arm',lowerArm:'Lower Arm',wrist:'Wrist',shoulder:'Shoulder',neckCircumference:'Neck',backLength:'Back Length',sleeveLength:'Sleeve Length',thigh:'Thigh',calf:'Calf',ankle:'Ankle',armholeDepth:'Armhole Depth'}};
const de:BodySchematicCopy={heading:'Messreferenz',description:'Auf einen Blick: Wo jedes Maß genommen wird.',aria:'Diagramm der Körpermesspunkte',labels:{bust:'Brust',waist:'Taille',hip:'Hüfte',upperArm:'Oberarm',lowerArm:'Unterarm',wrist:'Handgelenk',shoulder:'Schulter',neckCircumference:'Hals',backLength:'Rückenlänge',sleeveLength:'Ärmellänge',thigh:'Oberschenkel',calf:'Wade',ankle:'Knöchel',armholeDepth:'Armausschnitttiefe'}};
const fr:BodySchematicCopy={heading:'Référence des mesures',description:'En un coup d’œil, où chaque mesure ci-dessous est prise.',aria:'Schéma des points de mesure du corps',labels:{bust:'Poitrine',waist:'Taille',hip:'Hanches',upperArm:'Haut du bras',lowerArm:'Avant-bras',wrist:'Poignet',shoulder:'Épaule',neckCircumference:'Cou',backLength:'Longueur dos',sleeveLength:'Longueur de manche',thigh:'Cuisse',calf:'Mollet',ankle:'Cheville',armholeDepth:'Profondeur d’emmanchure'}};
const es:BodySchematicCopy={heading:'Referencia de medidas',description:'Dónde se toma cada medida, de un vistazo.',aria:'Diagrama de referencia de medidas corporales',labels:{bust:'Pecho',waist:'Cintura',hip:'Cadera',upperArm:'Parte superior del brazo',lowerArm:'Antebrazo',wrist:'Muñeca',shoulder:'Hombro',neckCircumference:'Cuello',backLength:'Largo de espalda',sleeveLength:'Largo de manga',thigh:'Muslo',calf:'Pantorrilla',ankle:'Tobillo',armholeDepth:'Profundidad de sisa'}};
const pt:BodySchematicCopy={heading:'Referência de medidas',description:'Veja rapidamente de onde é tirada cada medida abaixo.',aria:'Diagrama de referência das medidas do corpo',labels:{bust:'Peito',waist:'Cintura',hip:'Anca',upperArm:'Braço',lowerArm:'Antebraço',wrist:'Pulso',shoulder:'Ombro',neckCircumference:'Pescoço',backLength:'Comprimento das costas',sleeveLength:'Comprimento da manga',thigh:'Coxa',calf:'Gémeo',ankle:'Tornozelo',armholeDepth:'Profundidade da cava'}};
export const COPY:Record<LanguageCode,BodySchematicCopy>={en,de,fr,es,pt};

export const BODY_SCHEMATIC_COPY = COPY;
