import type { LanguageCode } from '@/lib/i18n';
export interface BoxInclusionCopy { title:string; description:string; offer:string; boxName:string; subscribers:string; boxPrice:string; designFee:string; royalty:string; exclusivity:string; designHours:string; hourlyRate:string; frequency:string; goods:string; health:string; byline:string; rights:string; funnel:string; exposed:string; listSale:string; digitalPrice:string; earnings:string; worth:string; direct:string; reach:string; joins:string; sales:string; revenue:string; timeCost:string; drag:string; netEv:string; breakEven:string; fairFloor:string; life:string; healthWeight:string; watch:string; verdict:string; anchors:string; }
const en:BoxInclusionCopy={title:'Box Inclusion Lab',description:'Price a yarn-box offer against your self-publish baseline: fee, exposure, time cost, exclusivity, and the box’s survival odds.',offer:'The box & the offer',boxName:'Box name',subscribers:'Subscribers',boxPrice:'Box price / month',designFee:'Flat design fee',royalty:'Royalty / box shipped',exclusivity:'Exclusivity lock',designHours:'Design + swatch hours',hourlyRate:'Your hourly rate',frequency:'Feature frequency',goods:'Free/discounted goods',health:'Box health (0 = frail / 1 = stable)',byline:'Pattern credits you by name',rights:'Contract demands rights / first-publication assignment',funnel:'Your exposure funnel & baseline',exposed:'Exposed → joins your list',listSale:'List → buys pattern (12 mo)',digitalPrice:'Your digital price',earnings:'Your shop earnings / month now',worth:'What the offer is actually worth',direct:'Direct income / wave',reach:'Wave reach (with byline)',joins:'List joins / wave',sales:'Funnel sales / wave',revenue:'Funnel revenue / wave',timeCost:'Your time cost (this design)',drag:'Exclusivity drag / yr',netEv:'Annual net EV (health-weighted)',breakEven:'Break-even fee / wave',fairFloor:'Fair floor fee (6% of retail)',life:'Avg subscriber life',healthWeight:'Health weight applied',watch:'Watch-outs',verdict:'Verdict',anchors:'Industry anchors and survival assumptions are shown here as context; compare the offer against your own baseline before accepting it.'};
const de:BoxInclusionCopy={...en,title:'Yarn-Box-Einschluss-Labor',description:'Bewerte ein Garnbox-Angebot gegenüber deinem Selbstveröffentlichungs-Baseline: Honorar, Reichweite, Zeitkosten, Exklusivität und Überlebenschance der Box.',offer:'Die Box und das Angebot',boxName:'Name der Box',subscribers:'Abonnenten',boxPrice:'Boxpreis / Monat',designFee:'Pauschales Designhonorar',royalty:'Lizenz pro versendeter Box',exclusivity:'Exklusivitätssperre',designHours:'Design- und Maschenprobenstunden',hourlyRate:'Dein Stundensatz',frequency:'Feature-Häufigkeit',goods:'Kostenlose/vergünstigte Waren',health:'Box-Gesundheit (0 = fragil / 1 = stabil)',byline:'Muster nennt dich namentlich',rights:'Vertrag verlangt Rechte / Erstveröffentlichung',funnel:'Dein Reichweiten-Funnel und Baseline',exposed:'Erreicht → tritt Liste bei',listSale:'Liste → kauft Muster (12 Monate)',digitalPrice:'Dein Digitalpreis',earnings:'Aktueller Monatsumsatz deines Shops',worth:'Was das Angebot wirklich wert ist',direct:'Direkte Einnahmen / Welle',reach:'Reichweite / Welle (mit Byline)',joins:'Listenbeitritte / Welle',sales:'Funnel-Verkäufe / Welle',revenue:'Funnel-Umsatz / Welle',timeCost:'Deine Zeitkosten (dieses Design)',drag:'Exklusivitätslast / Jahr',netEv:'Jährlicher Netto-EV (gesundheitsgewichtet)',breakEven:'Break-even-Honorar / Welle',fairFloor:'Faire Untergrenze (6 % vom Verkauf)',life:'Durchschnittliche Abonnentenlaufzeit',healthWeight:'Angewandtes Gesundheitsgewicht',watch:'Warnzeichen',verdict:'Urteil',anchors:'Branchenanker und Überlebensannahmen dienen als Kontext; vergleiche das Angebot vor der Annahme mit deiner eigenen Baseline.'};
const fr:BoxInclusionCopy={...en,title:'Labo d’inclusion en box',description:'Évaluez une offre de box face à votre base d’autoédition : rémunération, visibilité, temps, exclusivité et survie de la box.',offer:'La box et l’offre',boxName:'Nom de la box',subscribers:'Abonnés',boxPrice:'Prix de la box / mois',designFee:'Rémunération fixe',royalty:'Redevance / box expédiée',exclusivity:'Verrou d’exclusivité',designHours:'Heures de design et d’échantillon',hourlyRate:'Votre taux horaire',frequency:'Fréquence de mise en avant',goods:'Produits gratuits/réduits',health:'Santé de la box (0 = fragile / 1 = stable)',byline:'Le patron vous crédite par votre nom',rights:'Le contrat exige les droits / la première publication',funnel:'Votre entonnoir de visibilité et votre base',exposed:'Exposés → rejoignent la liste',listSale:'Liste → achète le patron (12 mois)',digitalPrice:'Votre prix numérique',earnings:'Revenus mensuels actuels de la boutique',worth:'Valeur réelle de l’offre',direct:'Revenu direct / vague',reach:'Portée / vague (avec crédit)',joins:'Inscriptions / vague',sales:'Ventes de l’entonnoir / vague',revenue:'Revenu de l’entonnoir / vague',timeCost:'Votre coût de temps (ce design)',drag:'Coût de l’exclusivité / an',netEv:'EV net annuel (pondéré par la santé)',breakEven:'Rémunération d’équilibre / vague',fairFloor:'Plancher juste (6 % du prix)',life:'Durée moyenne d’un abonné',healthWeight:'Poids de santé appliqué',watch:'Points de vigilance',verdict:'Verdict',anchors:'Les repères et hypothèses de survie servent de contexte ; comparez l’offre à votre base avant de l’accepter.'};
const es:BoxInclusionCopy={...en,title:'Laboratorio de inclusión en cajas',description:'Valora una oferta de caja frente a tu base de autopublicación: tarifa, exposición, tiempo, exclusividad y supervivencia de la caja.',offer:'La caja y la oferta',boxName:'Nombre de la caja',subscribers:'Suscriptores',boxPrice:'Precio de la caja / mes',designFee:'Tarifa fija de diseño',royalty:'Regalía / caja enviada',exclusivity:'Bloqueo de exclusividad',designHours:'Horas de diseño y muestra',hourlyRate:'Tu tarifa por hora',frequency:'Frecuencia de aparición',goods:'Productos gratis/con descuento',health:'Salud de la caja (0 = frágil / 1 = estable)',byline:'El patrón te acredita por nombre',rights:'El contrato exige derechos / primera publicación',funnel:'Tu embudo de exposición y base',exposed:'Expuestos → se unen a tu lista',listSale:'Lista → compra el patrón (12 meses)',digitalPrice:'Tu precio digital',earnings:'Ingresos mensuales actuales de tu tienda',worth:'Valor real de la oferta',direct:'Ingresos directos / oleada',reach:'Alcance / oleada (con crédito)',joins:'Altas en la lista / oleada',sales:'Ventas del embudo / oleada',revenue:'Ingresos del embudo / oleada',timeCost:'Tu coste de tiempo (este diseño)',drag:'Coste de exclusividad / año',netEv:'EV neto anual (ponderado por salud)',breakEven:'Tarifa de equilibrio / oleada',fairFloor:'Suelo justo (6 % del precio)',life:'Vida media del suscriptor',healthWeight:'Peso de salud aplicado',watch:'Puntos de atención',verdict:'Veredicto',anchors:'Los datos de industria y supervivencia son contexto; compara la oferta con tu base antes de aceptarla.'};
const pt:BoxInclusionCopy={...en,title:'Laboratório de inclusão em caixas',description:'Avalie uma oferta de caixa face à sua base de autopublicação: valor, exposição, tempo, exclusividade e sobrevivência da caixa.',offer:'A caixa e a oferta',boxName:'Nome da caixa',subscribers:'Subscritores',boxPrice:'Preço da caixa / mês',designFee:'Valor fixo do design',royalty:'Direitos / caixa enviada',exclusivity:'Bloqueio de exclusividade',designHours:'Horas de design e amostra',hourlyRate:'O seu valor por hora',frequency:'Frequência de destaque',goods:'Produtos gratuitos/com desconto',health:'Saúde da caixa (0 = frágil / 1 = estável)',byline:'O padrão dá crédito pelo seu nome',rights:'O contrato exige direitos / primeira publicação',funnel:'O seu funil de exposição e base',exposed:'Expostos → entram na lista',listSale:'Lista → compra o padrão (12 meses)',digitalPrice:'O seu preço digital',earnings:'Receita mensal atual da loja',worth:'Valor real da oferta',direct:'Rendimento direto / onda',reach:'Alcance / onda (com crédito)',joins:'Entradas na lista / onda',sales:'Vendas do funil / onda',revenue:'Receita do funil / onda',timeCost:'Custo do seu tempo (este design)',drag:'Custo da exclusividade / ano',netEv:'EV líquido anual (ponderado pela saúde)',breakEven:'Valor de equilíbrio / onda',fairFloor:'Piso justo (6% do preço)',life:'Vida média do subscritor',healthWeight:'Peso de saúde aplicado',watch:'Pontos de atenção',verdict:'Veredicto',anchors:'Os valores de referência e hipóteses de sobrevivência dão contexto; compare a oferta com a sua base antes de aceitar.'};
export const COPY:Record<LanguageCode,BoxInclusionCopy>={en,de,fr,es,pt};

export function getBoxFlagTitle(locale: string, id: string, fallback: string): string {
  const l = locale.toLowerCase().split('-')[0] as LanguageCode;
  const titles: Record<LanguageCode, Record<string,string>> = {
    en:{'BI-01':'Exposure-only offer','BI-02':'Fee below the indie floor','BI-03':'Exclusivity consumes your year','BI-04':'Box lifetime shorter than your lock','BI-05':'Rights assignment demanded','BI-06':'Royalty under the margin floor','BI-07':'Box price below sustainable margin','BI-08':'Weak box health','BI-09':'Anonymous hire, zero exposure'},
    de:{'BI-01':'Angebot nur gegen Reichweite','BI-02':'Honorar unter Indie-Untergrenze','BI-03':'Exklusivität verbraucht dein Jahr','BI-04':'Box-Laufzeit kürzer als deine Sperre','BI-05':'Rechteübertragung verlangt','BI-06':'Lizenz unter Margenuntergrenze','BI-07':'Boxpreis unter nachhaltiger Marge','BI-08':'Schwache Box-Gesundheit','BI-09':'Anonyme Beauftragung, keine Reichweite'},
    fr:{'BI-01':'Offre basée uniquement sur la visibilité','BI-02':'Rémunération sous le plancher indépendant','BI-03':'L’exclusivité consomme votre année','BI-04':'Durée de la box inférieure au verrou','BI-05':'Cession de droits exigée','BI-06':'Redevance sous le plancher de marge','BI-07':'Prix de box sous la marge viable','BI-08':'Santé fragile de la box','BI-09':'Commande anonyme, visibilité nulle'},
    es:{'BI-01':'Oferta solo por exposición','BI-02':'Tarifa por debajo del mínimo independiente','BI-03':'La exclusividad consume tu año','BI-04':'La vida de la caja es menor que el bloqueo','BI-05':'Se exige cesión de derechos','BI-06':'Regalía bajo el margen mínimo','BI-07':'Precio de caja bajo el margen sostenible','BI-08':'Salud débil de la caja','BI-09':'Trabajo anónimo, cero exposición'},
    pt:{'BI-01':'Oferta apenas por exposição','BI-02':'Valor abaixo do piso independente','BI-03':'A exclusividade consome o seu ano','BI-04':'Vida da caixa menor que o bloqueio','BI-05':'Cessão de direitos exigida','BI-06':'Direitos abaixo do piso de margem','BI-07':'Preço da caixa abaixo da margem sustentável','BI-08':'Saúde fraca da caixa','BI-09':'Trabalho anónimo, exposição zero'},
  };
  return titles[l]?.[id] ?? fallback;
}
export function getBoxVerdictLabel(locale: string, verdict: string): string {
  const l = locale.toLowerCase().split('-')[0] as LanguageCode;
  const map: Record<LanguageCode, Record<string,string>> = {
    en:{'Skip — exposure-only trap':'Skip — exposure-only trap','Fee below opportunity cost':'Fee below opportunity cost','Marginally acceptable':'Marginally acceptable','Take it — beats self-publish':'Take it — beats self-publish','Negotiate — fee + royalties':'Negotiate — fee + royalties'},
    de:{'Skip — exposure-only trap':'Ablehnen — nur Reichweitenfalle','Fee below opportunity cost':'Honorar unter Opportunitätskosten','Marginally acceptable':'Bedingt akzeptabel','Take it — beats self-publish':'Annehmen — besser als Selbstveröffentlichung','Negotiate — fee + royalties':'Verhandeln — Honorar plus Lizenz'},
    fr:{'Skip — exposure-only trap':'Refuser — piège de visibilité','Fee below opportunity cost':'Rémunération sous le coût d’opportunité','Marginally acceptable':'Acceptable avec réserves','Take it — beats self-publish':'Accepter — mieux que l’autoédition','Negotiate — fee + royalties':'Négocier — rémunération et redevances'},
    es:{'Skip — exposure-only trap':'Rechazar — trampa de exposición','Fee below opportunity cost':'Tarifa por debajo del coste de oportunidad','Marginally acceptable':'Aceptable con reservas','Take it — beats self-publish':'Aceptar — supera la autopublicación','Negotiate — fee + royalties':'Negociar — tarifa y regalías'},
    pt:{'Skip — exposure-only trap':'Recusar — armadilha de exposição','Fee below opportunity cost':'Valor abaixo do custo de oportunidade','Marginally acceptable':'Aceitável com reservas','Take it — beats self-publish':'Aceitar — supera a autopublicação','Negotiate — fee + royalties':'Negociar — valor e direitos'},
  };
  return map[l]?.[verdict] ?? verdict;
}

export function getBoxFlagNote(locale: string, id: string, fallback: string): string {
  const l = locale.toLowerCase().split('-')[0] as LanguageCode;
  const notes: Record<LanguageCode, Record<string,string>> = {
    en:{'BI-01':'An exposure-only offer makes your unpaid work the box’s marketing budget; judge it as unpaid labour, not promotion.','BI-02':'This fee is below a credible independent-design floor once design, sampling, editing, and knitting time are counted.','BI-03':'This lock removes the design from your own shop for most of a selling year and can cost the strongest season.','BI-04':'The box may fail before the exclusivity ends, leaving the design locked away without residual payments.','BI-05':'Rights or first-publication assignment can prevent resale, bundling, and re-release under your own name.','BI-06':'A royalty below the margin floor is marketing budget presented as participation.','BI-07':'A low retail price leaves too little room for shipping, packaging, fulfillment, and a sustainable designer fee.','BI-08':'Weak box health increases the chance that payout stops before the exclusivity period ends; investigate the operator before signing.','BI-09':'Without a byline there is no meaningful exposure funnel; evaluate this as an anonymous fee-only job.'},
    de:{'BI-01':'Ein Angebot nur für Reichweite macht deine unbezahlte Arbeit zum Marketingbudget der Box; bewerte es als Arbeit, nicht als Werbung.','BI-02':'Dieses Honorar liegt unter einer glaubwürdigen Indie-Untergrenze, sobald Design-, Muster- und Teststrickzeit zählen.','BI-03':'Diese Sperre nimmt das Design für den größten Teil eines Verkaufsjahres aus deinem Shop.','BI-04':'Die Box kann vor Ende der Exklusivität scheitern und das Design ohne Restzahlungen blockieren.','BI-05':'Rechte- oder Erstveröffentlichungsübertragung kann Wiederverkauf und spätere Veröffentlichung verhindern.','BI-06':'Eine Lizenz unter der Margenuntergrenze ist Marketingbudget in einer anderen Verpackung.','BI-07':'Ein niedriger Verkaufspreis lässt zu wenig Raum für Versand, Verpackung, Abwicklung und ein nachhaltiges Honorar.','BI-08':'Schwache Box-Gesundheit erhöht das Risiko ausbleibender Zahlungen; prüfe den Betreiber vor der Unterschrift.','BI-09':'Ohne Namensnennung gibt es keinen sinnvollen Reichweiten-Funnel; bewerte es als anonyme Arbeit gegen Honorar.'},
    fr:{'BI-01':'Une offre fondée uniquement sur la visibilité transforme votre travail non rémunéré en budget marketing de la box.','BI-02':'Cette rémunération est sous un plancher crédible une fois le design, les échantillons et le test tricot comptés.','BI-03':'Ce verrou retire le design de votre boutique pendant la majeure partie d’une année de vente.','BI-04':'La box peut disparaître avant la fin de l’exclusivité, sans paiements résiduels.','BI-05':'Une cession de droits peut empêcher la revente, les bundles et la republication sous votre nom.','BI-06':'Une redevance sous le plancher de marge est un budget marketing déguisé.','BI-07':'Un prix bas laisse trop peu de place à l’expédition, au conditionnement et à une rémunération viable.','BI-08':'Une santé fragile augmente le risque d’arrêt des paiements ; renseignez-vous sur l’opérateur avant de signer.','BI-09':'Sans crédit, l’entonnoir de visibilité est nul ; évaluez ce travail comme une mission anonyme rémunérée.'},
    es:{'BI-01':'Una oferta solo por exposición convierte tu trabajo no pagado en el presupuesto de marketing de la caja.','BI-02':'La tarifa queda por debajo de un mínimo independiente creíble al contar diseño, muestras y tejido de prueba.','BI-03':'Este bloqueo retira el diseño de tu tienda durante la mayor parte del año de ventas.','BI-04':'La caja puede cerrar antes de acabar la exclusividad y dejar el diseño bloqueado sin pagos residuales.','BI-05':'La cesión de derechos puede impedir revender, agrupar y volver a publicar bajo tu nombre.','BI-06':'Una regalía por debajo del margen mínimo es presupuesto de marketing disfrazado.','BI-07':'Un precio bajo deja poco espacio para envío, embalaje, logística y una tarifa sostenible.','BI-08':'La salud débil aumenta el riesgo de que los pagos terminen antes de la exclusividad; investiga al operador.','BI-09':'Sin crédito no hay embudo de exposición; evalúalo como trabajo anónimo pagado.'},
    pt:{'BI-01':'Uma oferta apenas por exposição transforma o seu trabalho não pago no orçamento de marketing da caixa.','BI-02':'O valor está abaixo de um piso independente credível quando se contam design, amostras e teste de tricot.','BI-03':'Este bloqueio retira o design da sua loja durante a maior parte do ano de vendas.','BI-04':'A caixa pode fechar antes do fim da exclusividade, deixando o design bloqueado sem pagamentos residuais.','BI-05':'A cessão de direitos pode impedir revenda, bundles e republicação em seu nome.','BI-06':'Direitos abaixo do piso de margem são orçamento de marketing disfarçado.','BI-07':'Um preço baixo deixa pouco espaço para envio, embalagem, logística e um valor sustentável.','BI-08':'Uma saúde fraca aumenta o risco de os pagamentos pararem; investigue o operador antes de assinar.','BI-09':'Sem crédito não há funil de exposição relevante; avalie como trabalho anónimo pago.'},
  };
  return notes[l]?.[id] ?? fallback;
}
export function getBoxVerdictNote(locale: string, verdict: string, fallback: string): string {
  const l = locale.toLowerCase().split('-')[0] as LanguageCode;
  const notes: Record<LanguageCode, Record<string,string>> = {
    en:{'Skip — exposure-only trap':'Do not trade design time for vague exposure; ask for a fee or a measurable, transferable audience benefit.','Fee below opportunity cost':'The offer does not cover the shop income and production time it displaces.','Marginally acceptable':'The offer clears some costs but leaves little edge after exclusivity and box risk.','Take it — beats self-publish':'The fee and expected value beat the self-publish baseline after the lock is priced in.','Negotiate — fee + royalties':'The offer is close; ask for a stronger fee, a per-box royalty, and a shorter lock.'},
    de:{'Skip — exposure-only trap':'Tausche keine Designzeit gegen vage Reichweite; verlange ein Honorar oder einen messbaren Vorteil.','Fee below opportunity cost':'Das Angebot deckt den verdrängten Shopumsatz und die Produktionszeit nicht.','Marginally acceptable':'Das Angebot deckt einige Kosten, lässt nach Risiko und Exklusivität aber wenig Spielraum.','Take it — beats self-publish':'Honorar und erwarteter Wert übertreffen die Selbstveröffentlichungs-Baseline.','Negotiate — fee + royalties':'Das Angebot ist knapp; verlange ein höheres Honorar, Lizenz und kürzere Sperre.'},
    fr:{'Skip — exposure-only trap':'Ne troquez pas le temps de design contre une visibilité vague ; demandez une rémunération mesurable.','Fee below opportunity cost':'L’offre ne couvre pas le revenu de boutique et le temps de production remplacés.','Marginally acceptable':'L’offre couvre certains coûts mais laisse peu de marge après exclusivité et risque.','Take it — beats self-publish':'La rémunération et la valeur attendue dépassent la base d’autoédition.','Negotiate — fee + royalties':'L’offre est proche ; demandez une meilleure rémunération, une redevance et un verrou plus court.'},
    es:{'Skip — exposure-only trap':'No cambies tiempo de diseño por exposición vaga; pide una tarifa o un beneficio medible.','Fee below opportunity cost':'La oferta no cubre los ingresos de tienda ni el tiempo de producción desplazados.','Marginally acceptable':'Cubre algunos costes, pero deja poco margen después del riesgo y la exclusividad.','Take it — beats self-publish':'La tarifa y el valor esperado superan la base de autopublicación.','Negotiate — fee + royalties':'Está cerca; pide una tarifa mayor, regalía por caja y bloqueo más corto.'},
    pt:{'Skip — exposure-only trap':'Não troque tempo de design por exposição vaga; peça um valor ou benefício mensurável.','Fee below opportunity cost':'A oferta não cobre a receita da loja e o tempo de produção que substitui.','Marginally acceptable':'Cobre alguns custos, mas deixa pouca margem após exclusividade e risco da caixa.','Take it — beats self-publish':'O valor e a expectativa superam a base de autopublicação.','Negotiate — fee + royalties':'Está perto; peça um valor maior, direitos por caixa e um bloqueio mais curto.'},
  };
  return notes[l]?.[verdict] ?? fallback;
}

export const BOX_INCLUSION_COPY = COPY;
