import type { LanguageCode } from '@/lib/i18n';
import type { BragCardTemplate, BragStats } from '@/lib/brag-card';
import { fmtMoney } from '@/lib/receipt-lab';

export interface BragCardCopy {
  sales: string; published: string; profitableMonths: string; bestMonth: string; earned: string; patternSales: string;
  oneStudio: string; monthsAllProfitable: string; onRecord: string; total: string; averagePerSale: string;
  ledger: string; honestLedger: string; knitLocal: string; report: string; oneStudioMeta: string; cameo: string;
  title: string; description: string; empty: string; studioName: string; studioPlaceholder: string; streakCaption: string; publishedHeadline: string; publishedCaption: string; highlight: string; style: string; accent: string; preview: string; captionLabel: string; copyCaption: string; share: string; download: string; cardSaved: string; pngReady: string; exportFailed: string; copyFailed: string; shared: string;
  caption: (stats: BragStats, currency: string, template: BragCardTemplate, studioName: string) => { headline: string; subline: string; caption: string };
}

const make = (locale: LanguageCode, words: Omit<BragCardCopy, 'caption'> & { caption?: BragCardCopy['caption'] }): BragCardCopy => ({
  ...words,
  caption: words.caption ?? ((stats, currency, template, studioName) => {
    const rev = fmtMoney(stats.totalRevenue, currency);
    const perSale = fmtMoney(stats.revenuePerSale, currency);
    const best = stats.bestMonth ? `${words.bestMonth}: ${fmtMoney(stats.bestMonthProfit, currency)}` : '';
    const prefix = studioName ? `${studioName}: ` : '';
    if (template === 'income') return { headline: `${rev} ${words.patternSales}`, subline: `${stats.totalSales} ${words.sales}${best ? ` · ${best}` : ''}`, caption: `${prefix}${rev} ${words.earned} — ${stats.totalSales} ${words.sales}, ${perSale} ${words.averagePerSale}.` };
    if (template === 'sales') return { headline: `${stats.totalSales} ${words.sales}, ${words.oneStudio}`, subline: `${perSale} ${words.averagePerSale}${best ? ` · ${best}` : ''}`, caption: `${prefix}${stats.totalSales} ${words.sales}, ${rev} ${words.total}.` };
    if (template === 'streak') return { headline: `${stats.profitMonths} ${words.monthsAllProfitable}`, subline: `${words.onRecord} · ${rev} ${words.total}`, caption: `${prefix}${words.streakCaption.replace('{count}', String(stats.profitMonths)).replace('{total}', rev)}` };
    return { headline: `${stats.publishedCount} ${words.publishedHeadline}`, subline: `${rev} ${words.earned} · ${stats.totalSales} ${words.sales}`, caption: `${prefix}${words.publishedCaption.replace('{count}', String(stats.publishedCount)).replace('{revenue}', rev).replace('{sales}', String(stats.totalSales))}` };
  }),
});

export const BRAG_COPY: Record<LanguageCode, BragCardCopy> = {
  en: make('en', { title: 'Brag Cards', studioPlaceholder: 'My Studio', streakCaption: '{count} months in a row finishing above zero. {total} on the books and still designing. This is what a real design studio looks like.', publishedHeadline: 'patterns published', publishedCaption: '{count} published patterns, {revenue} earned, {sales} sales. The portfolio is the résumé.', description: 'Turn your own ledger into a shareable card — your numbers, your studio name, and a caption that sounds like you.', empty: 'Nothing to brag about yet — log sales in Receipt Lab or publish a design in Design Ledger and the cards will fill themselves in.', studioName: 'Studio name on the card', highlight: 'Pick your highlight', style: 'Card style', accent: 'Card accent', preview: 'Card preview (1080 × 1080)', captionLabel: 'Caption', copyCaption: 'Copy caption', share: 'Share', download: 'Download PNG', cardSaved: 'Card saved', pngReady: 'PNG ready to share anywhere.', exportFailed: 'Card export failed', copyFailed: 'Copy failed', shared: 'Shared', sales: 'sales', published: 'published', profitableMonths: 'profitable months', bestMonth: 'best month', earned: 'earned from pattern sales', patternSales: 'in pattern sales', oneStudio: 'one studio', monthsAllProfitable: 'months, all profitable', onRecord: 'on record', total: 'total', averagePerSale: 'average per sale', ledger: 'THE LEDGER', honestLedger: 'HONEST LEDGER', knitLocal: 'KNIT LOCAL', report: 'LEDGER REPORT', oneStudioMeta: 'ONE STUDIO', cameo: 'CAMEO' }),
  de: make('de', { title: 'Brag Cards', studioPlaceholder: 'Mein Studio', streakCaption: '{count} Monate in Folge über null. {total} insgesamt und weiterhin im Designprozess.', publishedHeadline: 'Muster veröffentlicht', publishedCaption: '{count} veröffentlichte Muster, {revenue} verdient, {sales} Verkäufe.', description: 'Verwandle dein eigenes Ledger in eine teilbare Karte — deine Zahlen, dein Studio und eine Bildunterschrift, die nach dir klingt.', empty: 'Noch nichts zum Prahlen — erfasse Verkäufe im Receipt Lab oder veröffentliche ein Design im Design Ledger.', studioName: 'Studio-Name auf der Karte', highlight: 'Highlight auswählen', style: 'Kartendesign', accent: 'Kartenakzent', preview: 'Kartenvorschau (1080 × 1080)', captionLabel: 'Bildunterschrift', copyCaption: 'Bildunterschrift kopieren', share: 'Teilen', download: 'PNG herunterladen', cardSaved: 'Karte gespeichert', pngReady: 'PNG zum Teilen bereit.', exportFailed: 'Kartenexport fehlgeschlagen', copyFailed: 'Kopieren fehlgeschlagen', shared: 'Geteilt', sales: 'Verkäufe', published: 'veröffentlicht', profitableMonths: 'profitablen Monaten', bestMonth: 'bester Monat', earned: 'aus Musterverkäufen verdient', patternSales: 'aus Musterverkäufen', oneStudio: 'ein Studio', monthsAllProfitable: 'Monate, alle profitabel', onRecord: 'laut Aufzeichnungen', total: 'insgesamt', averagePerSale: 'durchschnittlich pro Verkauf', ledger: 'DAS LEDGER', honestLedger: 'EHRLICHES LEDGER', knitLocal: 'LOKAL GESTRICKT', report: 'LEDGER-BERICHT', oneStudioMeta: 'EIN STUDIO', cameo: 'CAMEO' }),
  fr: make('fr', { title: 'Cartes de réussite', studioPlaceholder: 'Mon atelier', streakCaption: '{count} mois consécutifs au-dessus de zéro. {total} au total, et la création continue.', publishedHeadline: 'modèles publiés', publishedCaption: '{count} modèles publiés, {revenue} gagnés, {sales} ventes.', description: 'Transformez votre registre en carte à partager — vos chiffres, votre atelier et une légende qui vous ressemble.', empty: 'Pas encore de quoi se vanter — ajoutez des ventes dans Receipt Lab ou publiez un modèle dans Design Ledger.', studioName: 'Nom de l’atelier sur la carte', highlight: 'Choisir un temps fort', style: 'Style de carte', accent: 'Accent de carte', preview: 'Aperçu de la carte (1080 × 1080)', captionLabel: 'Légende', copyCaption: 'Copier la légende', share: 'Partager', download: 'Télécharger le PNG', cardSaved: 'Carte enregistrée', pngReady: 'PNG prêt à être partagé.', exportFailed: 'Échec de l’export de la carte', copyFailed: 'Échec de la copie', shared: 'Partagé', sales: 'ventes', published: 'publiés', profitableMonths: 'mois bénéficiaires', bestMonth: 'meilleur mois', earned: 'gagnés grâce aux ventes de patrons', patternSales: 'de ventes de patrons', oneStudio: 'un atelier', monthsAllProfitable: 'mois, tous bénéficiaires', onRecord: 'au registre', total: 'au total', averagePerSale: 'en moyenne par vente', ledger: 'LE REGISTRE', honestLedger: 'REGISTRE HONNÊTE', knitLocal: 'TRICOT LOCAL', report: 'RAPPORT DU REGISTRE', oneStudioMeta: 'UN ATELIER', cameo: 'CAMEO' }),
  es: make('es', { title: 'Tarjetas de logro', studioPlaceholder: 'Mi estudio', streakCaption: '{count} meses seguidos por encima de cero. {total} en total y el diseño continúa.', publishedHeadline: 'patrones publicados', publishedCaption: '{count} patrones publicados, {revenue} ganados, {sales} ventas.', description: 'Convierte tu registro en una tarjeta para compartir — tus cifras, tu estudio y un texto que suene a ti.', empty: 'Aún no hay nada que celebrar — registra ventas en Receipt Lab o publica un diseño en Design Ledger.', studioName: 'Nombre del estudio en la tarjeta', highlight: 'Elige tu destacado', style: 'Estilo de tarjeta', accent: 'Acento de tarjeta', preview: 'Vista previa (1080 × 1080)', captionLabel: 'Texto', copyCaption: 'Copiar texto', share: 'Compartir', download: 'Descargar PNG', cardSaved: 'Tarjeta guardada', pngReady: 'PNG listo para compartir.', exportFailed: 'Error al exportar la tarjeta', copyFailed: 'Error al copiar', shared: 'Compartido', sales: 'ventas', published: 'publicados', profitableMonths: 'meses rentables', bestMonth: 'mejor mes', earned: 'ganados con ventas de patrones', patternSales: 'en ventas de patrones', oneStudio: 'un estudio', monthsAllProfitable: 'meses, todos rentables', onRecord: 'en el registro', total: 'en total', averagePerSale: 'de media por venta', ledger: 'EL REGISTRO', honestLedger: 'REGISTRO HONESTO', knitLocal: 'TEJIDO LOCAL', report: 'INFORME DEL REGISTRO', oneStudioMeta: 'UN ESTUDIO', cameo: 'CAMEO' }),
  pt: make('pt', { title: 'Cartões de conquista', studioPlaceholder: 'O meu estúdio', streakCaption: '{count} meses seguidos acima de zero. {total} no total e o design continua.', publishedHeadline: 'padrões publicados', publishedCaption: '{count} padrões publicados, {revenue} ganhos, {sales} vendas.', description: 'Transforme o seu registo num cartão partilhável — os seus números, o seu estúdio e uma legenda com a sua voz.', empty: 'Ainda não há nada para celebrar — registe vendas no Receipt Lab ou publique um design no Design Ledger.', studioName: 'Nome do estúdio no cartão', highlight: 'Escolha o destaque', style: 'Estilo do cartão', accent: 'Destaque do cartão', preview: 'Pré-visualização (1080 × 1080)', captionLabel: 'Legenda', copyCaption: 'Copiar legenda', share: 'Partilhar', download: 'Descarregar PNG', cardSaved: 'Cartão guardado', pngReady: 'PNG pronto para partilhar.', exportFailed: 'Falha ao exportar o cartão', copyFailed: 'Falha ao copiar', shared: 'Partilhado', sales: 'vendas', published: 'publicados', profitableMonths: 'meses rentáveis', bestMonth: 'melhor mês', earned: 'ganhos com vendas de padrões', patternSales: 'em vendas de padrões', oneStudio: 'um estúdio', monthsAllProfitable: 'meses, todos rentáveis', onRecord: 'no registo', total: 'no total', averagePerSale: 'em média por venda', ledger: 'O REGISTO', honestLedger: 'REGISTO HONESTO', knitLocal: 'TRICÔ LOCAL', report: 'RELATÓRIO DO REGISTO', oneStudioMeta: 'UM ESTÚDIO', cameo: 'CAMEO' }),
};

export function getBragCardCopy(locale: string): BragCardCopy {
  const code = locale.toLowerCase().split('-')[0] as LanguageCode;
  return BRAG_COPY[code] ?? BRAG_COPY.en;
}
