import type { LanguageCode } from '@/lib/i18n';
export interface ChannelFunnelCopy { title:string; description:string; offer:string; channelType:string; channelName:string; channelPlaceholder:string; designFee:string; extras:string; exclusivity:string; reach:string; visit:string; conversion:string; spend:string; effect:string; baseline:string; patternPrice:string; hours:string; buffer:string; defunct:string; selfSell:string; exclusiveYes:string; exclusiveNo:string; insert:string; writing:string; deadline:string; funnel:string; pitch:string; copied:string; copyManual:string; listSize:string; newLeads:string; launchConversion:string; launchPrice:string; launchWeek:string; evergreen:string; copyPitch:string; }
const en:ChannelFunnelCopy={title:'Channel & Funnel Planner',description:'Price a subscription box, brand collab or magazine offer against what self-publishing would earn — and see whether your email list turns releases into real money.',offer:'Channel offer (box, brand, magazine)',channelType:'Channel type',channelName:'Channel name',channelPlaceholder:'e.g. The Wool Parcels',designFee:'Design fee ($)',extras:'Extras value ($)',exclusivity:'Exclusivity (months)',reach:'Audience reach (subs)',visit:'Visit your shop (%)',conversion:'Visitor conversion (%)',spend:'Avg visitor spend ($)',effect:'Effect runs (months)',baseline:'Your baseline sales (units/mo)',patternPrice:'Pattern price ($)',hours:'Work hours',buffer:'Deadline buffer (weeks)',defunct:'Channel defunct risk (%)',selfSell:'Self-sell during exclusivity',exclusiveYes:"Exclusive (can't self-sell)",exclusiveNo:'Not exclusive',insert:'Marketing insert in the box',writing:'Fee & terms in writing',deadline:'Deadline',funnel:'Email funnel and release-week baseline',pitch:'Pitch builder',listSize:'List size',newLeads:'New leads/mo (freebie)',launchConversion:'Launch conversion (%)',launchPrice:'Launch price ($)',launchWeek:'Launch-week share (%)',evergreen:'Evergreen conversion (%)',copyPitch:'Copy pitch',copied:'Copied to clipboard',copyManual:'Select and copy manually'};
const de:ChannelFunnelCopy={...en,title:'Kanal- und Funnel-Planer',description:'Bewerte ein Box-, Marken- oder Magazinangebot gegenüber der Selbstveröffentlichung und prüfe, ob deine E-Mail-Liste echte Umsätze erzeugt.',offer:'Kanalangebot (Box, Marke, Magazin)',channelType:'Kanaltyp',channelName:'Kanalname',channelPlaceholder:'z. B. The Wool Parcels',designFee:'Designhonorar ($)',extras:'Wert der Extras ($)',exclusivity:'Exklusivität (Monate)',reach:'Reichweite (Abonnenten)',visit:'Besuch in deinem Shop (%)',conversion:'Besucherkonversion (%)',spend:'Durchschn. Ausgaben pro Besuch ($)',effect:'Wirkungsdauer (Monate)',baseline:'Deine Baseline-Verkäufe (Stk./Monat)',patternPrice:'Musterpreis ($)',hours:'Arbeitsstunden',buffer:'Puffer bis zur Frist (Wochen)',defunct:'Risiko für Kanalausfall (%)',selfSell:'Selbstverkauf während Exklusivität',exclusiveYes:'Exklusiv (kein Selbstverkauf)',exclusiveNo:'Nicht exklusiv',insert:'Marketingbeilage in der Box',writing:'Honorar und Bedingungen schriftlich',deadline:'Frist',funnel:'E-Mail-Funnel und Release-Woche',pitch:'Pitch-Builder',listSize:'Listengröße',newLeads:'Neue Leads/Monat (Freebie)',launchConversion:'Launch-Konversion (%)',launchPrice:'Launchpreis ($)',launchWeek:'Anteil der Launch-Woche (%)',evergreen:'Evergreen-Konversion (%)',copyPitch:'Pitch kopieren',copied:'In Zwischenablage kopiert',copyManual:'Markieren und manuell kopieren'};
const fr:ChannelFunnelCopy={...en,title:'Planificateur de canal et d’entonnoir',description:'Comparez une offre de box, de marque ou de magazine à l’autoédition et vérifiez si votre liste e-mail génère de vrais revenus.',offer:'Offre du canal (box, marque, magazine)',channelType:'Type de canal',channelName:'Nom du canal',channelPlaceholder:'ex. The Wool Parcels',designFee:'Rémunération du design ($)',extras:'Valeur des extras ($)',exclusivity:'Exclusivité (mois)',reach:'Portée (abonnés)',visit:'Visite de votre boutique (%)',conversion:'Conversion des visiteurs (%)',spend:'Dépense moyenne par visite ($)',effect:'Durée d’effet (mois)',baseline:'Ventes de base (unités/mois)',patternPrice:'Prix du patron ($)',hours:'Heures de travail',buffer:'Marge avant échéance (semaines)',defunct:'Risque de disparition du canal (%)',selfSell:'Vente autonome pendant l’exclusivité',exclusiveYes:'Exclusif (pas de vente autonome)',exclusiveNo:'Non exclusif',insert:'Encart marketing dans la box',writing:'Rémunération et conditions écrites',deadline:'Échéance',funnel:'Entonnoir e-mail et semaine de sortie',pitch:'Créateur de pitch',listSize:'Taille de la liste',newLeads:'Nouveaux leads/mois (cadeau)',launchConversion:'Conversion du lancement (%)',launchPrice:'Prix de lancement ($)',launchWeek:'Part de la semaine de sortie (%)',evergreen:'Conversion evergreen (%)',copyPitch:'Copier le pitch',copied:'Copié dans le presse-papiers',copyManual:'Sélectionnez et copiez manuellement'};
const es:ChannelFunnelCopy={...en,title:'Planificador de canal y embudo',description:'Valora una oferta de caja, marca o revista frente a la autopublicación y comprueba si tu lista de correo genera ingresos reales.',offer:'Oferta del canal (caja, marca, revista)',channelType:'Tipo de canal',channelName:'Nombre del canal',channelPlaceholder:'p. ej. The Wool Parcels',designFee:'Tarifa de diseño ($)',extras:'Valor de extras ($)',exclusivity:'Exclusividad (meses)',reach:'Alcance (suscriptores)',visit:'Visita tu tienda (%)',conversion:'Conversión de visitantes (%)',spend:'Gasto medio por visita ($)',effect:'Duración del efecto (meses)',baseline:'Ventas base (unidades/mes)',patternPrice:'Precio del patrón ($)',hours:'Horas de trabajo',buffer:'Margen de plazo (semanas)',defunct:'Riesgo de desaparición del canal (%)',selfSell:'Venta propia durante la exclusividad',exclusiveYes:'Exclusivo (no puedes vender por tu cuenta)',exclusiveNo:'No exclusivo',insert:'Inserto de marketing en la caja',writing:'Tarifa y condiciones por escrito',deadline:'Plazo',funnel:'Embudo de correo y semana de lanzamiento',pitch:'Constructor de pitch',listSize:'Tamaño de la lista',newLeads:'Nuevos leads/mes (regalo)',launchConversion:'Conversión del lanzamiento (%)',launchPrice:'Precio de lanzamiento ($)',launchWeek:'Parte de la semana de lanzamiento (%)',evergreen:'Conversión evergreen (%)',copyPitch:'Copiar pitch',copied:'Copiado al portapapeles',copyManual:'Selecciona y copia manualmente'};
const pt:ChannelFunnelCopy={...en,title:'Planeador de canal e funil',description:'Compare uma oferta de caixa, marca ou revista com a autopublicação e veja se a sua lista de e-mail gera dinheiro real.',offer:'Oferta do canal (caixa, marca, revista)',channelType:'Tipo de canal',channelName:'Nome do canal',channelPlaceholder:'ex.: The Wool Parcels',designFee:'Valor do design ($)',extras:'Valor dos extras ($)',exclusivity:'Exclusividade (meses)',reach:'Alcance (subscritores)',visit:'Visita à loja (%)',conversion:'Conversão dos visitantes (%)',spend:'Gasto médio por visita ($)',effect:'Duração do efeito (meses)',baseline:'Vendas de base (unidades/mês)',patternPrice:'Preço do padrão ($)',hours:'Horas de trabalho',buffer:'Margem do prazo (semanas)',defunct:'Risco de desaparecimento do canal (%)',selfSell:'Venda própria durante a exclusividade',exclusiveYes:'Exclusivo (não pode vender por conta própria)',exclusiveNo:'Não exclusivo',insert:'Inserção de marketing na caixa',writing:'Valor e condições por escrito',deadline:'Prazo',funnel:'Funil de e-mail e semana de lançamento',pitch:'Criador de pitch',listSize:'Tamanho da lista',newLeads:'Novos leads/mês (oferta)',launchConversion:'Conversão do lançamento (%)',launchPrice:'Preço de lançamento ($)',launchWeek:'Parte da semana de lançamento (%)',evergreen:'Conversão evergreen (%)',copyPitch:'Copiar pitch',copied:'Copiado para a área de transferência',copyManual:'Selecione e copie manualmente'};
export const COPY:Record<LanguageCode,ChannelFunnelCopy>={en,de,fr,es,pt};

export function getChannelTypeLabel(locale:string, type:string, fallback:string):string {
  const l=locale.toLowerCase().split('-')[0] as LanguageCode;
  const labels:Record<LanguageCode,Record<string,string>>={
    en:{subbox:'Subscription box','brand-collab':'Yarn-brand collab',magazine:'Magazine / anthology',other:'Other placement'},
    de:{subbox:'Abonnement-Box','brand-collab':'Yarn-Markenkooperation',magazine:'Magazin / Anthologie',other:'Andere Platzierung'},
    fr:{subbox:'Box d’abonnement','brand-collab':'Collaboration avec une marque de laine',magazine:'Magazine / anthologie',other:'Autre placement'},
    es:{subbox:'Caja de suscripción','brand-collab':'Colaboración con marca de lana',magazine:'Revista / antología',other:'Otra colocación'},
    pt:{subbox:'Caixa de subscrição','brand-collab':'Colaboração com marca de fios',magazine:'Revista / antologia',other:'Outra colocação'},
  };
  return labels[l]?.[type]??fallback;
}
export function getChannelVerdictLabel(locale:string, verdict:string):string {
  const l=locale.toLowerCase().split('-')[0] as LanguageCode;
  const labels:Record<LanguageCode,Record<string,string>>={
    en:{go:'GO',maybe:'MAYBE',no:'NO'},de:{go:'JA',maybe:'VIELLEICHT',no:'NEIN'},fr:{go:'OUI',maybe:'PEUT-ÊTRE',no:'NON'},es:{go:'SÍ',maybe:'QUIZÁ',no:'NO'},pt:{go:'SIM',maybe:'TALVEZ',no:'NÃO'}
  };
  return labels[l]?.[verdict]??verdict.toUpperCase();
}
export function getChannelNote(locale:string,note:string):string {
  const l=locale.toLowerCase().split('-')[0] as LanguageCode;
  const prefixes:Record<LanguageCode,string>={en:'',de:'Hinweis: ',fr:'Note : ',es:'Nota: ',pt:'Nota: '};
  return l==='en'?note:`${prefixes[l]}${note}`;
}

export const CHANNEL_FUNNEL_COPY = COPY;
