import { LanguageCode } from './i18n';

export interface CollaborationCopy {
  title: string;
  roster: string;
  addMember: string;
  nameLabel: string;
  roleLabel: string;
  statusLabel: string;
  inviteButton: string;
  editor: string;
  tester: string;
  viewer: string;
  invited: string;
  active: string;
  completed: string;
  ghosted: string;
  issueTracking: string;
  addIssue: string;
  assigneeLabel: string;
  dueDateLabel: string;
  locationLabel: string;
  comments: string;
  addComment: string;
  commentPlaceholder: string;
  evidenceLabel: string;
  reproductionLabel: string;
  dispositionLabel: string;
  resolutionLabel: string;
  statusNeedsTestKnit: string;
  testKnitRounds: string;
  addRound: string;
  testerLabel: string;
  sizeLabel: string;
  gaugeLabel: string;
  yarnLabel: string;
  startDateLabel: string;
  endDateLabel: string;
  observationsLabel: string;
  followUpLabel: string;
  noRounds: string;
  deleteRoundConfirm: string;
  testKnitArchive: string;
  testKnitArchiveDescription: string;
  noRoundsYet: string;
  noRoundsDescription: string;
  startFirstRound: string;
  testers: string;
  viewDetails: string;
  recordRoundDescription: string;
  cancelled: string;
  saveRound: string;
  roundUpdated: string;
}

export const COLLABORATION_COPY: Record<LanguageCode, CollaborationCopy> = {
  en: {
    title: 'Collaboration',
    roster: 'Team Roster',
    addMember: 'Invite Member',
    nameLabel: 'Name',
    roleLabel: 'Role',
    statusLabel: 'Status',
    inviteButton: 'Send Invite',
    editor: 'Technical Editor',
    tester: 'Test Knitter',
    viewer: 'Viewer',
    invited: 'Invited',
    active: 'Active',
    completed: 'Completed',
    ghosted: 'Ghosted',
    issueTracking: 'Issue Tracking',
    addIssue: 'Report Issue',
    assigneeLabel: 'Assignee',
    dueDateLabel: 'Due Date',
    locationLabel: 'Location',
    comments: 'Comments',
    addComment: 'Post Comment',
    commentPlaceholder: 'Write a comment...',
    evidenceLabel: 'Evidence',
    reproductionLabel: 'Reproduction',
    dispositionLabel: 'Disposition',
    resolutionLabel: 'Resolution Note',
    statusNeedsTestKnit: 'Needs Test Knit',
    testKnitRounds: 'Test-Knit Rounds',
    addRound: 'Add Round',
    testerLabel: 'Tester',
    sizeLabel: 'Size',
    gaugeLabel: 'Gauge',
    yarnLabel: 'Yarn',
    startDateLabel: 'Start Date',
    endDateLabel: 'End Date',
    observationsLabel: 'Observations',
    followUpLabel: 'Follow-up',
    noRounds: 'No test-knit rounds recorded.',
    deleteRoundConfirm: 'Are you sure you want to delete this test-knit round?',
    testKnitArchive: 'Test-Knit Archive',
    testKnitArchiveDescription: 'Durable history of physical testing rounds.',
    noRoundsYet: 'No rounds yet',
    noRoundsDescription: 'Record your first test-knit round to start building a history of physical testing for this pattern.',
    startFirstRound: 'Start First Round',
    testers: 'Testers',
    viewDetails: 'View Details',
    recordRoundDescription: 'Record a physical testing round for this design.',
    cancelled: 'Cancelled',
    saveRound: 'Save Round',
    roundUpdated: 'Test-knit round updated',
  },
  de: {
    title: 'Zusammenarbeit',
    roster: 'Teamliste',
    addMember: 'Mitglied einladen',
    nameLabel: 'Name',
    roleLabel: 'Rolle',
    statusLabel: 'Status',
    inviteButton: 'Einladung senden',
    editor: 'Technische Redaktion',
    tester: 'Test-Stricker',
    viewer: 'Beobachter',
    invited: 'Eingeladen',
    active: 'Aktiv',
    completed: 'Abgeschlossen',
    ghosted: 'Ghosted',
    issueTracking: 'Fehlerverfolgung',
    addIssue: 'Fehler melden',
    assigneeLabel: 'Zuständig',
    dueDateLabel: 'Fällig am',
    locationLabel: 'Ort',
    comments: 'Kommentare',
    addComment: 'Kommentar posten',
    commentPlaceholder: 'Schreibe einen Kommentar...',
    evidenceLabel: 'Beweis',
    reproductionLabel: 'Reproduktion',
    dispositionLabel: 'Entscheidung',
    resolutionLabel: 'Lösungshinweis',
    statusNeedsTestKnit: 'Test-Stricken erforderlich',
    testKnitRounds: 'Test-Strick-Runden',
    addRound: 'Runde hinzufügen',
    testerLabel: 'Tester',
    sizeLabel: 'Größe',
    gaugeLabel: 'Maschenprobe',
    yarnLabel: 'Garn',
    startDateLabel: 'Startdatum',
    endDateLabel: 'Enddatum',
    observationsLabel: 'Beobachtungen',
    followUpLabel: 'Nachverfolgung',
    noRounds: 'Keine Test-Strick-Runden aufgezeichnet.',
    deleteRoundConfirm: 'Bist du sicher, dass du diese Test-Strick-Runde löschen möchtest?',
    testKnitArchive: 'Teststrick-Archiv',
    testKnitArchiveDescription: 'Dauerhafte Historie physischer Testrunden.',
    noRoundsYet: 'Noch keine Runden',
    noRoundsDescription: 'Erfasse deine erste Teststrick-Runde, um eine Historie der physischen Tests für dieses Muster aufzubauen.',
    startFirstRound: 'Erste Runde starten',
    testers: 'Tester',
    viewDetails: 'Details anzeigen',
    recordRoundDescription: 'Erfasse eine physische Testrunde für dieses Design.',
    cancelled: 'Abgebrochen',
    saveRound: 'Runde speichern',
    roundUpdated: 'Teststrick-Runde aktualisiert',
  },
  fr: {
    title: 'Collaboration',
    roster: 'Liste de l\'équipe',
    addMember: 'Inviter un membre',
    nameLabel: 'Nom',
    roleLabel: 'Rôle',
    statusLabel: 'Statut',
    inviteButton: 'Envoyer l\'invitation',
    editor: 'Éditeur technique',
    tester: 'Testeur de tricot',
    viewer: 'Observateur',
    invited: 'Invité',
    active: 'Actif',
    completed: 'Terminé',
    ghosted: 'Disparu',
    issueTracking: 'Suivi des problèmes',
    addIssue: 'Signaler un problème',
    assigneeLabel: 'Assigné à',
    dueDateLabel: 'Date d\'échéance',
    locationLabel: 'Emplacement',
    comments: 'Commentaires',
    addComment: 'Publier un commentaire',
    commentPlaceholder: 'Écrire un commentaire...',
    evidenceLabel: 'Preuve',
    reproductionLabel: 'Reproduction',
    dispositionLabel: 'Disposition',
    resolutionLabel: 'Note de résolution',
    statusNeedsTestKnit: 'Nécessite un test de tricot',
    testKnitRounds: 'Rondes de test de tricot',
    addRound: 'Ajouter une ronde',
    testerLabel: 'Testeur',
    sizeLabel: 'Taille',
    gaugeLabel: 'Échantillon',
    yarnLabel: 'Fil',
    startDateLabel: 'Date de début',
    endDateLabel: 'Date de fin',
    observationsLabel: 'Observations',
    followUpLabel: 'Suivi',
    noRounds: 'Aucune ronde de test de tricot enregistrée.',
    deleteRoundConfirm: 'Êtes-vous sûr de vouloir supprimer cette ronde de test de tricot ?',
    testKnitArchive: 'Archive des tests de tricot',
    testKnitArchiveDescription: 'Historique durable des tours d\'essais physiques.',
    noRoundsYet: 'Pas encore de rondes',
    noRoundsDescription: 'Enregistrez votre première ronde de test de tricot pour commencer à construire un historique des tests physiques pour ce modèle.',
    startFirstRound: 'Démarrer la première ronde',
    testers: 'Testeurs',
    viewDetails: 'Voir les détails',
    recordRoundDescription: 'Enregistrez un tour d\'essai physique pour ce modèle.',
    cancelled: 'Annulé',
    saveRound: 'Enregistrer le tour',
    roundUpdated: 'Ronde de test de tricot mise à jour',
  },
  es: {
    title: 'Colaboración',
    roster: 'Lista del equipo',
    addMember: 'Invitar miembro',
    nameLabel: 'Nombre',
    roleLabel: 'Rol',
    statusLabel: 'Estado',
    inviteButton: 'Enviar invitación',
    editor: 'Editor técnico',
    tester: 'Tejedor de prueba',
    viewer: 'Observador',
    invited: 'Invitado',
    active: 'Activo',
    completed: 'Completado',
    ghosted: 'Desaparecido',
    issueTracking: 'Seguimiento de problemas',
    addIssue: 'Informar problema',
    assigneeLabel: 'Asignado a',
    dueDateLabel: 'Fecha de vencimiento',
    locationLabel: 'Ubicación',
    comments: 'Comentarios',
    addComment: 'Publicar comentario',
    commentPlaceholder: 'Escribir un comentario...',
    evidenceLabel: 'Evidencia',
    reproductionLabel: 'Reproducción',
    dispositionLabel: 'Disposición',
    resolutionLabel: 'Nota de resolución',
    statusNeedsTestKnit: 'Necesita prueba de tejido',
    testKnitRounds: 'Rondas de prueba de tejido',
    addRound: 'Agregar ronda',
    testerLabel: 'Probador',
    sizeLabel: 'Talla',
    gaugeLabel: 'Muestra',
    yarnLabel: 'Hilo',
    startDateLabel: 'Fecha de inicio',
    endDateLabel: 'Fecha de finalización',
    observationsLabel: 'Observaciones',
    followUpLabel: 'Seguimiento',
    noRounds: 'No se han registrado rondas de prueba de tejido.',
    deleteRoundConfirm: '¿Estás seguro de que deseas eliminar esta ronda de prueba de tejido?',
    testKnitArchive: 'Archivo de pruebas de tejido',
    testKnitArchiveDescription: 'Historial duradero de rondas de pruebas físicas.',
    noRoundsYet: 'Aún no hay rondas',
    noRoundsDescription: 'Registra tu primera ronda de prueba de tejido para comenzar a construir un historial de pruebas físicas para este patrón.',
    startFirstRound: 'Comenzar primera ronda',
    testers: 'Probadores',
    viewDetails: 'Ver detalles',
    recordRoundDescription: 'Registra una ronda de prueba física para este diseño.',
    cancelled: 'Cancelado',
    saveRound: 'Guardar ronda',
    roundUpdated: 'Ronda de prueba de tejido actualizada',
  },
  pt: {
    title: 'Colaboração',
    roster: 'Lista da equipe',
    addMember: 'Convidar membro',
    nameLabel: 'Nome',
    roleLabel: 'Função',
    statusLabel: 'Status',
    inviteButton: 'Enviar convite',
    editor: 'Editor técnico',
    tester: 'Testador de tricô',
    viewer: 'Observador',
    invited: 'Convidado',
    active: 'Ativo',
    completed: 'Concluído',
    ghosted: 'Desaparecido',
    issueTracking: 'Rastreamento de problemas',
    addIssue: 'Relatar problema',
    assigneeLabel: 'Responsável',
    dueDateLabel: 'Data de entrega',
    locationLabel: 'Localização',
    comments: 'Comentários',
    addComment: 'Publicar comentário',
    commentPlaceholder: 'Escrever um comentário...',
    evidenceLabel: 'Evidência',
    reproductionLabel: 'Reprodução',
    dispositionLabel: 'Disposição',
    resolutionLabel: 'Nota de resolução',
    statusNeedsTestKnit: 'Necessita teste de tricô',
    testKnitRounds: 'Rodadas de teste de tricô',
    addRound: 'Adicionar rodada',
    testerLabel: 'Testador',
    sizeLabel: 'Tamanho',
    gaugeLabel: 'Amostra',
    yarnLabel: 'Fio',
    startDateLabel: 'Data de início',
    endDateLabel: 'Data de término',
    observationsLabel: 'Observações',
    followUpLabel: 'Acompanhamento',
    noRounds: 'Nenhuma rodada de teste de tricô registrada.',
    deleteRoundConfirm: 'Tem certeza de que deseja excluir esta rodada de teste de tricô?',
    testKnitArchive: 'Arquivo de testes de tricô',
    testKnitArchiveDescription: 'Histórico durável de rodadas de testes físicos.',
    noRoundsYet: 'Ainda não há rodadas',
    noRoundsDescription: 'Registre sua primeira rodada de teste de tricô para começar a construir um histórico de testes físicos para este padrão.',
    startFirstRound: 'Iniciar primeira rodada',
    testers: 'Testadores',
    viewDetails: 'Ver detalhes',
    recordRoundDescription: 'Registre uma rodada de teste físico para este design.',
    cancelled: 'Cancelado',
    saveRound: 'Salvar rodada',
    roundUpdated: 'Rodada de teste de tricô atualizada',
  },
};
