import type { LanguageCode } from '@/lib/i18n';
export interface ConsignmentRepriceCopy {
  title:string; description:string; printRun:string; shelfLife:string; repriceCost:string;
  retail:string; channel:string; printCost:string; printShare:string; units:string; sold:string; months:string; season:string; hourly:string; hours:string;
  netNow:string; afterCosts:string; stock:string; atUnits:string; deadRisk:string; sunkCost:string; channelHeading:string; toYou:string; fees:string;
  ladder:string; ladderDescription:string; step:string; price:string; netUnit:string; monthsClear:string; totalNet:string; best:string; online:string; watchOuts:string; verdict:string; reset:string;
  channelOptions:Record<string,string>; seasonOptions:Record<string,string>; ofRetail:string; mo:string;
}
const en:ConsignmentRepriceCopy={title:'Consignment Re-Price Lab',description:'Price what your stock sitting at yarn shops is actually worth, then build the re-price ladder before shelf life runs out.',printRun:'The print run',shelfLife:'Shelf life & sell-through',repriceCost:'Re-price cost',retail:'Retail price',channel:'Channel the stock sits in',printCost:'Print cost per copy',printShare:'Print cost share',units:'Units at shop(s)',sold:'Units sold per month (current price)',months:'Months in shop',season:'Season band',hourly:'Your hourly rate',hours:'Hours to re-price',netNow:'Net per unit now',afterCosts:'After split, fees & print cost',stock:'Stock on hand',atUnits:'At {units} units & {sold}/mo',deadRisk:'Dead-stock risk',sunkCost:'Sunk print cost if it never moves',channelHeading:'Net per unit, by channel (at {price})',toYou:'to you',fees:'fees',ladder:'The re-price ladder',ladderDescription:'Each step: price, your net per unit, months to clear current stock, total net on {units} units.',step:'Step',price:'Price',netUnit:'Net/unit',monthsClear:'Months to clear',totalNet:'Total net',best:'BEST',online:'online',watchOuts:'Watch-outs',verdict:'Verdict',reset:'Reset to example',channelOptions:{'ravelry-instore':'Ravelry In-Store (60/40)','consignment-direct':'Direct consignment (45/55)','own-shop':'Own shop / online (97/3)'},seasonOptions:{winter:'Winter (peak Oct–Dec)',spring:'Spring (peak Jan–Mar)',summer:'Summer (peak Apr–Jun)',yearround:'Year-round'},ofRetail:'of retail',mo:'mo'};
const de:ConsignmentRepriceCopy={...en,title:'Kommissions-Neupreis-Labor',description:'Ermittle den Wert deiner Bestände im Wollgeschäft und erstelle eine Neupreisleiter, bevor die Lagerzeit abläuft.',printRun:'Der Drucklauf',shelfLife:'Lagerzeit & Abverkauf',repriceCost:'Kosten der Neupreisgestaltung',retail:'Ladenpreis',channel:'Vertriebskanal',printCost:'Druckkosten pro Exemplar',printShare:'Anteil der Druckkosten',units:'Exemplare im Geschäft',sold:'Verkaufte Exemplare pro Monat (aktueller Preis)',months:'Monate im Geschäft',season:'Saisonband',hourly:'Dein Stundensatz',hours:'Stunden für Neupreis',netNow:'Netto pro Exemplar jetzt',afterCosts:'Nach Anteil, Gebühren & Druckkosten',stock:'Bestand vor Ort',deadRisk:'Risiko unverkäuflicher Ware',sunkCost:'Versunkene Druckkosten, falls nichts verkauft wird',watchOuts:'Warnhinweise',verdict:'Fazit',reset:'Beispiel zurücksetzen'};
const fr:ConsignmentRepriceCopy={...en,title:'Laboratoire de nouveau prix en dépôt',description:'Estimez la valeur du stock en boutique et construisez une grille de prix avant la fin de sa durée en rayon.',printRun:'Le tirage',shelfLife:'Durée en rayon & écoulement',repriceCost:'Coût du nouveau prix',retail:'Prix public',channel:'Canal du stock',printCost:'Coût d’impression par exemplaire',units:'Exemplaires en boutique',sold:'Exemplaires vendus par mois',months:'Mois en boutique',season:'Saison',hourly:'Votre taux horaire',hours:'Heures de repricing',netNow:'Net par exemplaire',stock:'Stock disponible',deadRisk:'Risque d’invendus',watchOuts:'Points d’attention',verdict:'Verdict',reset:'Réinitialiser l’exemple'};
const es:ConsignmentRepriceCopy={...en,title:'Laboratorio de repricing en consignación',description:'Calcula el valor real del stock en tiendas y crea una escalera de precios antes de que termine su vida útil.',printRun:'La tirada',shelfLife:'Vida útil y rotación',repriceCost:'Coste del repricing',retail:'Precio minorista',channel:'Canal del stock',printCost:'Coste de impresión por copia',units:'Unidades en tienda',sold:'Unidades vendidas al mes',months:'Meses en tienda',season:'Temporada',hourly:'Tu tarifa por hora',hours:'Horas para repricing',netNow:'Neto por unidad',stock:'Stock disponible',deadRisk:'Riesgo de stock muerto',watchOuts:'Puntos de atención',verdict:'Veredicto',reset:'Restablecer ejemplo'};
const pt:ConsignmentRepriceCopy={...en,title:'Laboratório de novo preço em consignação',description:'Calcule o valor do stock nas lojas e crie uma escada de preços antes de terminar o tempo em prateleira.',printRun:'A tiragem',shelfLife:'Tempo em prateleira e vendas',repriceCost:'Custo do novo preço',retail:'Preço de venda',channel:'Canal do stock',printCost:'Custo de impressão por cópia',units:'Unidades na loja',sold:'Unidades vendidas por mês',months:'Meses na loja',season:'Estação',hourly:'O seu valor por hora',hours:'Horas para novo preço',netNow:'Líquido por unidade',stock:'Stock disponível',deadRisk:'Risco de stock parado',watchOuts:'Pontos de atenção',verdict:'Veredicto',reset:'Repor exemplo'};
export const CONSIGNMENT_REPRICE_COPY:Record<LanguageCode,ConsignmentRepriceCopy>={en,de,fr,es,pt};

import type { RepriceResult } from '@/lib/consignment-reprice-lab';

const STEP_COPY: Record<LanguageCode, Record<number, [string,string]>> = {
  en:{1:['Hold full price','Sell-through is healthy and the season still supports retail.'],.85:['Light markdown (15% off)','A start-of-next-season nudge; buyers still see it as current stock, not destash.'],.7:['Seasonal markdown (30% off)','The 65–70% band buyers accept for current-condition stock; the standard end-of-season move.'],.55:['Clearance (45% off)','The real-deal band: roughly 2.2× sell-through uplift while staying above the destash floor.'],.5:['Destash floor (50% off)','The floor: aged stock below this reads as clearance-bin and trains buyers to wait.'],0:['Pull back to online-only discount','Remove print copies, sell remaining stock online at a promo price, or fold them into a bundle.']},
  de:{1:['Vollen Preis halten','Der Abverkauf ist gesund und die Saison trägt den Ladenpreis.'],.85:['Leichte Reduzierung (15 %)','Ein Impuls zum Saisonwechsel; der Bestand wirkt noch aktuell, nicht wie Restposten.'],.7:['Saisonale Reduzierung (30 %)','Die akzeptierte Spanne von 65–70 % für aktuellen Bestand.'],.55:['Ausverkauf (45 %)','Ein echter Anreiz mit höherem Abverkauf, ohne die Restposten-Wahrnehmung zu verstärken.'],.5:['Restposten-Grenze (50 %)','Darunter wirkt gealterter Bestand wie Räumungsware und trainiert Kunden zu warten.'],0:['Zurück in den Online-Verkauf','Druckexemplare zurückholen, online rabattiert verkaufen oder bündeln.']},
  fr:{1:['Maintenir le prix','Les ventes sont saines et la saison justifie encore le prix public.'],.85:['Légère remise (15 %)','Un premier geste de début de saison suivante; le stock reste actuel.'],.7:['Remise saisonnière (30 %)','La zone de 65–70 % généralement acceptée pour un stock actuel.'],.55:['Déstockage (45 %)','Une vraie remise qui accélère les ventes tout en restant au-dessus du seuil de déstockage.'],.5:['Seuil de déstockage (50 %)','En dessous, le stock ancien ressemble à une liquidation et incite à attendre.'],0:['Retour à la vente en ligne','Récupérez les imprimés, vendez-les en ligne ou intégrez-les à un lot.']},
  es:{1:['Mantener el precio','Las ventas son saludables y la temporada aún sostiene el precio.'],.85:['Descuento ligero (15 %)','Un primer empujón de cambio de temporada; el stock sigue pareciendo actual.'],.7:['Descuento de temporada (30 %)','La franja del 65–70 % que los compradores aceptan para stock actual.'],.55:['Liquidación (45 %)','Una oferta real que acelera las ventas sin cruzar el umbral de stock de saldo.'],.5:['Umbral de saldo (50 %)','Por debajo, el stock envejecido parece liquidación y enseña a esperar.'],0:['Retirar y vender solo online','Retira las copias, véndelas online con promoción o inclúyelas en un pack.']},
  pt:{1:['Manter o preço','As vendas estão saudáveis e a estação ainda sustenta o preço.'],.85:['Desconto ligeiro (15%)','Um primeiro incentivo na mudança de estação; o stock ainda parece atual.'],.7:['Desconto sazonal (30%)','A faixa de 65–70% que os compradores aceitam para stock atual.'],.55:['Liquidação (45%)','Uma oferta real que acelera as vendas sem ultrapassar o limite de stock antigo.'],.5:['Limite de stock antigo (50%)','Abaixo disso, o stock envelhecido parece liquidação e ensina os clientes a esperar.'],0:['Recolher e vender apenas online','Recolha as cópias, venda-as online em promoção ou inclua-as num conjunto.']}
};

export function localizeConsignmentResult(result: RepriceResult, language: LanguageCode): RepriceResult {
  if (language === 'en') return result;
  const steps = STEP_COPY[language];
  const ladder = result.ladder.map(step => {
    const pair = steps[step.pricePctOfRetail];
    return pair ? {...step, label:pair[0], rationale:pair[1]} : step;
  });
  const best = ladder.find(step => step.pricePctOfRetail === result.bestStep.pricePctOfRetail) ?? result.bestStep;
  const flags = result.flags.map(flag => ({...flag, title: flagTitle(flag.code, language), detail: flagDetail(flag.code, language)}));
  const verdict = verdictCopy(best.label, result, language);
  return {...result, ladder, bestStep:best, flags, verdict};
}
function flagTitle(code:string, language:LanguageCode):string {
  const t:Record<LanguageCode,Record<string,string>>={en:{},de:{'CR-01':'Preis liegt unter der Ravelry-Schwelle','CR-02':'Aktueller Preis bringt keinen positiven Nettoerlös','CR-03':'Drucklauf ist aus der Saison gefallen','CR-04':'Zu viel Bestand auf Lager','CR-05':'Tiefe Rabatte wirken wie Restposten','CR-06':'Ladenanteil über dem üblichen Kommissionsniveau','CR-07':'Arbeitskosten der Neupreisgestaltung sind relevant','CR-08':'Druckkosten übersteigen 25 % des Ladenpreises','CR-09':'Weitere Prüfung erforderlich'},fr:{'CR-01':'Le prix est sous le seuil Ravelry','CR-02':'Le prix actuel ne produit pas de net positif','CR-03':'Le tirage est sorti de sa saison','CR-04':'Stock disponible trop important','CR-05':'Les fortes remises évoquent le déstockage','CR-06':'Part de la boutique supérieure à la norme','CR-07':'Le coût du repricing est significatif','CR-08':'L’impression dépasse 25 % du prix public'},es:{'CR-01':'El precio está bajo el umbral de Ravelry','CR-02':'El precio actual no deja margen positivo','CR-03':'La tirada ha salido de temporada','CR-04':'Hay demasiado stock disponible','CR-05':'Los descuentos profundos parecen liquidación','CR-06':'La parte de la tienda supera la norma','CR-07':'El coste de repricing es relevante','CR-08':'La impresión supera el 25 % del precio'},pt:{'CR-01':'O preço está abaixo do limite Ravelry','CR-02':'O preço atual não gera líquido positivo','CR-03':'A tiragem saiu da estação','CR-04':'Há demasiado stock disponível','CR-05':'Descontos profundos parecem liquidação','CR-06':'A parte da loja está acima da norma','CR-07':'O custo do novo preço é relevante','CR-08':'A impressão ultrapassa 25% do preço'}};
  return t[language]?.[code] ?? code;
}
function flagDetail(code:string, language:LanguageCode):string {
  const generic:Record<LanguageCode,string>={en:'Review the inputs and compare the ladder before committing more time or print cost.',de:'Prüfe die Eingaben und vergleiche die Preisleiter, bevor du weitere Zeit oder Druckkosten bindest.',fr:'Vérifiez les données et comparez la grille avant d’engager davantage de temps ou de frais d’impression.',es:'Revisa los datos y compara la escalera antes de invertir más tiempo o coste de impresión.',pt:'Reveja os dados e compare a escada antes de investir mais tempo ou custos de impressão.'};
  return `${generic[language]} (${code})`;
}
function verdictCopy(label:string, result:RepriceResult, language:LanguageCode):string {
  if(language==='de') return `${label} — die Warnhinweise zeigen, dass die aktuelle Konfiguration Geld oder Lagerzeit kostet.`;
  if(language==='fr') return `${label} — les alertes indiquent que la configuration actuelle coûte de l’argent ou de la durée en rayon.`;
  if(language==='es') return `${label} — las alertas indican que la configuración actual está perdiendo dinero o vida útil.`;
  if(language==='pt') return `${label} — os alertas mostram que a configuração atual está a perder dinheiro ou tempo de prateleira.`;
  return result.verdict;
}

Object.assign(de,{atUnits:'Bei {units} Einheiten und {sold}/Monat',channelHeading:'Netto pro Exemplar nach Kanal (bei {price})',toYou:'für dich',fees:'Gebühren',ladder:'Die Neupreisleiter',ladderDescription:'Jeder Schritt: Preis, dein Netto pro Exemplar, Monate bis zum Abverkauf und Netto auf {units} Einheiten.',step:'Schritt',price:'Preis',netUnit:'Netto/Exemplar',monthsClear:'Monate bis Abverkauf',totalNet:'Gesamtnetto',best:'BESTE WAHL',online:'online',ofRetail:'des Ladenpreises',mo:'Mon.'});
Object.assign(fr,{atUnits:'Pour {units} unités et {sold}/mois',channelHeading:'Net par exemplaire, par canal (à {price})',toYou:'pour vous',fees:'frais',ladder:'La grille de nouveau prix',ladderDescription:'Chaque étape : prix, net par exemplaire, mois pour écouler le stock et net total sur {units} unités.',step:'Étape',price:'Prix',netUnit:'Net/unité',monthsClear:'Mois pour écouler',totalNet:'Net total',best:'MEILLEUR',online:'en ligne',ofRetail:'du prix public',mo:'mois'});
Object.assign(es,{atUnits:'Con {units} unidades y {sold}/mes',channelHeading:'Neto por unidad y canal (a {price})',toYou:'para ti',fees:'comisiones',ladder:'La escalera de repricing',ladderDescription:'Cada paso: precio, neto por unidad, meses para liquidar el stock y neto total sobre {units} unidades.',step:'Paso',price:'Precio',netUnit:'Neto/unidad',monthsClear:'Meses para liquidar',totalNet:'Neto total',best:'MEJOR',online:'online',ofRetail:'del precio',mo:'meses'});
Object.assign(pt,{atUnits:'Para {units} unidades e {sold}/mês',channelHeading:'Líquido por unidade, por canal (a {price})',toYou:'para si',fees:'taxas',ladder:'A escada de novo preço',ladderDescription:'Cada passo: preço, líquido por unidade, meses para escoar o stock e líquido total em {units} unidades.',step:'Passo',price:'Preço',netUnit:'Líquido/unidade',monthsClear:'Meses para escoar',totalNet:'Líquido total',best:'MELHOR',online:'online',ofRetail:'do preço',mo:'meses'});
Object.assign(de.channelOptions,{'ravelry-instore':'Ravelry In-Store (60/40)','consignment-direct':'Consignação direta (45/55)','own-shop':'Loja própria / online (97/3)'}); Object.assign(de.seasonOptions,{winter:'Inverno (pico out.–dez.)',spring:'Primavera (pico jan.–mar.)',summer:'Verão (pico abr.–jun.)',yearround:'Todo o ano'});
Object.assign(fr.channelOptions,{'ravelry-instore':'Ravelry In-Store (60/40)','consignment-direct':'Dépôt direct (45/55)','own-shop':'Boutique propre / en ligne (97/3)'}); Object.assign(fr.seasonOptions,{winter:'Hiver (pic oct.–déc.)',spring:'Printemps (pic janv.–mars)',summer:'Été (pic avr.–juin)',yearround:'Toute l’année'});
Object.assign(es.channelOptions,{'ravelry-instore':'Ravelry In-Store (60/40)','consignment-direct':'Consignación directa (45/55)','own-shop':'Tienda propia / online (97/3)'}); Object.assign(es.seasonOptions,{winter:'Invierno (pico oct.–dic.)',spring:'Primavera (pico ene.–mar.)',summer:'Verano (pico abr.–jun.)',yearround:'Todo el año'});
Object.assign(pt.channelOptions,{'ravelry-instore':'Ravelry In-Store (60/40)','consignment-direct':'Consignação direta (45/55)','own-shop':'Loja própria / online (97/3)'}); Object.assign(pt.seasonOptions,{winter:'Inverno (pico out.–dez.)',spring:'Primavera (pico jan.–mar.)',summer:'Verão (pico abr.–jun.)',yearround:'Todo o ano'});
