// CHK-145 localization module — shared localized lab/StatBox labels (was bare English).
import type { LanguageCode } from '@/lib/i18n';

export interface LabStatCopy {
  printingCostPerCopy: string;
  netRoyaltyPerCopy: string;
  cannibalizationDragPerMo: string;
  monthlyNetAfterDrag: string;
  royaltyBand: string;
  breakEvenUnitsPerMo: string;
  physicalVsDigitalRatio: string;
  digitalNetPerSale: string;
  digitalNetPerMonthNow: string;
  monthsOfPhysicalToMatch1DigitalMonth: string;
  cpmBenchmarkBand: string;
  fairFlatFeePerRead: string;
  cpmBreakEvenAudience: string;
  bestMonthlyNetAllLanes: string;
  currentMonthlyNet: string;
  candidateMonthlyNet: string;
  changeVsCurrent: string;
  currentImpliedUnits: string;
  candidateImpliedUnits: string;
  leftDigitMoves: string;
  recommendedEnding: string;
  highestShopAnchor: string;
  barrierBelow: string;
  barrierAbove: string;
  singlesNetAllComponents: string;
  bundleNet: string;
  bundleTotalEndsOdd: string;
  componentsEndEven: string;
  bestLaunchMonth: string;
  twelveMoRevenueBestWindow: string;
  promoAddsRevenue: string;
  asSoonAsReadyValue: string;
  mistimingCostBestVsWorst: string;
  launchWeekDiscountedNet: string;
  launchWeekFullPriceNet: string;
  peakDemandMultiplier: string;
  realisticNetCash: string;
  guestRateBenchmark: string;
  breakEvenTargetStudents: string;
  alumniConversionValue: string;
  breakEvenStudents: string;
  studentsToClearYourRate: string;
  realisticEffectiveRate: string;
  worstCaseEffectiveRate: string;
  travelShareOfRealisticTakeHome: string;
  realisticVsOpportunityCost: string;
  yourHourlyRate: string;
  patternPrice: string;
  freePoolNet: string;
  bestPaidModelNet: string;
  sizeCoverageFree: string;
  errorsCaught: string;
  yourTimeCost: string;
  paidSlots: string;
  baseWholesaleKeystoneFloor: string;
  netPerUnitBase: string;
  monthlyNetWholesale: string;
  breakEvenOrders: string;
  annualWholesaleNet: string;
  minimumOrderGate: string;
  reordersPerStockistYr: string;
  orderProcessingCost: string;
  unitsPerSkuPerOrder: string;
  knitHoursPerYearWholesale: string;
  faireStyleCommission: string;
  flatFeeReceived: string;
  royaltyStreamTermTotal: string;
  royaltyAfterRiskHaircut: string;
  totalOfferValue: string;
  exclusivityDragOwnShop: string;
  ownShopBaselineSameWindow: string;
  offerInYearsOfBaseline: string;
  minFlatToSayYes: string;
  minRoyaltyToSayYes: string;
  compensationModelComparison: string;
  watchOutFlags: string;
  verdict: string;
  tierTable: string;
  orderModels: string;
  compareAcrossWeights: string;
  yourLineWholesaleVsCogs: string;
  yesBestSellingConfig: string;
  noShiftTo99: string;
  yesPairedCorrectly: string;
  noEndComponents00: string;
  noDigitChange: string;
  noneSet: string;
  testerName: string;
  notesPerTester: string;
  partnerCompanyDyerShop: string;
  removePitch: string;
  dueDate: string;
  partnerNotesPlaceholder: string;
  affilPlaceholder: string;
  retreatTopicPlaceholder: string;
  testKnitRewardPlaceholder: string;
  patternNamePlaceholder: string;
  lunaWrapPlaceholder: string;
  copyText: string;
  addPartnerPattern: string;
  publishDesignPitchPlaceholder: string;
  publishPitchPlaceholder: string;
  measurementPlaceholder: string;
  notesPlaceholder: string;
  projectNotFound: string;
  returnToDashboard: string;
  recoveryImportTitle: string;
  recoveryImportDesc: string;
  recoveryImportButton: string;
  recoveryLocalOnlyTitle: string;
  recoveryLocalOnlyDesc: string;
  baseSize: string;
  gauge: string;
  infiniteValue: string;
  minimumList60Band: string;
  opportunityRate: string;
  cpmNetPerMonth: string;
  flatFeesNetPerMonth: string;
  affiliateNetPerMonth: string;
  bestLanePerHr: string;
  earliestLaunchThisMonth: string;
  designCategory: string;
  yourRole: string;
  effectivePerHrAllIn: string;
  hoursInvestedPrepClass: string;
  yarnGoodsPaidServices: string;
  netVsTimeAndDrag: string;
  priceSamplesPlaceholder: string;
  yourRoleAndTrip: string;
  yourClasses: string;
  classTitle: string;
  classTitleExample: string;
  addAnotherClass: string;
  guestTeacherAtRetreat: string;
  featuredTeacherOnCruise: string;
  hostingMyOwnRetreat: string;
  hostEconomics: string;
  compensationAndCompPackage: string;
  dealMathAndScenarioTable: string;
  slotsPerSize: string;
  yarnWeightAria: string;
  leadWeeks: string;
  ydPlaceholder: string;
  zeroPlaceholder: string;
  publishedPatternsPortfolio: string;
  amountDollars: string;
  firstOrderMinimumDollars: string;
  repeatMinimumDollars: string;
  clubTermsRetention: string;
  yourLineWholesaleVsCogsHeading: string;
  knitHoursSample: string;
  yarnAndMaterials: string;
  yourKnitHourlyRate: string;
  expectedMonth1PatternSales: string;
  customNewGarmentAskPrice: string;
  sampleSalePrice: string;
  boothCostFairs: string;
  daysAfterReleaseForSale: string;
  conversionRate: string;
  flatFeeOfferPays: string;
  exclusivityWindow: string;
  yarnSupportValue: string;
  royaltyShareBoxDeals: string;
  sampleCostYouFund: string;
  modelPhotographyYouFund: string;
  techEditingYouFund: string;
  ownStorePatternPrice: string;
  yourTotalHours: string;
  yourHourlyRateFloor: string;
  weeklyOwnStoreSalesCopies: string;
  members: string;
  downloadsPerMemberMo: string;
  ratePerPattern: string;
  buildCostToRecover: string;
  productionHoursTotal: string;
  patternHourlyRate: string;
  platformToolingPerMonth: string;
  materialsTravelOutOfPocket: string;
  hoursPerSession: string;
  refundRate: string;
  platformToolingCostLifetime: string;
  platformMembershipRevenueYr: string;
  yourMinutesShare: string;
  platformShareAfterCoupons: string;
  sampleKnitterRate: string;
  deadline: string;
  feedbackDue: string;
  yarnSupportUnpaid: string;
  patternPriceVideo: string;
  platformFee: string;
  monthlyPatternSales: string;
  emailSalesPerMonth: string;
  techEditCovered: string;
  photographyCovered: string;
  keepOwnSiteRights: string;
  earlyAccess: string;
  emailListSize: string;
  expectedMonthlyUnits: string;
  expectedStudentsZeroProject: string;
  expectedStudentsBuyers: string;
  extraPatternValue: string;
  freeFinalPattern: string;
  listConversion: string;
  minutesPerPost: string;
  paidSampleKnitters: string;
  patternLifetime: string;
  postsPerMonthAllPlatforms: string;
  royaltyPerDownload: string;
  royaltyRunwayMonths: string;
  seatsPerClassSlot: string;
  sessions: string;
  socialFeature: string;
  studentsCount: string;
  toolingRunwayMonths: string;
  videoLength: string;
  readinessLevel: string;
  earlyBirdPriceDollar: string;
  emailToOrder: string;
  waitlistToOrder: string;
  stitchRounding: string;
  rowRounding: string;
  handleNamePlaceholder: string;
  dollarPerYdPlaceholder: string;
  yarnDollarPlaceholder: string;
  platformAria: string;
  sampleCostRecoveryHeading: string;
  sampleSaleByChannelHeading: string;
  launchWindowHeading: string;
  garmentSeason: string;
  plannedReleaseMonth: string;
  bestNetBadge: string;
  sampleLaunchLabTitle: string;
  sampleAndLaunchLabDescription: string;
  weekOneSales: string;
  tailSales: string;
  weeklyValueAtPrice: string;
  thenTheTailTakesOver: string;
  launchBurstAtSeasonFactor: string;
  sampleNoChannels: string;
  channelNoteEtsy: string;
  channelNoteFlash: string;
  channelNoteConsignment: string;
  channelNoteFair: string;
  sampleVerdictRecovers: string;
  sampleVerdictPartial: string;
  keepVsSellNote: string;
  burstNoteOnPeak: string;
  burstNoteOffPeak: string;
  offPeakBurstLossBand: string;
  monthPctSuffix: string;
  channelEtsy: string;
  channelFlash: string;
  channelBoutique: string;
  channelCraftFair: string;
}

const en: LabStatCopy = {
  printingCostPerCopy: 'Printing cost / copy',
  netRoyaltyPerCopy: 'Net royalty / copy',
  cannibalizationDragPerMo: 'Cannibalization drag / mo',
  monthlyNetAfterDrag: 'Monthly net (after drag)',
  royaltyBand: 'Royalty band',
  breakEvenUnitsPerMo: 'Break-even units / mo',
  physicalVsDigitalRatio: 'Physical vs digital ratio',
  digitalNetPerSale: 'Digital net / sale',
  digitalNetPerMonthNow: 'Digital net / month now',
  monthsOfPhysicalToMatch1DigitalMonth: 'Months of physical to match 1 digital month',
  cpmBenchmarkBand: 'CPM benchmark band',
  fairFlatFeePerRead: 'Fair flat-fee equivalent per read',
  cpmBreakEvenAudience: 'CPM break-even audience',
  bestMonthlyNetAllLanes: 'Best monthly net (all lanes combined)',
  currentMonthlyNet: 'Current monthly net',
  candidateMonthlyNet: 'Candidate monthly net',
  changeVsCurrent: 'Change vs current',
  currentImpliedUnits: 'Current implied units',
  candidateImpliedUnits: 'Candidate implied units',
  leftDigitMoves: 'Left digit moves',
  recommendedEnding: 'Recommended ending',
  highestShopAnchor: 'Highest shop anchor',
  barrierBelow: 'Barrier below',
  barrierAbove: 'Barrier above',
  singlesNetAllComponents: 'Singles net (all components)',
  bundleNet: 'Bundle net',
  bundleTotalEndsOdd: 'Bundle total ends odd (.99)',
  componentsEndEven: 'Components end even (.00)',
  bestLaunchMonth: 'Best launch month',
  twelveMoRevenueBestWindow: '12-mo revenue at best window',
  promoAddsRevenue: 'Promo adds revenue?',
  asSoonAsReadyValue: 'As-soon-as-ready value',
  mistimingCostBestVsWorst: 'Mistiming cost (best vs worst ready)',
  launchWeekDiscountedNet: 'Launch-week discounted net',
  launchWeekFullPriceNet: 'Launch-week full-price net',
  peakDemandMultiplier: 'Peak demand multiplier',
  realisticNetCash: 'Realistic net cash',
  guestRateBenchmark: 'Guest rate benchmark',
  breakEvenTargetStudents: 'Break-even / target students',
  alumniConversionValue: 'Alumni conversion value',
  breakEvenStudents: 'Break-even students',
  studentsToClearYourRate: 'Students to clear your rate',
  realisticEffectiveRate: 'Realistic effective rate',
  worstCaseEffectiveRate: 'Worst-case effective rate',
  travelShareOfRealisticTakeHome: 'Travel share of realistic take-home',
  realisticVsOpportunityCost: 'Realistic vs opportunity cost',
  yourHourlyRate: 'Your hourly rate',
  patternPrice: 'Pattern price',
  freePoolNet: 'Free pool net',
  bestPaidModelNet: 'Best paid model net',
  sizeCoverageFree: 'Size coverage (free)',
  errorsCaught: 'Errors caught',
  yourTimeCost: 'Your time cost',
  paidSlots: 'Paid slots',
  baseWholesaleKeystoneFloor: 'Base wholesale (keystone floor)',
  netPerUnitBase: 'Net per unit (base)',
  monthlyNetWholesale: 'Monthly net (wholesale)',
  breakEvenOrders: 'Break-even orders',
  annualWholesaleNet: 'Annual wholesale net',
  minimumOrderGate: 'Minimum order gate',
  reordersPerStockistYr: 'Reorders per stockist / yr',
  orderProcessingCost: 'Order processing cost',
  unitsPerSkuPerOrder: 'Units per SKU per order',
  knitHoursPerYearWholesale: 'Knit hours / year to wholesale',
  faireStyleCommission: 'Faire-style commission',
  flatFeeReceived: 'Flat fee received',
  royaltyStreamTermTotal: 'Royalty stream (term total)',
  royaltyAfterRiskHaircut: 'Royalty after risk haircut',
  totalOfferValue: 'Total offer value',
  exclusivityDragOwnShop: 'Exclusivity drag (own shop)',
  ownShopBaselineSameWindow: 'Your own-shop baseline (same window)',
  offerInYearsOfBaseline: 'Offer in years of your baseline',
  minFlatToSayYes: 'Min flat to say yes',
  minRoyaltyToSayYes: 'Min royalty to say yes',
  compensationModelComparison: 'Compensation model comparison',
  watchOutFlags: 'Watch-out flags ({n})',
  verdict: 'Verdict',
  tierTable: 'Tier table',
  orderModels: 'Order models',
  compareAcrossWeights: 'Compare across weights',
  yourLineWholesaleVsCogs: 'Your line (wholesale prices vs COGS)',
  yesBestSellingConfig: 'Yes — best-selling config',
  noShiftTo99: 'No — shift to .99',
  yesPairedCorrectly: 'Yes — paired correctly',
  noEndComponents00: 'No — end components .00',
  noDigitChange: 'No digit change',
  noneSet: 'None set',
  testerName: 'Tester name',
  notesPerTester: 'Notes per tester',
  partnerCompanyDyerShop: 'Yarn company / dyer / shop',
  removePitch: 'Remove pitch',
  dueDate: 'Due date',
  partnerNotesPlaceholder: 'Notes — yarn received, deliverables owed, next deadline…',
  affilPlaceholder: 'e.g. LoveCrafts (15%)',
  retreatTopicPlaceholder: 'e.g. Seamless yoke construction',
  testKnitRewardPlaceholder: 'e.g. Plus a $10 gift card to my yarn sponsor',
  patternNamePlaceholder: 'e.g. Calyx Pullover',
  lunaWrapPlaceholder: 'e.g. Luna Wrap',
  copyText: 'Copy text',
  addPartnerPattern: 'Add partner pattern',
  publishDesignPitchPlaceholder: 'A relaxed crewneck worked flat and seamed, with drop shoulders and deep ribbing.',
  publishPitchPlaceholder: 'e.g. A modern take on the classic gansey',
  measurementPlaceholder: 'e.g. Back Width',
  notesPlaceholder: 'e.g. Worked flat, seamed at the side. Blocks generously — swatch and block before committing to a size.',
  projectNotFound: 'Project Not Found',
  returnToDashboard: 'Return to Dashboard',
  recoveryImportTitle: 'Shared this link?',
  recoveryImportDesc: 'This project might be on another device or browser. If you have a backup file (.json), you can import it now to continue.',
  recoveryImportButton: 'Import project from file',
  recoveryLocalOnlyTitle: 'Local-first Privacy',
  recoveryLocalOnlyDesc: 'Stitch & Scale stores your patterns locally. They don\'t sync automatically between devices unless you export and import them.',
  baseSize: 'Base Size',
  gauge: 'Gauge',
  infiniteValue: 'not reachable',
  minimumList60Band: 'Minimum list (60% band)',
  opportunityRate: 'Opportunity rate',
  cpmNetPerMonth: 'CPM — net / month',
  flatFeesNetPerMonth: 'Flat fees — net / month',
  affiliateNetPerMonth: 'Affiliate — net / month',
  bestLanePerHr: 'Best lane $/hr',
  earliestLaunchThisMonth: 'Earliest launch (this month)',
  designCategory: 'Design category',
  yourRole: 'Your role',
  effectivePerHrAllIn: 'Effective $/hr (all-in hours)',
  hoursInvestedPrepClass: 'Hours invested (prep + class)',
  yarnGoodsPaidServices: 'Yarn goods + paid services',
  netVsTimeAndDrag: 'Net vs your time + drag',
  priceSamplesPlaceholder: '5.00, 8.00, 14.00',
  yourRoleAndTrip: 'Your role & trip',
  yourClasses: 'Your classes',
  classTitle: 'Class title',
  classTitleExample: 'e.g. Seamless yoke sweater construction',
  addAnotherClass: 'Add another class',
  guestTeacherAtRetreat: 'Guest teacher at a retreat',
  featuredTeacherOnCruise: 'Featured teacher on a cruise',
  hostingMyOwnRetreat: 'Hosting my own retreat',
  hostEconomics: 'Host economics',
  compensationAndCompPackage: 'Compensation & comp package',
  dealMathAndScenarioTable: 'Deal math & scenario table',
  slotsPerSize: 'slots per size',
  yarnWeightAria: 'yarn weight',
  leadWeeks: 'lead weeks',
  ydPlaceholder: '— yd',
  zeroPlaceholder: '0',
  publishedPatternsPortfolio: 'Published patterns in portfolio',
  amountDollars: 'Amount ($)',
  firstOrderMinimumDollars: 'First-order minimum ($)',
  repeatMinimumDollars: 'Repeat minimum ($)',
  clubTermsRetention: 'Terms & retention',
  yourLineWholesaleVsCogsHeading: 'Your line (wholesale prices vs COGS)',
  knitHoursSample: 'Knit hours (sample)',
  yarnAndMaterials: 'Yarn & materials',
  yourKnitHourlyRate: 'Your knit hourly rate',
  expectedMonth1PatternSales: 'Expected month-1 pattern sales',
  customNewGarmentAskPrice: 'Custom/new garment ask price',
  sampleSalePrice: 'Sample-sale price',
  boothCostFairs: 'Booth cost (fairs)',
  daysAfterReleaseForSale: 'Days after release for sale',
  conversionRate: 'Conversion',
  flatFeeOfferPays: 'Flat fee the offer pays',
  exclusivityWindow: 'Exclusivity window',
  yarnSupportValue: 'Yarn support value',
  royaltyShareBoxDeals: 'Royalty share (box deals)',
  sampleCostYouFund: 'Sample cost (you fund)',
  modelPhotographyYouFund: 'Model / photography (you fund)',
  techEditingYouFund: 'Tech editing (you fund)',
  ownStorePatternPrice: 'Own-store pattern price',
  yourTotalHours: 'Your total hours',
  yourHourlyRateFloor: 'Your hourly rate (floor)',
  weeklyOwnStoreSalesCopies: 'Weekly own-store sales (copies)',
  members: 'Members',
  downloadsPerMemberMo: 'Downloads/member/mo',
  ratePerPattern: 'Rate per pattern',
  buildCostToRecover: 'Build cost to recover',
  productionHoursTotal: 'Production hours (total)',
  patternHourlyRate: 'Pattern hourly rate',
  platformToolingPerMonth: 'Platform/tooling / month',
  materialsTravelOutOfPocket: 'Materials / travel out-of-pocket',
  hoursPerSession: 'Hours per session',
  refundRate: 'Refund rate',
  platformToolingCostLifetime: 'Platform / tooling cost (lifetime)',
  platformMembershipRevenueYr: 'Platform membership revenue / yr',
  yourMinutesShare: 'Your minutes share (0.00013 ≈ $260/mo at an $8M pool)',
  platformShareAfterCoupons: 'Platform share (after coupons)',
  sampleKnitterRate: 'Sample-knitter rate',
  deadline: 'Deadline',
  feedbackDue: 'Feedback due',
  yarnSupportUnpaid: 'Yarn support / unpaid',
  patternPriceVideo: 'Pattern price',
  platformFee: 'Platform fee',
  monthlyPatternSales: 'Monthly pattern sales',
  emailSalesPerMonth: 'Email sales per month',
  techEditCovered: 'tech edit covered',
  photographyCovered: 'photography covered',
  keepOwnSiteRights: 'keep own-site rights',
  earlyAccess: 'Early access',
  emailListSize: 'Email list size',
  expectedMonthlyUnits: 'Expected monthly units',
  expectedStudentsZeroProject: 'Expected students (0 = project from list)',
  expectedStudentsBuyers: 'Expected students / buyers',
  extraPatternValue: 'Extra pattern value',
  freeFinalPattern: 'Free final pattern',
  listConversion: 'List conversion',
  minutesPerPost: 'Minutes per post',
  paidSampleKnitters: 'Paid sample knitters',
  patternLifetime: 'Pattern lifetime',
  postsPerMonthAllPlatforms: 'Posts per month (all platforms)',
  royaltyPerDownload: 'Royalty per download',
  royaltyRunwayMonths: 'Royalty runway (months)',
  seatsPerClassSlot: 'Seats per class slot',
  sessions: 'Sessions',
  socialFeature: 'Social feature',
  studentsCount: 'Students',
  toolingRunwayMonths: 'Tooling runway (months)',
  videoLength: 'Video length',
  readinessLevel: 'readiness',
  earlyBirdPriceDollar: 'Early-bird price ($)',
  emailToOrder: 'Email → order',
  waitlistToOrder: 'Waitlist → order',
  stitchRounding: 'Stitch Rounding',
  rowRounding: 'Row Rounding',
  handleNamePlaceholder: 'handle / name',
  dollarPerYdPlaceholder: '$/yd',
  yarnDollarPlaceholder: 'yarn $',
  platformAria: 'platform',
  sampleCostRecoveryHeading: 'The sample — what did it cost, what can it recover?',
  sampleSaleByChannelHeading: 'Sample sale by channel — nets compared against the cost basis',
  launchWindowHeading: 'The launch window — week-one burst vs the tail',
  garmentSeason: 'Garment season',
  plannedReleaseMonth: 'Planned release month',
  bestNetBadge: 'Best net',
  sampleLaunchLabTitle: 'Sample & Launch Window Lab',
  sampleAndLaunchLabDescription: 'No tool prices the sample garment or the launch-week burst — Ravelry treats a sample as a sunk cost and launch tools stop at "post consistently". A sweater sample is the largest single cost block of a pattern (≈30 knit hours + $75 yarn ≈ $525 at a $15/hr basis), and a well-timed launch caught Hot Right Now and sold 76 copies in under 5 days against 109 in a whole month for the designer’s previous best. This lab prices the sample across four sale channels and prices the launch week before the tail.',
  weekOneSales: 'Week-one sales',
  tailSales: 'Tail sales',
  weeklyValueAtPrice: 'Weekly value at {price}',
  thenTheTailTakesOver: 'Then the tail takes over — sales decline through the month.',
  launchBurstAtSeasonFactor: 'Launch burst at season factor {factor}',
  sampleNoChannels: 'No channels available.',
  channelNoteEtsy: 'Etsy transaction + listing fees apply to physical knitwear too; the sample is one listing.',
  channelNoteFlash: 'Westknits-style flash drops: ~10% platform cut; demand concentrates into the drop window, samples clear fast at a discount.',
  channelNoteConsignment: 'Boutique consignment typically takes 40% (30–50% band) — no unsold risk and no selling effort, but the deepest cut.',
  channelNoteFair: 'Booth cost ${cost} amortized across samples sold at the fair + ~2% card-processing fee.',
  sampleVerdictRecovers: 'At {channel} the sample nets {net} against a {basis} cost basis — it recovers {pct}% of its own production cost.',
  sampleVerdictPartial: 'Even the best channel nets {net} against a {basis} basis — the sample sale only partially recovers cost; pair it with the launch burst (see week-one math) to close the gap.',
  keepVsSellNote: 'Keeping the sample as a portfolio/marketing asset has its own value (photos, classes, trunk shows). If the sample nets more than its basis here, selling it is pure recovery; if it nets less, it stays a marketing asset until a flash drop clears it.',
  monthPctSuffix: '% of month',
  channelEtsy: 'Etsy listing',
  channelFlash: 'Flash online drop (Westknits-style)',
  channelBoutique: 'Boutique consignment',
  channelCraftFair: 'Craft fair / market',
  burstNoteOnPeak: 'Launch month lands inside the season peak for this garment type — documented launches timed this way catch Ravelry Hot Right Now and pull most of the month’s sales into the first week.',
  burstNoteOffPeak: 'Launch month is off the peak for {season} designs — the burst typically loses ~15–35% of its force (Diego sold 76 copies in under 5 days when timed right; a whole month took the designer’s previous best 109).',
  offPeakBurstLossBand: '~15–35% of its force',
};

const de: LabStatCopy = {
  printingCostPerCopy: 'Druckkosten / Exemplar',
  netRoyaltyPerCopy: 'Nettolizenzgebühr / Exemplar',
  cannibalizationDragPerMo: 'Kannibalisierungsverlust / Monat',
  monthlyNetAfterDrag: 'Monatsnetto (nach Erosion)',
  royaltyBand: 'Lizenzband',
  breakEvenUnitsPerMo: 'Break-even-Einheiten / Monat',
  physicalVsDigitalRatio: 'Verhältnis physisch zu digital',
  digitalNetPerSale: 'Digital-Netto / Verkauf',
  digitalNetPerMonthNow: 'Digital-Netto / aktueller Monat',
  monthsOfPhysicalToMatch1DigitalMonth: 'Physische Monate für einen digitalen Monat',
  cpmBenchmarkBand: 'CPM-Benchmark-Band',
  fairFlatFeePerRead: 'Fair-Pauschale pro Erwähnung',
  cpmBreakEvenAudience: 'CPM-Break-even-Zuhörerschaft',
  bestMonthlyNetAllLanes: 'Bestes Monatsnetto (alle Kanäle)',
  currentMonthlyNet: 'Aktuelles Monatsnetto',
  candidateMonthlyNet: 'Kandidaten-Monatsnetto',
  changeVsCurrent: 'Änderung ggü. aktuell',
  currentImpliedUnits: 'Aktuelle implizite Einheiten',
  candidateImpliedUnits: 'Kandidaten-implizite Einheiten',
  leftDigitMoves: 'Verschiebung der ersten Ziffer',
  recommendedEnding: 'Empfohlenes Preisende',
  highestShopAnchor: 'Höchster Shop-Anker',
  barrierBelow: 'Preisbarriere darunter',
  barrierAbove: 'Preisbarriere darüber',
  singlesNetAllComponents: 'Einzelnetto (alle Komponenten)',
  bundleNet: 'Bündelnetto',
  bundleTotalEndsOdd: 'Bündelgesamtsumme endet ungerade (.99)',
  componentsEndEven: 'Komponenten enden gerade (.00)',
  bestLaunchMonth: 'Bester Launchmonat',
  twelveMoRevenueBestWindow: '12-Monats-Umsatz im besten Fenster',
  promoAddsRevenue: 'Steigert die Promo den Umsatz?',
  asSoonAsReadyValue: 'Wert bei Sofort-Release',
  mistimingCostBestVsWorst: 'Fehltiming-Kosten (bestes vs. schlechtestes Timing)',
  launchWeekDiscountedNet: 'Launchwoche-Aktionsnetto',
  launchWeekFullPriceNet: 'Launchwoche-Netto zum Vollpreis',
  peakDemandMultiplier: 'Nachfragespitzen-Multiplikator',
  realisticNetCash: 'Realistisches Nettobargeld',
  guestRateBenchmark: 'Benchmark-Gasthonorar',
  breakEvenTargetStudents: 'Break-even / Zielteilnehmer',
  alumniConversionValue: 'Alumni-Konversionswert',
  breakEvenStudents: 'Break-even-Teilnehmer',
  studentsToClearYourRate: 'Teilnehmer für deinen Stundensatz',
  realisticEffectiveRate: 'Realistischer effektiver Stundensatz',
  worstCaseEffectiveRate: 'Worst-Case-effektiver Stundensatz',
  travelShareOfRealisticTakeHome: 'Reiseanteil am realistischen Netto',
  realisticVsOpportunityCost: 'Realistisch vs. Opportunitätskosten',
  yourHourlyRate: 'Dein Stundensatz',
  patternPrice: 'Schnittmuster-Preis',
  freePoolNet: 'Gratis-Pool-Netto',
  bestPaidModelNet: 'Bestes Paid-Modell-Netto',
  sizeCoverageFree: 'Größenspreizung (gratis)',
  errorsCaught: 'Gefundene Fehler',
  yourTimeCost: 'Deine Zeitkosten',
  paidSlots: 'Bezahlte Testplätze',
  baseWholesaleKeystoneFloor: 'Basis-Großhandel (Keystone-Untergrenze)',
  netPerUnitBase: 'Netto pro Einheit (Basis)',
  monthlyNetWholesale: 'Monatsnetto (Großhandel)',
  breakEvenOrders: 'Break-even-Bestellungen',
  annualWholesaleNet: 'Jahresnetto Großhandel',
  minimumOrderGate: 'Mindestbestellgrenze',
  reordersPerStockistYr: 'Nachbestellungen pro Händler / Jahr',
  orderProcessingCost: 'Bearbeitungskosten pro Bestellung',
  unitsPerSkuPerOrder: 'Einheiten pro SKU pro Bestellung',
  knitHoursPerYearWholesale: 'Strickstunden / Jahr für Großhandel',
  faireStyleCommission: 'Faire-artige Provision',
  flatFeeReceived: 'Erhaltene Pauschale',
  royaltyStreamTermTotal: 'Royalty-Stream (Gesamtlaufzeit)',
  royaltyAfterRiskHaircut: 'Royalty nach Risikoabschlag',
  totalOfferValue: 'Gesamtwert des Angebots',
  exclusivityDragOwnShop: 'Exklusivitätsverlust (eigener Shop)',
  ownShopBaselineSameWindow: 'Deine Shop-Basislinie (gleiches Zeitfenster)',
  offerInYearsOfBaseline: 'Angebot in Jahren deiner Basislinie',
  minFlatToSayYes: 'Mindestpauschale für ein Ja',
  minRoyaltyToSayYes: 'Mindestroyalty für ein Ja',
  compensationModelComparison: 'Vergleich der Vergütungsmodelle',
  watchOutFlags: 'Warnhinweise ({n})',
  verdict: 'Urteil',
  tierTable: 'Stufentabelle',
  orderModels: 'Bestellmodelle',
  compareAcrossWeights: 'Über Garnstärken vergleichen',
  yourLineWholesaleVsCogs: 'Deine Linie (Großhandelspreise vs. Herstellkosten)',
  yesBestSellingConfig: 'Ja — meistverkaufte Konfiguration',
  noShiftTo99: 'Nein — auf .99 umstellen',
  yesPairedCorrectly: 'Ja — richtig kombiniert',
  noEndComponents00: 'Nein — Komponenten auf .00 enden lassen',
  noDigitChange: 'Keine Ziffernverschiebung',
  noneSet: 'Keine gesetzt',
  testerName: 'Tester-Name',
  notesPerTester: 'Notizen pro Tester',
  partnerCompanyDyerShop: 'Garnfirma / Färber / Shop',
  removePitch: 'Angebot entfernen',
  dueDate: 'Fälligkeitsdatum',
  partnerNotesPlaceholder: 'Notizen — Garn erhalten, fällige Leistungen, nächste Deadline …',
  affilPlaceholder: 'z. B. LoveCrafts (15 %)',
  retreatTopicPlaceholder: 'z. B. nahtlose Passe-Konstruktion',
  testKnitRewardPlaceholder: 'z. B. plus eine 10-$-Geschenkkarte für meine Garn-Sponsoren',
  patternNamePlaceholder: 'z. B. Calyx Pullover',
  lunaWrapPlaceholder: 'z. B. Luna Wrap',
  copyText: 'Text kopieren',
  addPartnerPattern: 'Partner-Schnittmuster hinzufügen',
  publishDesignPitchPlaceholder: 'Ein entspannter Rundhals, flach gestrickt und genäht, mit Fallschultern und tiefem Bündchen.',
  publishPitchPlaceholder: 'z. B. Eine moderne Interpretation des klassischen Gansey',
  measurementPlaceholder: 'z. B. Rückenbreite',
  notesPlaceholder: 'z. B. Flach gestrickt, seitlich genäht. Lässt sich großzügig blocken — vor der Größenwahl maschenproben und blocken.',
  projectNotFound: 'Projekt nicht gefunden',
  returnToDashboard: 'Zum Dashboard zurück',
  recoveryImportTitle: 'Diesen Link geteilt?',
  recoveryImportDesc: 'Dieses Projekt befindet sich möglicherweise auf einem anderen Gerät oder Browser. Wenn du eine Backup-Datei (.json) hast, kannst du sie jetzt importieren, um fortzufahren.',
  recoveryImportButton: 'Projekt aus Datei importieren',
  recoveryLocalOnlyTitle: 'Lokale Privatsphäre',
  recoveryLocalOnlyDesc: 'Stitch & Scale speichert deine Muster lokal. Sie werden nicht automatisch zwischen Geräten synchronisiert, es sei denn, du exportierst und importierst sie.',
  baseSize: 'Basisgröße',
  gauge: 'Maschenprobe',
  infiniteValue: 'unerreichbar',
  minimumList60Band: 'Mindestliste (60-%-Band)',
  opportunityRate: 'Opportunitätsrate',
  cpmNetPerMonth: 'CPM — Netto / Monat',
  flatFeesNetPerMonth: 'Pauschalen — Netto / Monat',
  affiliateNetPerMonth: 'Affiliate — Netto / Monat',
  bestLanePerHr: 'Bester Kanal $/Std.',
  earliestLaunchThisMonth: 'Frühestmöglicher Start (dieser Monat)',
  designCategory: 'Design-Kategorie',
  yourRole: 'Deine Rolle',
  effectivePerHrAllIn: 'Effektiver $/Std. (Gesamtstunden)',
  hoursInvestedPrepClass: 'Investierte Stunden (Vorbereitung + Kurs)',
  yarnGoodsPaidServices: 'Garnwaren + bezahlte Services',
  netVsTimeAndDrag: 'Netto vs. deine Zeit + Verlust',
  priceSamplesPlaceholder: '5,00, 8,00, 14,00',
  yourRoleAndTrip: 'Deine Rolle & Reise',
  yourClasses: 'Deine Kurse',
  classTitle: 'Kurstitel',
  classTitleExample: 'z. B. nahtlose Passe-Konstruktion',
  addAnotherClass: 'Weiteren Kurs hinzufügen',
  guestTeacherAtRetreat: 'Gastlehrer an einem Retreat',
  featuredTeacherOnCruise: 'Hauptlehrer auf einer Kreuzfahrt',
  hostingMyOwnRetreat: 'Eigenes Retreat ausrichten',
  hostEconomics: 'Host-Ökonomie',
  compensationAndCompPackage: 'Vergütung & Komp-Paket',
  dealMathAndScenarioTable: 'Deal-Rechnung & Szenariotabelle',
  slotsPerSize: 'Plätze pro Größe',
  yarnWeightAria: 'Garnstärke',
  leadWeeks: 'Vorlaufwochen',
  ydPlaceholder: '— yd',
  zeroPlaceholder: '0',
  publishedPatternsPortfolio: 'Veröffentlichte Muster im Portfolio',
  amountDollars: 'Betrag ($)',
  firstOrderMinimumDollars: 'Erstbestellminimum ($)',
  repeatMinimumDollars: 'Nachbestellminimum ($)',
  clubTermsRetention: 'Konditionen & Bindung',
  yourLineWholesaleVsCogsHeading: 'Deine Linie (Großhandelspreise vs. Herstellkosten)',
  knitHoursSample: 'Strickstunden (Sample)',
  yarnAndMaterials: 'Garn & Material',
  yourKnitHourlyRate: 'Dein Strick-Stundensatz',
  expectedMonth1PatternSales: 'Erwartete Muster-Verkäufe Monat 1',
  customNewGarmentAskPrice: 'Preis für Sonderanfertigung/neues Kleidungsstück',
  sampleSalePrice: 'Sample-Sale-Preis',
  boothCostFairs: 'Standkosten (Messen)',
  daysAfterReleaseForSale: 'Tage nach Release für den Sale',
  conversionRate: 'Konversionsrate',
  flatFeeOfferPays: 'Pauschale des Angebots',
  exclusivityWindow: 'Exklusivitätsfenster',
  yarnSupportValue: 'Garn-Support-Wert',
  royaltyShareBoxDeals: 'Royalty-Anteil (Box-Deals)',
  sampleCostYouFund: 'Sample-Kosten (du trägst)',
  modelPhotographyYouFund: 'Model / Fotografie (du trägst)',
  techEditingYouFund: 'Tech Editing (du trägst)',
  ownStorePatternPrice: 'Muster-Preis im eigenen Shop',
  yourTotalHours: 'Deine Gesamtstunden',
  yourHourlyRateFloor: 'Dein Stundensatz (Untergrenze)',
  weeklyOwnStoreSalesCopies: 'Wöchentliche Shop-Verkäufe (Kopien)',
  members: 'Mitglieder',
  downloadsPerMemberMo: 'Downloads/Mitglied/Monat',
  ratePerPattern: 'Vergütung pro Muster',
  buildCostToRecover: 'Zu deckende Entwicklungskosten',
  productionHoursTotal: 'Produktionsstunden (gesamt)',
  patternHourlyRate: 'Stundensatz fürs Muster',
  platformToolingPerMonth: 'Plattform/Tooling / Monat',
  materialsTravelOutOfPocket: 'Material / Reisen (selbst gezahlt)',
  hoursPerSession: 'Stunden pro Session',
  refundRate: 'Rückerstattungsrate',
  platformToolingCostLifetime: 'Plattform-/Tooling-Kosten (gesamt)',
  platformMembershipRevenueYr: 'Plattform-Mitglieds-Umsatz / Jahr',
  yourMinutesShare: 'Dein Minutenanteil (0,00013 ≈ 260 $/Monat bei 8-Mio-$-Pool)',
  platformShareAfterCoupons: 'Plattform-Anteil (nach Coupons)',
  sampleKnitterRate: 'Sample-Stricker-Tarif',
  deadline: 'Deadline',
  feedbackDue: 'Feedback fällig',
  yarnSupportUnpaid: 'Garn-Support / unbezahlt',
  patternPriceVideo: 'Muster-Preis',
  platformFee: 'Plattformgebühr',
  monthlyPatternSales: 'Monatliche Muster-Verkäufe',
  emailSalesPerMonth: 'E-Mail-Verkäufe / Monat',
  techEditCovered: 'Tech Editing abgedeckt',
  photographyCovered: 'Fotografie abgedeckt',
  keepOwnSiteRights: 'eigene Website-Rechte behalten',
  earlyAccess: 'Frühzugang',
  emailListSize: 'E-Mail-Listen-Größe',
  expectedMonthlyUnits: 'Erwartete monatliche Einheiten',
  expectedStudentsZeroProject: 'Erwartete Teilnehmer (0 = Projekt aus Liste)',
  expectedStudentsBuyers: 'Erwartete Teilnehmer / Käufer',
  extraPatternValue: 'Zusätzlicher Muster-Wert',
  freeFinalPattern: 'Finales Muster gratis',
  listConversion: 'Listen-Konversion',
  minutesPerPost: 'Minuten pro Post',
  paidSampleKnitters: 'Bezahlte Sample-Stricker',
  patternLifetime: 'Muster-Lebensdauer',
  postsPerMonthAllPlatforms: 'Posts / Monat (alle Plattformen)',
  royaltyPerDownload: 'Royalty pro Download',
  royaltyRunwayMonths: 'Royalty-Reserve (Monate)',
  seatsPerClassSlot: 'Plätze pro Kurs-Slot',
  sessions: 'Sessions',
  socialFeature: 'Social-Feature',
  studentsCount: 'Teilnehmer',
  toolingRunwayMonths: 'Tooling-Reserve (Monate)',
  videoLength: 'Videolänge',
  readinessLevel: 'Reifegrad',
  earlyBirdPriceDollar: 'Frühbucher-Preis ($)',
  emailToOrder: 'E-Mail → Bestellung',
  waitlistToOrder: 'Warteliste → Bestellung',
  stitchRounding: 'Maschen-Rundung',
  rowRounding: 'Reihen-Rundung',
  handleNamePlaceholder: 'Handle / Name',
  dollarPerYdPlaceholder: '$/yd',
  yarnDollarPlaceholder: 'Garn $',
  platformAria: 'Plattform',
  sampleCostRecoveryHeading: 'Das Sample — was hat es gekostet, was bringt es zurück?',
  sampleSaleByChannelHeading: 'Sample-Verkauf pro Kanal — Netto gegen die Kostenbasis',
  launchWindowHeading: 'Das Launch-Fenster — Woche-1-Boom vs. der Abfall',
  garmentSeason: 'Kleidungsstück-Saison',
  plannedReleaseMonth: 'Geplanter Release-Monat',
  bestNetBadge: 'Bester Netto-Erlös',
  sampleLaunchLabTitle: 'Sample- & Launch-Fenster-Labor',
  sampleAndLaunchLabDescription: 'Kein Tool bepreist das Sample-Kleidungsstück oder die Launch-Woche — Ravelry behandelt Samples als versunkene Kosten und Launch-Tools hören bei „konsistent posten" auf. Ein Pullover-Sample ist der größte einzelne Kostenblock eines Musters (≈30 Strickstunden + 75 $ Garn ≈ 525 $ bei 15 $/h), und ein gut getimter Launch hat Hot Right Now erwischt und 76 Kopien in unter 5 Tagen verkauft — gegen 109 in einem ganzen Monat zuvor. Dieses Labor bepreist das Sample über vier Verkaufskanäle und die Launch-Woche vor dem Abfall.',
  weekOneSales: 'Verkäufe Woche 1',
  tailSales: 'Abfall-Verkäufe',
  weeklyValueAtPrice: 'Wochenwert bei {price}',
  thenTheTailTakesOver: 'Dann übernimmt der Abfall — die Verkäufe sinken durch den Monat.',
  launchBurstAtSeasonFactor: 'Launch-Boom bei Saison-Faktor {factor}',
  sampleNoChannels: 'Keine Kanäle verfügbar.',
  channelNoteEtsy: 'Etsy-Transaktions- und Insertionsgebühren gelten auch für physische Strickware; das Sample ist ein Listing.',
  channelNoteFlash: 'Flash-Drops im Westknits-Stil: ~10 % Plattformanteil; die Nachfrage konzentriert sich aufs Drop-Fenster, Samples verkaufen sich mit Rabatt schnell.',
  channelNoteConsignment: 'Boutique-Kommission nimmt typisch 40 % (30–50 % Band) — kein Unverkauftsrisiko, kein Verkaufsaufwand, aber der tiefste Anteil.',
  channelNoteFair: 'Standkosten {cost} $ auf die auf der Messe verkauften Samples verteilt + ~2 % Kartengebühr.',
  sampleVerdictRecovers: 'Bei {channel} macht das Sample {net} netto gegen eine Kostenbasis von {basis} — es deckt {pct} % seiner eigenen Herstellungskosten.',
  sampleVerdictPartial: 'Selbst der beste Kanal macht nur {net} netto gegen eine Basis von {basis} — der Sample-Verkauf deckt nur einen Teil der Kosten; kombiniere ihn mit dem Launch-Boom (siehe Woche-1-Rechnung), um die Lücke zu schließen.',
  keepVsSellNote: 'Das Sample als Portfolio-/Marketing-Asset zu behalten hat eigenen Wert (Fotos, Kurse, Trunk Shows). Wenn es hier mehr netto macht als seine Basis, ist der Verkauf reine Kostenrückholung; wenn weniger, bleibt es Marketing-Asset, bis ein Flash Drop es verkauft.',
  burstNoteOnPeak: 'Der Release-Monat liegt in der Saisonspitze für diesen Kleidungsstyp — dokumentierte Launches mit diesem Timing erwischen Ravelry „Hot Right Now" und ziehen den Großteil der Monatsverkäufe in die erste Woche.',
  burstNoteOffPeak: 'Der Release-Monat liegt außerhalb der Spitze für {season}-Designs — der Boom verliert typisch ~15–35 % seiner Kraft (Diego verkaufte gut getimt 76 Kopien in unter 5 Tagen; ein ganzer Monat brachte dem Designer zuvor 109 im besten Monat).',
  monthPctSuffix: '% des Monats',
  channelEtsy: 'Etsy-Listing',
  channelFlash: 'Online-Flash-Drop (Westknits-Stil)',
  channelBoutique: 'Boutique-Kommission',
  channelCraftFair: 'Messe / Markt',
  offPeakBurstLossBand: '~15–35 % seiner Kraft',
};

const fr: LabStatCopy = {
  printingCostPerCopy: 'Coût d\'impression / exemplaire',
  netRoyaltyPerCopy: 'Redevance nette / exemplaire',
  cannibalizationDragPerMo: 'Érosion par cannibalisation / mois',
  monthlyNetAfterDrag: 'Net mensuel (après érosion)',
  royaltyBand: 'Fourchette de redevance',
  breakEvenUnitsPerMo: 'Unités au seuil de rentabilité / mois',
  physicalVsDigitalRatio: 'Ratio physique vs numérique',
  digitalNetPerSale: 'Net numérique / vente',
  digitalNetPerMonthNow: 'Net numérique / mois actuel',
  monthsOfPhysicalToMatch1DigitalMonth: 'Mois de physique pour égaler un mois numérique',
  cpmBenchmarkBand: 'Fourchette de référence CPM',
  fairFlatFeePerRead: 'Équivalent forfait juste par mention',
  cpmBreakEvenAudience: 'Audience de seuil CPM',
  bestMonthlyNetAllLanes: 'Meilleur net mensuel (toutes voies)',
  currentMonthlyNet: 'Net mensuel actuel',
  candidateMonthlyNet: 'Net mensuel candidat',
  changeVsCurrent: 'Variation vs actuel',
  currentImpliedUnits: 'Unités implicites actuelles',
  candidateImpliedUnits: 'Unités implicites candidates',
  leftDigitMoves: 'Mouvement du chiffre de gauche',
  recommendedEnding: 'Fin de prix recommandé',
  highestShopAnchor: 'Ancrage le plus élevé',
  barrierBelow: 'Barrière inférieure',
  barrierAbove: 'Barrière supérieure',
  singlesNetAllComponents: 'Net en unité (toutes pièces)',
  bundleNet: 'Net du bundle',
  bundleTotalEndsOdd: 'Total du bundle se terminant par un chiffre impair (.99)',
  componentsEndEven: 'Pièces se terminant par .00',
  bestLaunchMonth: 'Meilleur mois de lancement',
  twelveMoRevenueBestWindow: 'Revenu sur 12 mois au meilleur créneau',
  promoAddsRevenue: 'La promo augmente-t-elle le revenu ?',
  asSoonAsReadyValue: 'Valeur "dès que prêt"',
  mistimingCostBestVsWorst: 'Coût d\'un mauvais timing (meilleur vs pire)',
  launchWeekDiscountedNet: 'Net promo de la semaine de lancement',
  launchWeekFullPriceNet: 'Net plein tarif de la semaine de lancement',
  peakDemandMultiplier: 'Multiplicateur de demande de pointe',
  realisticNetCash: 'Net trésorerie réaliste',
  guestRateBenchmark: 'Référence de tarif invité',
  breakEvenTargetStudents: 'Seuil / étudiants cibles',
  alumniConversionValue: 'Valeur de conversion alumni',
  breakEvenStudents: 'Étudiants au seuil de rentabilité',
  studentsToClearYourRate: 'Étudiants pour couvrir ton tarif',
  realisticEffectiveRate: 'Taux horaire effectif réaliste',
  worstCaseEffectiveRate: 'Taux horaire effectif au pire cas',
  travelShareOfRealisticTakeHome: 'Part des frais de voyage dans le net réaliste',
  realisticVsOpportunityCost: 'Réaliste vs coût d\'opportunité',
  yourHourlyRate: 'Ton taux horaire',
  patternPrice: 'Prix du patron',
  freePoolNet: 'Net du pool gratuit',
  bestPaidModelNet: 'Net du meilleur modèle payant',
  sizeCoverageFree: 'Couverture de tailles (gratuit)',
  errorsCaught: 'Erreurs détectées',
  yourTimeCost: 'Coût de ton temps',
  paidSlots: 'Places payées',
  baseWholesaleKeystoneFloor: 'Gros de base (plancher keystone)',
  netPerUnitBase: 'Net par unité (base)',
  monthlyNetWholesale: 'Net mensuel (gros)',
  breakEvenOrders: 'Commandes de seuil de rentabilité',
  annualWholesaleNet: 'Net annuel gros',
  minimumOrderGate: 'Portail de commande minimale',
  reordersPerStockistYr: 'Recommandes par revendeur / an',
  orderProcessingCost: 'Coût de traitement de commande',
  unitsPerSkuPerOrder: 'Unités par référence par commande',
  knitHoursPerYearWholesale: 'Heures de tricot / an pour le gros',
  faireStyleCommission: 'Commission style Faire',
  flatFeeReceived: 'Forfait reçu',
  royaltyStreamTermTotal: 'Flux de redevances (durée totale)',
  royaltyAfterRiskHaircut: 'Redevance après réduction de risque',
  totalOfferValue: 'Valeur totale de l\'offre',
  exclusivityDragOwnShop: 'Érosion d\'exclusivité (boutique propre)',
  ownShopBaselineSameWindow: 'Base de ta boutique (même fenêtre)',
  offerInYearsOfBaseline: 'Offre en années de ta base',
  minFlatToSayYes: 'Forfait minimum pour accepter',
  minRoyaltyToSayYes: 'Redevance minimale pour accepter',
  compensationModelComparison: 'Comparaison des modèles de rémunération',
  watchOutFlags: 'Drapeaux d\'attention ({n})',
  verdict: 'Verdict',
  tierTable: 'Tableau des paliers',
  orderModels: 'Modèles de commande',
  compareAcrossWeights: 'Comparer entre épaisseurs',
  yourLineWholesaleVsCogs: 'Ta ligne (prix gros vs coût de revient)',
  yesBestSellingConfig: 'Oui — config la plus vendue',
  noShiftTo99: 'Non — passer à .99',
  yesPairedCorrectly: 'Oui — bien assorties',
  noEndComponents00: 'Non — terminer les pièces en .00',
  noDigitChange: 'Pas de changement de chiffre',
  noneSet: 'Aucun défini',
  testerName: 'Nom du testeur',
  notesPerTester: 'Notes par testeur',
  partnerCompanyDyerShop: 'Société de laine / teinturier / boutique',
  removePitch: 'Retirer la proposition',
  dueDate: 'Date d\'échéance',
  partnerNotesPlaceholder: 'Notes — laine reçue, livrables dus, prochaine échéance…',
  affilPlaceholder: 'p. ex. LoveCrafts (15 %)',
  retreatTopicPlaceholder: 'p. ex. construction de yoke sans couture',
  testKnitRewardPlaceholder: 'p. ex. plus une carte-cadeau de 10 $ pour mon sponsor de laine',
  patternNamePlaceholder: 'p. ex. Pull Calyx',
  lunaWrapPlaceholder: 'p. ex. Châle Luna',
  copyText: 'Copier le texte',
  addPartnerPattern: 'Ajouter un patron partenaire',
  publishDesignPitchPlaceholder: 'Un col rond décontracté tricoté à plat et cousu, avec épaules tombantes et côtes profondes.',
  publishPitchPlaceholder: 'p. ex. Une version moderne du gansey classique',
  measurementPlaceholder: 'p. ex. Largeur du dos',
  notesPlaceholder: 'p. ex. Tricoté à plat, cousu sur le côté. Se bloque généreusement — fais un échantillon et bloque avant de choisir la taille.',
  projectNotFound: 'Projet introuvable',
  returnToDashboard: 'Retour au tableau de bord',
  recoveryImportTitle: 'Lien partagé ?',
  recoveryImportDesc: 'Ce projet se trouve peut-être sur un autre appareil ou navigateur. Si vous avez un fichier de sauvegarde (.json), vous pouvez l\'importer maintenant pour continuer.',
  recoveryImportButton: 'Importer le projet depuis un fichier',
  recoveryLocalOnlyTitle: 'Confidentialité locale',
  recoveryLocalOnlyDesc: 'Stitch & Scale stocke vos modèles localement. Ils ne se synchronisent pas automatiquement entre les appareils, sauf si vous les exportez et les importez.',
  baseSize: 'Taille de base',
  gauge: 'Échantillon',
  infiniteValue: 'inatteignable',
  minimumList60Band: 'Liste minimale (bande 60 %)',
  opportunityRate: 'Taux d’opportunité',
  cpmNetPerMonth: 'CPM — net / mois',
  flatFeesNetPerMonth: 'Forfaits — net / mois',
  affiliateNetPerMonth: 'Affiliation — net / mois',
  bestLanePerHr: 'Meilleure voie $/h',
  earliestLaunchThisMonth: 'Lancement le plus précoce (ce mois)',
  designCategory: 'Catégorie de design',
  yourRole: 'Ton rôle',
  effectivePerHrAllIn: '$/h effectif (heures totales)',
  hoursInvestedPrepClass: 'Heures investies (prépa + cours)',
  yarnGoodsPaidServices: 'Biens de laine + services payés',
  netVsTimeAndDrag: 'Net vs ton temps + érosion',
  priceSamplesPlaceholder: '5,00, 8,00, 14,00',
  yourRoleAndTrip: 'Ton rôle et voyage',
  yourClasses: 'Tes cours',
  classTitle: 'Titre du cours',
  classTitleExample: 'p. ex. construction de yoke sans couture',
  addAnotherClass: 'Ajouter un autre cours',
  guestTeacherAtRetreat: 'Professeur invité à un stage',
  featuredTeacherOnCruise: 'Professeur vedette sur une croisière',
  hostingMyOwnRetreat: 'Organiser mon propre stage',
  hostEconomics: 'Économie d’hôte',
  compensationAndCompPackage: 'Rémunération et prestations offertes',
  dealMathAndScenarioTable: 'Calcul du deal et tableau de scénarios',
  slotsPerSize: 'places par taille',
  yarnWeightAria: 'épaisseur de laine',
  leadWeeks: 'semaines de délai',
  ydPlaceholder: '— yd',
  zeroPlaceholder: '0',
  publishedPatternsPortfolio: 'Patrons publiés dans le portfolio',
  amountDollars: 'Montant ($)',
  firstOrderMinimumDollars: 'Minimum de première commande ($)',
  repeatMinimumDollars: 'Minimum de recommande ($)',
  clubTermsRetention: 'Conditions & rétention',
  yourLineWholesaleVsCogsHeading: 'Ta ligne (prix gros vs coût de revient)',
  knitHoursSample: 'Heures de tricot (échantillon)',
  yarnAndMaterials: 'Laine et matériel',
  yourKnitHourlyRate: 'Ton taux horaire de tricot',
  expectedMonth1PatternSales: 'Ventes de patrons attendues au mois 1',
  customNewGarmentAskPrice: 'Prix demandé pour vêtement sur mesure/nouveau',
  sampleSalePrice: 'Prix de vente d’échantillon',
  boothCostFairs: 'Coût de stand (foires)',
  daysAfterReleaseForSale: 'Jours après sortie pour la promo',
  conversionRate: 'Taux de conversion',
  flatFeeOfferPays: 'Forfait versé par l’offre',
  exclusivityWindow: 'Fenêtre d’exclusivité',
  yarnSupportValue: 'Valeur du soutien en laine',
  royaltyShareBoxDeals: 'Part de redevance (box)',
  sampleCostYouFund: 'Coût de l’échantillon (à ta charge)',
  modelPhotographyYouFund: 'Mannequin / photo (à ta charge)',
  techEditingYouFund: 'Édition technique (à ta charge)',
  ownStorePatternPrice: 'Prix du patron dans ta boutique',
  yourTotalHours: 'Tes heures totales',
  yourHourlyRateFloor: 'Ton taux horaire (plancher)',
  weeklyOwnStoreSalesCopies: 'Ventes hebdo en boutique (copies)',
  members: 'Membres',
  downloadsPerMemberMo: 'Téléchargements/membre/mois',
  ratePerPattern: 'Taux par patron',
  buildCostToRecover: 'Coût de construction à amortir',
  productionHoursTotal: 'Heures de production (total)',
  patternHourlyRate: 'Taux horaire de patron',
  platformToolingPerMonth: 'Plateforme/outils / mois',
  materialsTravelOutOfPocket: 'Matériel / déplacements (avance de frais)',
  hoursPerSession: 'Heures par session',
  refundRate: 'Taux de remboursement',
  platformToolingCostLifetime: 'Coût plateforme/outils (durée de vie)',
  platformMembershipRevenueYr: 'Revenu membres plateforme / an',
  yourMinutesShare: 'Ta part de minutes (0,00013 ≈ 260 $/mois sur un pool de 8 M $)',
  platformShareAfterCoupons: 'Part de la plateforme (après coupons)',
  sampleKnitterRate: 'Tarif du tricoteur d’échantillon',
  deadline: 'Date limite',
  feedbackDue: 'Retour attendu',
  yarnSupportUnpaid: 'Soutien en laine / non payé',
  patternPriceVideo: 'Prix du patron',
  platformFee: 'Frais de plateforme',
  monthlyPatternSales: 'Ventes de patrons mensuelles',
  emailSalesPerMonth: 'Ventes par e-mail / mois',
  techEditCovered: 'édition technique couverte',
  photographyCovered: 'photo couverte',
  keepOwnSiteRights: 'conserver les droits sur ton propre site',
  earlyAccess: 'Accès anticipé',
  emailListSize: 'Taille de la liste e-mail',
  expectedMonthlyUnits: 'Unités mensuelles attendues',
  expectedStudentsZeroProject: 'Étudiants attendus (0 = projet de la liste)',
  expectedStudentsBuyers: 'Étudiants / acheteurs attendus',
  extraPatternValue: 'Valeur de patron supplémentaire',
  freeFinalPattern: 'Patron final gratuit',
  listConversion: 'Conversion de la liste',
  minutesPerPost: 'Minutes par publication',
  paidSampleKnitters: 'Tricoteurs d’échantillon payés',
  patternLifetime: 'Durée de vie du patron',
  postsPerMonthAllPlatforms: 'Publications / mois (toutes plateformes)',
  royaltyPerDownload: 'Redevance par téléchargement',
  royaltyRunwayMonths: 'Piste de redevances (mois)',
  seatsPerClassSlot: 'Places par créneau de cours',
  sessions: 'Sessions',
  socialFeature: 'Fonctionnalité sociale',
  studentsCount: 'Étudiants',
  toolingRunwayMonths: 'Piste d’outils (mois)',
  videoLength: 'Durée de la vidéo',
  readinessLevel: 'préparation',
  earlyBirdPriceDollar: 'Prix early-bird ($)',
  emailToOrder: 'E-mail → commande',
  waitlistToOrder: 'Liste d’attente → commande',
  stitchRounding: 'Arrondi de mailles',
  rowRounding: 'Arrondi de rangs',
  handleNamePlaceholder: 'pseudonyme / nom',
  dollarPerYdPlaceholder: '$/yd',
  yarnDollarPlaceholder: 'laine $',
  platformAria: 'plateforme',
  sampleCostRecoveryHeading: 'L’échantillon — quel coût, quel retour ?',
  sampleSaleByChannelHeading: 'Vente d’échantillon par canal — nets comparés au coût',
  launchWindowHeading: 'La fenêtre de lancement — pic de la semaine 1 vs la queue',
  garmentSeason: 'Saison du vêtement',
  plannedReleaseMonth: 'Mois de sortie prévu',
  bestNetBadge: 'Meilleur net',
  sampleLaunchLabTitle: 'Laboratoire Échantillon & Fenêtre de lancement',
  sampleAndLaunchLabDescription: 'Aucun outil ne valorise le vêtement échantillon ni le pic de la semaine de lancement — Ravelry traite un échantillon comme un coût irrécupérable et les outils de lancement s’arrêtent à « publie régulièrement ». Un pull échantillon est le plus gros bloc de coût d’un patron (≈30 h de tricot + 75 $ de laine ≈ 525 $ à 15 $/h), et un lancement bien calé a attrapé Hot Right Now et vendu 76 copies en moins de 5 jours contre 109 sur tout un mois pour le meilleur mois précédent du designer. Ce laboratoire valorise l’échantillon sur quatre canaux et la semaine de lancement avant la queue.',
  weekOneSales: 'Ventes semaine 1',
  tailSales: 'Ventes de la queue',
  weeklyValueAtPrice: 'Valeur hebdo à {price}',
  thenTheTailTakesOver: 'Puis la queue prend le relais — les ventes baissent tout au long du mois.',
  launchBurstAtSeasonFactor: 'Pic de lancement à facteur de saison {factor}',
  sampleNoChannels: 'Aucun canal disponible.',
  channelNoteEtsy: 'Les frais de transaction et d’insertion Etsy s’appliquent aussi au tricot physique ; l’échantillon est une annonce.',
  channelNoteFlash: 'Ventes flash à la Westknits : ~10 % de commission ; la demande se concentre dans la fenêtre du drop, les échantillons partent vite en remise.',
  channelNoteConsignment: 'La vente en dépôt boutique prend typiquement 40 % (fourchette 30–50 %) — aucun risque d’invendu et aucun effort de vente, mais la coupe la plus profonde.',
  channelNoteFair: 'Coût du stand {cost} $ amorti sur les échantillons vendus à la foire + ~2 % de frais de paiement.',
  sampleVerdictRecovers: 'À {channel}, l’échantillon nettoie {net} contre une base de coût de {basis} — il récupère {pct} % de son propre coût de production.',
  sampleVerdictPartial: 'Même le meilleur canal nettoie {net} contre une base de {basis} — la vente d’échantillon ne récupère qu’une partie du coût ; couple-la au pic de lancement (voir le calcul de la semaine 1) pour combler l’écart.',
  keepVsSellNote: 'Garder l’échantillon comme actif de portfolio/marketing a sa propre valeur (photos, cours, trunk shows). S’il nettoie plus que sa base ici, le vendre est une récupération pure ; sinon il reste un actif marketing jusqu’à ce qu’un drop flash l’écoule.',
  burstNoteOnPeak: 'Le mois de lancement tombe en plein pic de saison pour ce type de vêtement — les lancements documentés avec ce timing attrapent Hot Right Now sur Ravelry et concentrent la majorité des ventes du mois dans la première semaine.',
  burstNoteOffPeak: 'Le mois de lancement est hors du pic pour les designs {season} — le pic perd typiquement ~15–35 % de sa force (Diego a vendu 76 copies en moins de 5 jours avec le bon timing ; un mois entier avait donné 109 au meilleur mois du designer).',
  offPeakBurstLossBand: '~15–35 % de sa force',
  monthPctSuffix: '% du mois',
  channelEtsy: 'Annonce Etsy',
  channelFlash: 'Drop flash en ligne (style Westknits)',
  channelBoutique: 'Dépôt boutique',
  channelCraftFair: 'Foire / marché',
};

const es: LabStatCopy = {
  printingCostPerCopy: 'Coste de impresión / copia',
  netRoyaltyPerCopy: 'Regalía neta / copia',
  cannibalizationDragPerMo: 'Erosión por canibalización / mes',
  monthlyNetAfterDrag: 'Neto mensual (tras erosión)',
  royaltyBand: 'Banda de regalía',
  breakEvenUnitsPerMo: 'Unidades de equilibrio / mes',
  physicalVsDigitalRatio: 'Ratio físico vs digital',
  digitalNetPerSale: 'Neto digital / venta',
  digitalNetPerMonthNow: 'Neto digital / mes actual',
  monthsOfPhysicalToMatch1DigitalMonth: 'Meses de físico para igualar un mes digital',
  cpmBenchmarkBand: 'Banda de referencia CPM',
  fairFlatFeePerRead: 'Equivalente justo de tarifa plana por mención',
  cpmBreakEvenAudience: 'Audiencia de equilibrio CPM',
  bestMonthlyNetAllLanes: 'Mejor neto mensual (todos los canales)',
  currentMonthlyNet: 'Neto mensual actual',
  candidateMonthlyNet: 'Neto mensual candidato',
  changeVsCurrent: 'Cambio vs actual',
  currentImpliedUnits: 'Unidades implícitas actuales',
  candidateImpliedUnits: 'Unidades implícitas candidatas',
  leftDigitMoves: 'Cambio de dígito inicial',
  recommendedEnding: 'Terminación recomendada',
  highestShopAnchor: 'Ancla más alta',
  barrierBelow: 'Barrera inferior',
  barrierAbove: 'Barrera superior',
  singlesNetAllComponents: 'Neto individual (todas las piezas)',
  bundleNet: 'Neto del bundle',
  bundleTotalEndsOdd: 'Total del bundle termina en impar (.99)',
  componentsEndEven: 'Piezas terminan en .00',
  bestLaunchMonth: 'Mejor mes de lanzamiento',
  twelveMoRevenueBestWindow: 'Ingresos a 12 meses en la mejor ventana',
  promoAddsRevenue: '¿La promo suma ingresos?',
  asSoonAsReadyValue: 'Valor de lanzamiento inmediato',
  mistimingCostBestVsWorst: 'Costo de mal timing (mejor vs peor)',
  launchWeekDiscountedNet: 'Neto de descuento en semana de lanzamiento',
  launchWeekFullPriceNet: 'Neto a precio completo en semana de lanzamiento',
  peakDemandMultiplier: 'Multiplicador de demanda pico',
  realisticNetCash: 'Efectivo neto realista',
  guestRateBenchmark: 'Referencia de tarifa de invitado',
  breakEvenTargetStudents: 'Equilibrio / estudiantes objetivo',
  alumniConversionValue: 'Valor de conversión de alumnos',
  breakEvenStudents: 'Estudiantes de equilibrio',
  studentsToClearYourRate: 'Estudiantes para cubrir tu tarifa',
  realisticEffectiveRate: 'Tarifa efectiva realista',
  worstCaseEffectiveRate: 'Tarifa efectiva en el peor caso',
  travelShareOfRealisticTakeHome: 'Proporción de viaje del ingreso neto realista',
  realisticVsOpportunityCost: 'Realista vs costo de oportunidad',
  yourHourlyRate: 'Tu tarifa horaria',
  patternPrice: 'Precio del patrón',
  freePoolNet: 'Neto del pool gratuito',
  bestPaidModelNet: 'Neto del mejor modelo de pago',
  sizeCoverageFree: 'Cobertura de tallas (gratis)',
  errorsCaught: 'Errores detectados',
  yourTimeCost: 'Costo de tu tiempo',
  paidSlots: 'Plazas pagadas',
  baseWholesaleKeystoneFloor: 'Mayoreo base (piso keystone)',
  netPerUnitBase: 'Neto por unidad (base)',
  monthlyNetWholesale: 'Neto mensual (mayoreo)',
  breakEvenOrders: 'Pedidos de equilibrio',
  annualWholesaleNet: 'Neto anual de mayoreo',
  minimumOrderGate: 'Umbral de pedido mínimo',
  reordersPerStockistYr: 'Repedidos por tienda / año',
  orderProcessingCost: 'Costo de procesamiento de pedidos',
  unitsPerSkuPerOrder: 'Unidades por SKU por pedido',
  knitHoursPerYearWholesale: 'Horas de tejido / año para mayoreo',
  faireStyleCommission: 'Comisión estilo Faire',
  flatFeeReceived: 'Tarifa fija recibida',
  royaltyStreamTermTotal: 'Flujo de regalías (plazo total)',
  royaltyAfterRiskHaircut: 'Regalía tras recorte de riesgo',
  totalOfferValue: 'Valor total de la oferta',
  exclusivityDragOwnShop: 'Erosión por exclusividad (tienda propia)',
  ownShopBaselineSameWindow: 'Base de tu tienda (misma ventana)',
  offerInYearsOfBaseline: 'Oferta en años de tu base',
  minFlatToSayYes: 'Tarifa fija mínima para aceptar',
  minRoyaltyToSayYes: 'Regalía mínima para aceptar',
  compensationModelComparison: 'Comparación de modelos de compensación',
  watchOutFlags: 'Alertas ({n})',
  verdict: 'Veredicto',
  tierTable: 'Tabla de niveles',
  orderModels: 'Modelos de pedido',
  compareAcrossWeights: 'Comparar entre grosores',
  yourLineWholesaleVsCogs: 'Tu línea (precios mayoristas vs COGS)',
  yesBestSellingConfig: 'Sí — configuración más vendida',
  noShiftTo99: 'No — cambiar a .99',
  yesPairedCorrectly: 'Sí — bien combinadas',
  noEndComponents00: 'No — terminar piezas en .00',
  noDigitChange: 'Sin cambio de dígito',
  noneSet: 'Ninguna definida',
  testerName: 'Nombre del tester',
  notesPerTester: 'Notas por tester',
  partnerCompanyDyerShop: 'Empresa de hilos / tintorero / tienda',
  removePitch: 'Eliminar propuesta',
  dueDate: 'Fecha de entrega',
  partnerNotesPlaceholder: 'Notas — hilo recibido, entregables pendientes, próxima fecha…',
  affilPlaceholder: 'p. ej. LoveCrafts (15 %)',
  retreatTopicPlaceholder: 'p. ej. construcción de canesú sin costuras',
  testKnitRewardPlaceholder: 'p. ej. más una tarjeta de regalo de 10 $ para mi patrocinador de hilos',
  patternNamePlaceholder: 'p. ej. Jersey Calyx',
  lunaWrapPlaceholder: 'p. ej. Chal Luna',
  copyText: 'Copiar texto',
  addPartnerPattern: 'Añadir patrón de socio',
  publishDesignPitchPlaceholder: 'Un cuello redondo relajado tejido plano y con costuras, hombros caídos y acanalado profundo.',
  publishPitchPlaceholder: 'p. ej. Una versión moderna del gansey clásico',
  measurementPlaceholder: 'p. ej. Ancho de espalda',
  notesPlaceholder: 'p. ej. Tejido plano, con costura lateral. Se bloquea generosamente — haz una muestra y bloquéalo antes de decidir la talla.',
  projectNotFound: 'Proyecto no encontrado',
  returnToDashboard: 'Volver al panel',
  recoveryImportTitle: '¿Compartiste este enlace?',
  recoveryImportDesc: 'Este proyecto podría estar en otro dispositivo o navegador. Si tienes un archivo de respaldo (.json), puedes importarlo ahora para continuar.',
  recoveryImportButton: 'Importar proyecto desde archivo',
  recoveryLocalOnlyTitle: 'Privacidad local primero',
  recoveryLocalOnlyDesc: 'Stitch & Scale guarda tus patrones localmente. No se sincronizan automáticamente entre dispositivos a menos que los exportes e importes.',
  baseSize: 'Talla base',
  gauge: 'Muestra',
  infiniteValue: 'inalcanzable',
  minimumList60Band: 'Lista mínima (banda 60 %)',
  opportunityRate: 'Tarifa de oportunidad',
  cpmNetPerMonth: 'CPM — neto / mes',
  flatFeesNetPerMonth: 'Tarifas fijas — neto / mes',
  affiliateNetPerMonth: 'Afiliados — neto / mes',
  bestLanePerHr: 'Mejor canal $/h',
  earliestLaunchThisMonth: 'Lanzamiento más temprano (este mes)',
  designCategory: 'Categoría de diseño',
  yourRole: 'Tu rol',
  effectivePerHrAllIn: '$/h efectivo (horas totales)',
  hoursInvestedPrepClass: 'Horas invertidas (preparación + clase)',
  yarnGoodsPaidServices: 'Productos de hilo + servicios pagados',
  netVsTimeAndDrag: 'Neto vs tu tiempo + erosión',
  priceSamplesPlaceholder: '5,00, 8,00, 14,00',
  yourRoleAndTrip: 'Tu rol y viaje',
  yourClasses: 'Tus clases',
  classTitle: 'Título de la clase',
  classTitleExample: 'p. ej. construcción de canesú sin costuras',
  addAnotherClass: 'Añadir otra clase',
  guestTeacherAtRetreat: 'Profesor invitado a un retiro',
  featuredTeacherOnCruise: 'Profesor destacado en un crucero',
  hostingMyOwnRetreat: 'Organizar mi propio retiro',
  hostEconomics: 'Economía de anfitrión',
  compensationAndCompPackage: 'Compensación y paquete de cortesía',
  dealMathAndScenarioTable: 'Matemática del acuerdo y tabla de escenarios',
  slotsPerSize: 'plazas por talla',
  yarnWeightAria: 'grosor del hilo',
  leadWeeks: 'semanas de preparación',
  ydPlaceholder: '— yd',
  zeroPlaceholder: '0',
  publishedPatternsPortfolio: 'Patrones publicados en el portafolio',
  amountDollars: 'Monto ($)',
  firstOrderMinimumDollars: 'Mínimo de primer pedido ($)',
  repeatMinimumDollars: 'Mínimo de repedido ($)',
  clubTermsRetention: 'Términos y retención',
  yourLineWholesaleVsCogsHeading: 'Tu línea (precios mayoristas vs COGS)',
  knitHoursSample: 'Horas de tejido (muestra)',
  yarnAndMaterials: 'Hilo y materiales',
  yourKnitHourlyRate: 'Tu tarifa horaria de tejido',
  expectedMonth1PatternSales: 'Ventas de patrones esperadas el mes 1',
  customNewGarmentAskPrice: 'Precio pedido de prenda personalizada/nueva',
  sampleSalePrice: 'Precio de venta de muestra',
  boothCostFairs: 'Costo de stand (ferias)',
  daysAfterReleaseForSale: 'Días tras el lanzamiento para la oferta',
  conversionRate: 'Tasa de conversión',
  flatFeeOfferPays: 'Tarifa fija que paga la oferta',
  exclusivityWindow: 'Ventana de exclusividad',
  yarnSupportValue: 'Valor del apoyo de hilos',
  royaltyShareBoxDeals: 'Participación de regalía (cajas)',
  sampleCostYouFund: 'Costo de muestra (lo pagas tú)',
  modelPhotographyYouFund: 'Modelo / fotografía (lo pagas tú)',
  techEditingYouFund: 'Edición técnica (lo pagas tú)',
  ownStorePatternPrice: 'Precio del patrón en tu tienda',
  yourTotalHours: 'Tus horas totais',
  yourHourlyRateFloor: 'Tu tarifa horaria (piso)',
  weeklyOwnStoreSalesCopies: 'Ventas semanales en tienda (copias)',
  members: 'Miembros',
  downloadsPerMemberMo: 'Descargas/miembro/mes',
  ratePerPattern: 'Tarifa por patrón',
  buildCostToRecover: 'Costo de construcción a recuperar',
  productionHoursTotal: 'Horas de producción (total)',
  patternHourlyRate: 'Tarifa horaria de patrón',
  platformToolingPerMonth: 'Plataforma/herramientas / mes',
  materialsTravelOutOfPocket: 'Materiales / viajes (de tu bolsillo)',
  hoursPerSession: 'Horas por sesión',
  refundRate: 'Tasa de reembolso',
  platformToolingCostLifetime: 'Costo de plataforma/herramientas (vitalicio)',
  platformMembershipRevenueYr: 'Ingresos de membresías de plataforma / año',
  yourMinutesShare: 'Tu participación de minutos (0,00013 ≈ 260 $/mes en un pool de 8 M $)',
  platformShareAfterCoupons: 'Participación de la plataforma (tras cupones)',
  sampleKnitterRate: 'Tarifa del tejedor de muestra',
  deadline: 'Fecha límite',
  feedbackDue: 'Comentarios debidos',
  yarnSupportUnpaid: 'Apoyo de hilos / no pagado',
  patternPriceVideo: 'Precio del patrón',
  platformFee: 'Comisión de plataforma',
  monthlyPatternSales: 'Ventas mensuales de patrones',
  emailSalesPerMonth: 'Ventas por email / mes',
  techEditCovered: 'edición técnica cubierta',
  photographyCovered: 'fotografía cubierta',
  keepOwnSiteRights: 'conservar derechos en tu propio sitio',
  earlyAccess: 'Acceso anticipado',
  emailListSize: 'Tamaño de la lista de correo',
  expectedMonthlyUnits: 'Unidades mensuales esperadas',
  expectedStudentsZeroProject: 'Estudiantes esperados (0 = proyecto de la lista)',
  expectedStudentsBuyers: 'Estudiantes / compradores esperados',
  extraPatternValue: 'Valor extra de patrón',
  freeFinalPattern: 'Patrón final gratis',
  listConversion: 'Conversión de lista',
  minutesPerPost: 'Minutos por publicación',
  paidSampleKnitters: 'Tejedores de muestra pagados',
  patternLifetime: 'Vida útil del patrón',
  postsPerMonthAllPlatforms: 'Publicaciones al mes (todas las plataformas)',
  royaltyPerDownload: 'Regalía por descarga',
  royaltyRunwayMonths: 'Reserva de regalías (meses)',
  seatsPerClassSlot: 'Plazas por slot de clase',
  sessions: 'Sesiones',
  socialFeature: 'Función social',
  studentsCount: 'Estudiantes',
  toolingRunwayMonths: 'Reserva de herramientas (meses)',
  videoLength: 'Duración del video',
  readinessLevel: 'preparación',
  earlyBirdPriceDollar: 'Precio early-bird ($)',
  emailToOrder: 'Email → pedido',
  waitlistToOrder: 'Lista de espera → pedido',
  stitchRounding: 'Redondeo de puntos',
  rowRounding: 'Redondeo de filas',
  handleNamePlaceholder: 'usuario / nombre',
  dollarPerYdPlaceholder: '$/yd',
  yarnDollarPlaceholder: 'hilo $',
  platformAria: 'plataforma',
  sampleCostRecoveryHeading: 'La muestra — qué costó, qué recupera',
  sampleSaleByChannelHeading: 'Venta de muestra por canal — netos frente al coste base',
  launchWindowHeading: 'La ventana de lanzamiento — pico de la semana 1 vs la cola',
  garmentSeason: 'Temporada de la prenda',
  plannedReleaseMonth: 'Mes de lanzamiento previsto',
  bestNetBadge: 'Mejor neto',
  sampleLaunchLabTitle: 'Laboratorio de Muestra y Ventana de Lanzamiento',
  sampleAndLaunchLabDescription: 'Ninguna herramienta valora la prenda de muestra ni el pico de la semana de lanzamiento — Ravelry trata la muestra como costo hundido y las herramientas de lanzamiento se quedan en «publica constantemente». Una muestra de suéter es el mayor bloque de costo único de un patrón (≈30 h de tejido + 75 $ de hilo ≈ 525 $ a 15 $/h), y un lanzamiento bien sincronizado atrapó Hot Right Now y vendió 76 copias en menos de 5 días frente a 109 en todo un mes del mejor resultado anterior. Este laboratorio valora la muestra en cuatro canales y la semana de lanzamiento antes de la cola.',
  weekOneSales: 'Ventas de la semana 1',
  tailSales: 'Ventas de la cola',
  weeklyValueAtPrice: 'Valor semanal a {price}',
  thenTheTailTakesOver: 'Luego la cola toma el mando — las ventas caen durante el mes.',
  launchBurstAtSeasonFactor: 'Pico de lanzamiento con factor de temporada {factor}',
  sampleNoChannels: 'Sin canales disponibles.',
  channelNoteEtsy: 'Las tarifas de transacción y publicación de Etsy también aplican al tejido físico; la muestra es una publicación.',
  channelNoteFlash: 'Drops flash estilo Westknits: ~10% de corte de plataforma; la demanda se concentra en la ventana del drop, las muestras se venden rápido con descuento.',
  channelNoteConsignment: 'La consignación boutique suele tomar el 40% (banda 30–50%) — sin riesgo de sobras ni esfuerzo de venta, pero el corte más profundo.',
  channelNoteFair: 'Costo del stand ${cost} amortizado entre las muestras vendidas en la feria + ~2% de comisión por tarjeta.',
  sampleVerdictRecovers: 'En {channel} la muestra deja {net} contra una base de costo de {basis} — recupera el {pct}% de su propio costo de producción.',
  sampleVerdictPartial: 'Incluso el mejor canal deja {net} contra una base de {basis} — la venta de la muestra solo recupera parcialmente el costo; combínala con el pico de lanzamiento (ver matemática de la semana 1) para cerrar la brecha.',
  keepVsSellNote: 'Guardar la muestra como activo de portafolio/marketing tiene valor propio (fotos, clases, trunk shows). Si deja más que su base aquí, venderla es recuperación pura; si deja menos, sigue siendo activo de marketing hasta que un drop flash la liquide.',
  monthPctSuffix: '% del mes',
  channelEtsy: 'Anuncio Etsy',
  channelFlash: 'Drop online exprés (estilo Westknits)',
  channelBoutique: 'Consignación boutique',
  channelCraftFair: 'Feria / mercado',
  burstNoteOnPeak: 'El mes de lanzamiento cae dentro del pico de temporada para este tipo de prenda — lanzamientos documentados con este timing atrapan Hot Right Now de Ravelry y concentran la mayoría de las ventas del mes en la primera semana.',
  burstNoteOffPeak: 'El mes de lanzamiento está fuera del pico para diseños {season} — el pico suele perder ~15–35% de su fuerza (Diego vendió 76 copias en menos de 5 días con el timing correcto; un mes entero le dio 109 al mejor mes anterior).',
  offPeakBurstLossBand: '~15–35% de su fuerza',
};

const pt: LabStatCopy = {
  printingCostPerCopy: 'Custo de impressão / cópia',
  netRoyaltyPerCopy: 'Royalty líquido / cópia',
  cannibalizationDragPerMo: 'Erosão por canibalização / mês',
  monthlyNetAfterDrag: 'Líquido mensal (após erosão)',
  royaltyBand: 'Faixa de royalty',
  breakEvenUnitsPerMo: 'Unidades de ponto de equilíbrio / mês',
  physicalVsDigitalRatio: 'Proporção físico vs digital',
  digitalNetPerSale: 'Líquido digital / venda',
  digitalNetPerMonthNow: 'Líquido digital / mês atual',
  monthsOfPhysicalToMatch1DigitalMonth: 'Meses de físico para igualar um mês digital',
  cpmBenchmarkBand: 'Faixa de referência de CPM',
  fairFlatFeePerRead: 'Equivalente justo de taxa fixa por menção',
  cpmBreakEvenAudience: 'Audiência de equilíbrio de CPM',
  bestMonthlyNetAllLanes: 'Melhor líquido mensal (todos os canais)',
  currentMonthlyNet: 'Líquido mensal atual',
  candidateMonthlyNet: 'Líquido mensal candidato',
  changeVsCurrent: 'Variação vs atual',
  currentImpliedUnits: 'Unidades implícitas atuais',
  candidateImpliedUnits: 'Unidades implícitas candidatas',
  leftDigitMoves: 'Mudança do dígito inicial',
  recommendedEnding: 'Terminação recomendada',
  highestShopAnchor: 'Âncora mais alta',
  barrierBelow: 'Barreira inferior',
  barrierAbove: 'Barreira superior',
  singlesNetAllComponents: 'Líquido avulso (todas as peças)',
  bundleNet: 'Líquido do pacote',
  bundleTotalEndsOdd: 'Total do pacote termina em ímpar (.99)',
  componentsEndEven: 'Peças terminam em .00',
  bestLaunchMonth: 'Melhor mês de lançamento',
  twelveMoRevenueBestWindow: 'Receita de 12 meses na melhor janela',
  promoAddsRevenue: 'A promo aumenta a receita?',
  asSoonAsReadyValue: 'Valor de lançamento imediato',
  mistimingCostBestVsWorst: 'Custo de timing errado (melhor vs pior)',
  launchWeekDiscountedNet: 'Líquido promocional na semana de lançamento',
  launchWeekFullPriceNet: 'Líquido a preço cheio na semana de lançamento',
  peakDemandMultiplier: 'Multiplicador de demanda de pico',
  realisticNetCash: 'Caixa líquido realista',
  guestRateBenchmark: 'Referência de tarifa de convidado',
  breakEvenTargetStudents: 'Equilíbrio / alunos-alvo',
  alumniConversionValue: 'Valor de conversão de ex-alunos',
  breakEvenStudents: 'Alunos de ponto de equilíbrio',
  studentsToClearYourRate: 'Alunos para cobrir sua tarifa',
  realisticEffectiveRate: 'Taxa efetiva realista',
  worstCaseEffectiveRate: 'Taxa efetiva no pior caso',
  travelShareOfRealisticTakeHome: 'Participação de viagem no líquido realista',
  realisticVsOpportunityCost: 'Realista vs custo de oportunidade',
  yourHourlyRate: 'Sua tarifa horária',
  patternPrice: 'Preço do padrão',
  freePoolNet: 'Líquido do pool gratuito',
  bestPaidModelNet: 'Líquido do melhor modelo pago',
  sizeCoverageFree: 'Cobertura de tamanhos (grátis)',
  errorsCaught: 'Erros detectados',
  yourTimeCost: 'Custo do seu tempo',
  paidSlots: 'Vagas pagas',
  baseWholesaleKeystoneFloor: 'Atacado base (piso keystone)',
  netPerUnitBase: 'Líquido por unidade (base)',
  monthlyNetWholesale: 'Líquido mensal (atacado)',
  breakEvenOrders: 'Pedidos de ponto de equilíbrio',
  annualWholesaleNet: 'Líquido anual de atacado',
  minimumOrderGate: 'Limiar de pedido mínimo',
  reordersPerStockistYr: 'Recompras por loja / ano',
  orderProcessingCost: 'Custo de processamento de pedidos',
  unitsPerSkuPerOrder: 'Unidades por SKU por pedido',
  knitHoursPerYearWholesale: 'Horas de tricô / ano para atacado',
  faireStyleCommission: 'Comissão estilo Faire',
  flatFeeReceived: 'Taxa fixa recebida',
  royaltyStreamTermTotal: 'Fluxo de royalty (período total)',
  royaltyAfterRiskHaircut: 'Royalty após corte de risco',
  totalOfferValue: 'Valor total da oferta',
  exclusivityDragOwnShop: 'Erosão por exclusividade (loja própria)',
  ownShopBaselineSameWindow: 'Sua base da loja (mesma janela)',
  offerInYearsOfBaseline: 'Oferta em anos da sua base',
  minFlatToSayYes: 'Taxa fixa mínima para aceitar',
  minRoyaltyToSayYes: 'Royalty mínimo para aceitar',
  compensationModelComparison: 'Comparação de modelos de compensação',
  watchOutFlags: 'Alertas ({n})',
  verdict: 'Veredicto',
  tierTable: 'Tabela de níveis',
  orderModels: 'Modelos de pedido',
  compareAcrossWeights: 'Comparar entre espessuras',
  yourLineWholesaleVsCogs: 'Sua linha (preços de atacado vs custo)',
  yesBestSellingConfig: 'Sim — configuração mais vendida',
  noShiftTo99: 'Não — mudar para .99',
  yesPairedCorrectly: 'Sim — bem combinadas',
  noEndComponents00: 'Não — terminar peças em .00',
  noDigitChange: 'Sem mudança de dígito',
  noneSet: 'Nenhuma definida',
  testerName: 'Nome do tester',
  notesPerTester: 'Notas por tester',
  partnerCompanyDyerShop: 'Empresa de fios / tinturaria / loja',
  removePitch: 'Remover proposta',
  dueDate: 'Data de entrega',
  partnerNotesPlaceholder: 'Notas — fio recebido, entregas devidas, próximo prazo…',
  affilPlaceholder: 'ex.: LoveCrafts (15 %)',
  retreatTopicPlaceholder: 'ex.: construção de yoke sem costura',
  testKnitRewardPlaceholder: 'ex.: mais um cartão-presente de US$ 10 para meu patrocinador de fios',
  patternNamePlaceholder: 'ex.: Blusão Calyx',
  lunaWrapPlaceholder: 'ex.: Poncho Luna',
  copyText: 'Copiar texto',
  addPartnerPattern: 'Adicionar padrão de parceiro',
  publishDesignPitchPlaceholder: 'Uma gola redonda relaxada, tricotada plana e costurada, com ombros caídos e barra canelada profunda.',
  publishPitchPlaceholder: 'ex.: Uma releitura moderna do clássico gansey',
  measurementPlaceholder: 'ex.: Largura das costas',
  notesPlaceholder: 'ex.: Tricotado plano, costurado na lateral. Bloqueia com folga — faça uma amostra e bloqueie antes de definir o tamanho.',
  projectNotFound: 'Projeto não encontrado',
  returnToDashboard: 'Voltar ao painel',
  recoveryImportTitle: 'Compartilhou este link?',
  recoveryImportDesc: 'Este projeto pode estar em outro dispositivo ou navegador. Se você tiver um arquivo de backup (.json), pode importá-lo agora para continuar.',
  recoveryImportButton: 'Importar projeto de arquivo',
  recoveryLocalOnlyTitle: 'Privacidade local primeiro',
  recoveryLocalOnlyDesc: 'O Stitch & Scale armazena seus padrões localmente. Eles não são sincronizados automaticamente entre dispositivos, a menos que você os exporte e importe.',
  baseSize: 'Tamanho base',
  gauge: 'Amostra',
  infiniteValue: 'inalcançável',
  minimumList60Band: 'Lista mínima (faixa 60 %)',
  opportunityRate: 'Taxa de oportunidade',
  cpmNetPerMonth: 'CPM — líquido / mês',
  flatFeesNetPerMonth: 'Taxas fixas — líquido / mês',
  affiliateNetPerMonth: 'Afiliados — líquido / mês',
  bestLanePerHr: 'Melhor canal $/h',
  earliestLaunchThisMonth: 'Lançamento mais cedo (este mês)',
  designCategory: 'Categoria de design',
  yourRole: 'Seu papel',
  effectivePerHrAllIn: '$/h efetivo (horas totais)',
  hoursInvestedPrepClass: 'Horas investidas (preparação + aula)',
  yarnGoodsPaidServices: 'Produtos de fio + serviços pagos',
  netVsTimeAndDrag: 'Líquido vs seu tempo + erosão',
  priceSamplesPlaceholder: '5,00, 8,00, 14,00',
  yourRoleAndTrip: 'Seu papel e viagem',
  yourClasses: 'Suas aulas',
  classTitle: 'Título da aula',
  classTitleExample: 'ex.: construção de yoke sem costura',
  addAnotherClass: 'Adicionar outra aula',
  guestTeacherAtRetreat: 'Professor convidado em um retiro',
  featuredTeacherOnCruise: 'Professor destaque em um cruzeiro',
  hostingMyOwnRetreat: 'Organizar meu próprio retiro',
  hostEconomics: 'Economia de anfitrião',
  compensationAndCompPackage: 'Compensação e pacote de cortesia',
  dealMathAndScenarioTable: 'Cálculo do acordo e tabela de cenários',
  slotsPerSize: 'vagas por tamanho',
  yarnWeightAria: 'espessura do fio',
  leadWeeks: 'semanas de lead',
  ydPlaceholder: '— jda',
  zeroPlaceholder: '0',
  publishedPatternsPortfolio: 'Padrões publicados no portfólio',
  amountDollars: 'Valor ($)',
  firstOrderMinimumDollars: 'Mínimo do primeiro pedido ($)',
  repeatMinimumDollars: 'Mínimo de recompra ($)',
  clubTermsRetention: 'Termos e retenção',
  yourLineWholesaleVsCogsHeading: 'Sua linha (preços de atacado vs custo)',
  knitHoursSample: 'Horas de tricô (sample)',
  yarnAndMaterials: 'Fio e materiais',
  yourKnitHourlyRate: 'Sua tarifa horária de tricô',
  expectedMonth1PatternSales: 'Vendas de padrões esperadas no mês 1',
  customNewGarmentAskPrice: 'Preço pedido de peça personalizada/nova',
  sampleSalePrice: 'Preço de venda de amostra',
  boothCostFairs: 'Custo de estande (feiras)',
  daysAfterReleaseForSale: 'Dias após o lançamento para a promoção',
  conversionRate: 'Taxa de conversão',
  flatFeeOfferPays: 'Taxa fixa paga pela oferta',
  exclusivityWindow: 'Janela de exclusividade',
  yarnSupportValue: 'Valor do apoio de fios',
  royaltyShareBoxDeals: 'Participação de royalty (caixas)',
  sampleCostYouFund: 'Custo da amostra (pago por você)',
  modelPhotographyYouFund: 'Modelo / fotografia (pago por você)',
  techEditingYouFund: 'Edição técnica (pago por você)',
  ownStorePatternPrice: 'Preço do padrão na sua loja',
  yourTotalHours: 'Suas horas totais',
  yourHourlyRateFloor: 'Sua tarifa horária (piso)',
  weeklyOwnStoreSalesCopies: 'Vendas semanais na loja (cópias)',
  members: 'Membros',
  downloadsPerMemberMo: 'Downloads/membro/mês',
  ratePerPattern: 'Taxa por padrão',
  buildCostToRecover: 'Custo de desenvolvimento a recuperar',
  productionHoursTotal: 'Horas de produção (total)',
  patternHourlyRate: 'Taxa horária de padrão',
  platformToolingPerMonth: 'Plataforma/ferramentas / mês',
  materialsTravelOutOfPocket: 'Materiais / viagens (do seu bolso)',
  hoursPerSession: 'Horas por sessão',
  refundRate: 'Taxa de reembolso',
  platformToolingCostLifetime: 'Custo de plataforma/ferramentas (vida útil)',
  platformMembershipRevenueYr: 'Receita de membros da plataforma / ano',
  yourMinutesShare: 'Sua participação de minutos (0,00013 ≈ US$ 260/mês em um pool de US$ 8 mi)',
  platformShareAfterCoupons: 'Participação da plataforma (após cupons)',
  sampleKnitterRate: 'Tarifa do tricoteiro de amostra',
  deadline: 'Prazo',
  feedbackDue: 'Feedback devido',
  yarnSupportUnpaid: 'Apoio de fios / não pago',
  patternPriceVideo: 'Preço do padrão',
  platformFee: 'Taxa da plataforma',
  monthlyPatternSales: 'Vendas mensais de padrões',
  emailSalesPerMonth: 'Vendas por e-mail / mês',
  techEditCovered: 'edição técnica coberta',
  photographyCovered: 'fotografia coberta',
  keepOwnSiteRights: 'manter direitos no seu próprio site',
  earlyAccess: 'Acesso antecipado',
  emailListSize: 'Tamanho da lista de e-mail',
  expectedMonthlyUnits: 'Unidades mensais esperadas',
  expectedStudentsZeroProject: 'Alunos esperados (0 = projeto da lista)',
  expectedStudentsBuyers: 'Alunos / compradores esperados',
  extraPatternValue: 'Valor extra de padrão',
  freeFinalPattern: 'Padrão final grátis',
  listConversion: 'Conversão de lista',
  minutesPerPost: 'Minutos por post',
  paidSampleKnitters: 'Tricoteiros de amostra pagos',
  patternLifetime: 'Vida útil do padrão',
  postsPerMonthAllPlatforms: 'Posts por mês (todas as plataformas)',
  royaltyPerDownload: 'Royalty por download',
  royaltyRunwayMonths: 'Reserva de royalty (meses)',
  seatsPerClassSlot: 'Vagas por slot de aula',
  sessions: 'Sessões',
  socialFeature: 'Recurso social',
  studentsCount: 'Alunos',
  toolingRunwayMonths: 'Reserva de ferramentas (meses)',
  videoLength: 'Duração do vídeo',
  readinessLevel: 'preparação',
  earlyBirdPriceDollar: 'Preço early-bird ($)',
  emailToOrder: 'E-mail → pedido',
  waitlistToOrder: 'Lista de espera → pedido',
  stitchRounding: 'Arredondamento de pontos',
  rowRounding: 'Arredondamento de fileiras',
  handleNamePlaceholder: 'usuário / nome',
  dollarPerYdPlaceholder: 'US$/jarda',
  yarnDollarPlaceholder: 'fio $',
  platformAria: 'plataforma',
  sampleCostRecoveryHeading: 'A sample — quanto custou, quanto recupera',
  sampleSaleByChannelHeading: 'Venda de amostra por canal — líquidos vs base de custo',
  launchWindowHeading: 'A janela de lançamento — pico da semana 1 vs cauda',
  garmentSeason: 'Temporada da peça',
  plannedReleaseMonth: 'Mês de lançamento previsto',
  bestNetBadge: 'Melhor líquido',
  sampleLaunchLabTitle: 'Laboratório de Sample e Janela de Lançamento',
  sampleAndLaunchLabDescription: 'Nenhuma ferramenta precifica a peça de amostra nem o pico da semana de lançamento — a Ravelry trata a amostra como custo perdido e ferramentas de lançamento param em «poste com consistência». Uma amostra de suéter é o maior bloco de custo único de um padrão (≈30 h de tricô + US$ 75 de fio ≈ US$ 525 a US$ 15/h), e um lançamento bem cronometrado pegou o Hot Right Now e vendeu 76 cópias em menos de 5 dias contra 109 em um mês inteiro no melhor mês anterior. Este laboratório precifica a amostra em quatro canais e a semana de lançamento antes da cauda.',
  weekOneSales: 'Vendas da semana 1',
  tailSales: 'Vendas da cauda',
  weeklyValueAtPrice: 'Valor semanal a {price}',
  thenTheTailTakesOver: 'Depois a cauda assume — as vendas caem ao longo do mês.',
  launchBurstAtSeasonFactor: 'Pico de lançamento com fator sazonal {factor}',
  sampleNoChannels: 'Nenhum canal disponível.',
  channelNoteEtsy: 'As taxas de transação e listagem do Etsy também valem para malharia física; a amostra é uma listagem.',
  channelNoteFlash: 'Drops flash estilo Westknits: ~10% de taxa da plataforma; a demanda se concentra na janela do drop, amostras esgotam rápido com desconto.',
  channelNoteConsignment: 'Consignação em boutique normalmente leva 40% (banda 30–50%) — sem risco de sobras nem esforço de venda, mas o maior corte.',
  channelNoteFair: 'Custo do estande ${cost} amortizado entre as amostras vendidas na feira + ~2% de taxa de cartão.',
  sampleVerdictRecovers: 'Em {channel} a amostra deixa {net} contra uma base de custo de {basis} — ela recupera {pct}% do seu próprio custo de produção.',
  sampleVerdictPartial: 'Até o melhor canal deixa {net} contra uma base de {basis} — a venda da amostra só recupera parcialmente o custo; combine-a com o pico de lançamento (veja a matemática da semana 1) para fechar a lacuna.',
  keepVsSellNote: 'Manter a amostra como ativo de portfólio/marketing tem valor próprio (fotos, aulas, trunk shows). Se ela deixar mais que a base aqui, vendê-la é recuperação pura; se deixar menos, ela fica como ativo de marketing até um drop flash liquidá-la.',
  burstNoteOnPeak: 'O mês de lançamento cai dentro do pico da temporada para esse tipo de peça — lançamentos documentados com esse timing pegam o Hot Right Now da Ravelry e concentram a maior parte das vendas do mês na primeira semana.',
  burstNoteOffPeak: 'O mês de lançamento está fora do pico para designs {season} — o pico geralmente perde ~15–35% da sua força (Diego vendeu 76 cópias em menos de 5 dias com o timing certo; um mês inteiro rendeu 109 no melhor mês anterior).',
  offPeakBurstLossBand: '~15–35% da sua força',
  monthPctSuffix: '% do mês',
  channelEtsy: 'Anúncio Etsy',
  channelFlash: 'Drop online relâmpago (estilo Westknits)',
  channelBoutique: 'Consignação boutique',
  channelCraftFair: 'Feira / mercado',
};

export const LAB_STAT_COPY: Record<LanguageCode, LabStatCopy> = { en, de, fr, es, pt };
export function getLabStatCopy(language: LanguageCode): LabStatCopy {
  return LAB_STAT_COPY[language] ?? LAB_STAT_COPY.en;
}
