import type { LanguageCode } from './i18n';

export interface MembershipSiteCopy {title:string;description:string;audience:string;engaged:string;conservative:string;realistic:string;best:string;conversionNote:string;pricing:string;monthly:string;annual:string;annualMembers:string;churn:string;contentHours:string;supportHours:string;rate:string;feeStack:string;numbers:string;scenario:string;members:string;gross:string;fees:string;net:string;ltv:string;breakEven:string;treadmill:string;ratio:string;lifetime:string;watchouts:string;verdict:string;people:string;channels:{low:string;realistic:string;high:string}}
const en={title:'Membership Site Lab',description:'Should you launch a paid pattern membership — and does the math support it? Model conversion bands, the real fee stack, churn-capped member lifetime, and whether the monthly pattern treadmill pays your hours.',audience:'Audience & conversion',engaged:'Engaged followers',conservative:'Conservative conversion',realistic:'Realistic conversion',best:'Best conversion',conversionNote:'Conversion is entered as a percent; 3% is a healthy realistic band, while newsletter-to-paid medians can be much lower.',pricing:'Pricing & retention',monthly:'Monthly price',annual:'Annual price (0 = none)',annualMembers:'Members on annual',churn:'Monthly churn',contentHours:'Content hours / month',supportHours:'Support / moderation hrs',rate:'Opportunity rate',feeStack:'Fee stack',numbers:'What the numbers say',scenario:'Scenario',members:'Members',gross:'Gross / mo',fees:'Fees / mo',net:'Net / mo',ltv:'LTV / member',breakEven:'Break-even audience',treadmill:'Treadmill gap / mo',ratio:'Net ÷ hours cost',lifetime:'Member lifetime',watchouts:'Watch-outs',verdict:'Verdict',people:'people',channels:{low:'Conservative',realistic:'Realistic',high:'Best case'}};
const de={...en,title:'Mitgliedschafts-Labor',description:'Solltest du eine kostenpflichtige Muster-Mitgliedschaft starten — und trägt die Rechnung? Modellieren Sie Konversionsspannen, echte Gebühren, churn-begrenzte Mitgliedsdauer und ob das monatliche Muster-Laufband Ihre Stunden bezahlt.',audience:'Zielgruppe & Konversion',engaged:'Engagierte Follower',conservative:'Konservative Konversion',realistic:'Realistische Konversion',best:'Beste Konversion',conversionNote:'Die Konversion wird als Prozent eingegeben; 3 % ist ein gesunder realistischer Wert, Newsletter-Mediane können deutlich niedriger liegen.',pricing:'Preis & Bindung',monthly:'Monatlicher Preis',annual:'Jahrespreis (0 = keiner)',annualMembers:'Mitglieder mit Jahresabo',churn:'Monatliche Abwanderung',contentHours:'Inhaltsstunden / Monat',supportHours:'Support-/Moderationsstunden',rate:'Opportunitätswert',feeStack:'Gebührenmodell',numbers:'Was die Zahlen sagen',scenario:'Szenario',members:'Mitglieder',gross:'Brutto / Monat',fees:'Gebühren / Monat',net:'Netto / Monat',ltv:'LTV / Mitglied',breakEven:'Break-even-Zielgruppe',treadmill:'Laufband-Lücke / Monat',ratio:'Netto ÷ Stundenkosten',lifetime:'Mitgliedsdauer',watchouts:'Achtungspunkte',verdict:'Urteil',people:'Personen',channels:{low:'Konservativ',realistic:'Realistisch',high:'Bestfall'}};
const fr={...en,title:'Laboratoire d’abonnement',description:'Faut-il lancer une adhésion payante aux modèles — et les chiffres la justifient-ils ? Modélisez les taux de conversion, les frais réels, la durée de vie plafonnée par le churn et la capacité de l’abonnement à rémunérer vos heures.',audience:'Audience & conversion',engaged:'Abonnés engagés',conservative:'Conversion prudente',realistic:'Conversion réaliste',best:'Meilleure conversion',conversionNote:'La conversion est saisie en pourcentage ; 3 % constitue une bonne hypothèse réaliste, tandis que les médianes newsletter-payant peuvent être bien plus basses.',pricing:'Prix & rétention',monthly:'Prix mensuel',annual:'Prix annuel (0 = aucun)',annualMembers:'Membres annuels',churn:'Churn mensuel',contentHours:'Heures de contenu / mois',supportHours:'Heures support / modération',rate:'Taux d’opportunité',feeStack:'Structure de frais',numbers:'Ce que disent les chiffres',scenario:'Scénario',members:'Membres',gross:'Brut / mois',fees:'Frais / mois',net:'Net / mois',ltv:'LTV / membre',breakEven:'Audience au seuil de rentabilité',treadmill:'Écart du rythme / mois',ratio:'Net ÷ coût des heures',lifetime:'Durée de vie membre',watchouts:'Points de vigilance',verdict:'Verdict',people:'personnes',channels:{low:'Prudent',realistic:'Réaliste',high:'Meilleur cas'}};
const es={...en,title:'Laboratorio de membresía',description:'¿Deberías lanzar una membresía de patrones de pago y la respaldan las cifras? Modela bandas de conversión, la estructura real de comisiones, la vida del miembro limitada por la baja y si el ritmo mensual de patrones paga tus horas.',audience:'Audiencia y conversión',engaged:'Seguidores activos',conservative:'Conversión conservadora',realistic:'Conversión realista',best:'Mejor conversión',conversionNote:'La conversión se introduce como porcentaje; 3 % es una banda realista saludable, mientras que las medianas de newsletter a pago pueden ser mucho menores.',pricing:'Precio y retención',monthly:'Precio mensual',annual:'Precio anual (0 = ninguno)',annualMembers:'Miembros anuales',churn:'Baja mensual',contentHours:'Horas de contenido / mes',supportHours:'Horas de soporte / moderación',rate:'Tasa de oportunidad',feeStack:'Estructura de comisiones',numbers:'Qué dicen las cifras',scenario:'Escenario',members:'Miembros',gross:'Bruto / mes',fees:'Comisiones / mes',net:'Neto / mes',ltv:'LTV / miembro',breakEven:'Audiencia de equilibrio',treadmill:'Brecha del ritmo / mes',ratio:'Neto ÷ coste de horas',lifetime:'Vida del miembro',watchouts:'Puntos de atención',verdict:'Veredicto',people:'personas',channels:{low:'Conservador',realistic:'Realista',high:'Mejor caso'}};
const pt={...en,title:'Laboratório de adesão',description:'Deve lançar uma adesão paga de padrões — e a matemática apoia a decisão? Modele faixas de conversão, a estrutura real de taxas, a duração limitada pelo churn e se o ritmo mensal de padrões paga as suas horas.',audience:'Audiência e conversão',engaged:'Seguidores envolvidos',conservative:'Conversão conservadora',realistic:'Conversão realista',best:'Melhor conversão',conversionNote:'A conversão é introduzida em percentagem; 3% é uma faixa realista saudável, enquanto as medianas de newsletter para pago podem ser muito inferiores.',pricing:'Preço e retenção',monthly:'Preço mensal',annual:'Preço anual (0 = nenhum)',annualMembers:'Membros anuais',churn:'Churn mensal',contentHours:'Horas de conteúdo / mês',supportHours:'Horas de suporte / moderação',rate:'Taxa de oportunidade',feeStack:'Estrutura de taxas',numbers:'O que dizem os números',scenario:'Cenário',members:'Membros',gross:'Bruto / mês',fees:'Taxas / mês',net:'Líquido / mês',ltv:'LTV / membro',breakEven:'Audiência de equilíbrio',treadmill:'Diferença do ritmo / mês',ratio:'Líquido ÷ custo das horas',lifetime:'Duração do membro',watchouts:'Pontos de atenção',verdict:'Veredicto',people:'pessoas',channels:{low:'Conservador',realistic:'Realista',high:'Melhor caso'}};
export const MEMBERSHIP_SITE_COPY: Record<LanguageCode, MembershipSiteCopy> = { en, de, fr, es, pt };

const languageOf = (locale: string): LanguageCode => {
  const code = locale.toLowerCase().split('-')[0] as LanguageCode;
  return MEMBERSHIP_SITE_COPY[code] ? code : 'en';
};

const money = (locale: string, value: number): string => new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const number = (locale: string, value: number): string => new Intl.NumberFormat(locale, { maximumFractionDigits: 0 }).format(value);

const FEE_STACK_LABELS: Record<LanguageCode, Record<string, string>> = {
  en: { payhipFree: 'Payhip (free plan, 5% + PayPal)', payhipPlus: 'Payhip Plus ($29/mo, 2% + card)', wixStripe: 'Wix memberships (Stripe 2.9% + $0.30)', patreon: 'Patreon (8% + processing)', ravelryGifts: 'Ravelry gift codes (3.5% + PayPal)' },
  de: { payhipFree: 'Payhip (kostenlos, 5 % + PayPal)', payhipPlus: 'Payhip Plus (29 $/Monat, 2 % + Karte)', wixStripe: 'Wix-Mitgliedschaften (Stripe 2,9 % + 0,30 $)', patreon: 'Patreon (8 % + Zahlungsabwicklung)', ravelryGifts: 'Ravelry-Gutscheincodes (3,5 % + PayPal)' },
  fr: { payhipFree: 'Payhip (forfait gratuit, 5 % + PayPal)', payhipPlus: 'Payhip Plus (29 $/mois, 2 % + carte)', wixStripe: 'Abonnements Wix (Stripe 2,9 % + 0,30 $)', patreon: 'Patreon (8 % + traitement)', ravelryGifts: 'Codes cadeau Ravelry (3,5 % + PayPal)' },
  es: { payhipFree: 'Payhip (plan gratuito, 5 % + PayPal)', payhipPlus: 'Payhip Plus (29 $/mes, 2 % + tarjeta)', wixStripe: 'Membresías Wix (Stripe 2,9 % + 0,30 $)', patreon: 'Patreon (8 % + procesamiento)', ravelryGifts: 'Códigos regalo de Ravelry (3,5 % + PayPal)' },
  pt: { payhipFree: 'Payhip (plano gratuito, 5% + PayPal)', payhipPlus: 'Payhip Plus (29 $/mês, 2% + cartão)', wixStripe: 'Adesões Wix (Stripe 2,9% + 0,30 $)', patreon: 'Patreon (8% + processamento)', ravelryGifts: 'Códigos-presente Ravelry (3,5% + PayPal)' },
};

const FLAG_TITLES: Record<LanguageCode, Record<string, string>> = {
  en: { 'MS-01': 'Audience too small for a club yet', 'MS-02': 'Conversion assumption is optimistic', 'MS-03': 'Churn erases member value', 'MS-04': 'Fees eat revenue', 'MS-05': 'The pattern treadmill underpays', 'MS-06': 'Annual discount is steep', 'MS-07': 'Member support hours missing' },
  de: { 'MS-01': 'Die Zielgruppe ist noch zu klein', 'MS-02': 'Die Konversionsannahme ist optimistisch', 'MS-03': 'Abwanderung vernichtet den Mitgliedswert', 'MS-04': 'Gebühren verbrauchen Einnahmen', 'MS-05': 'Das Muster-Laufband bezahlt zu wenig', 'MS-06': 'Der Jahresrabatt ist hoch', 'MS-07': 'Stunden für Mitgliedersupport fehlen' },
  fr: { 'MS-01': 'Audience encore trop petite pour un club', 'MS-02': 'Hypothèse de conversion optimiste', 'MS-03': 'Le churn réduit la valeur membre', 'MS-04': 'Les frais absorbent les revenus', 'MS-05': 'Le rythme des modèles paie trop peu', 'MS-06': 'La remise annuelle est forte', 'MS-07': 'Heures de support membre manquantes' },
  es: { 'MS-01': 'La audiencia aún es pequeña para un club', 'MS-02': 'La conversión prevista es optimista', 'MS-03': 'La baja reduce el valor del miembro', 'MS-04': 'Las comisiones consumen ingresos', 'MS-05': 'El ritmo de patrones paga poco', 'MS-06': 'El descuento anual es elevado', 'MS-07': 'Faltan horas de soporte a miembros' },
  pt: { 'MS-01': 'A audiência ainda é pequena para um clube', 'MS-02': 'A conversão prevista é otimista', 'MS-03': 'O churn reduz o valor do membro', 'MS-04': 'As taxas consomem receita', 'MS-05': 'O ritmo de padrões paga pouco', 'MS-06': 'O desconto anual é elevado', 'MS-07': 'Faltam horas de apoio aos membros' },
};

const VERDICT_LABELS: Record<LanguageCode, Record<string, string>> = {
  en: { notReady: 'Not ready — grow the audience first', love: 'Club pays less than your hours — launch for love, not money', borderline: 'Borderline — small club, launch lean', thin: 'Club pays, but the treadmill bites', fund: 'Fund the club — the numbers support it' },
  de: { notReady: 'Noch nicht bereit — baue zuerst die Zielgruppe aus', love: 'Der Club bezahlt deine Stunden nicht — starte aus Überzeugung, nicht fürs Geld', borderline: 'Grenzwertig — kleiner Club, schlank starten', thin: 'Der Club zahlt, aber das Laufband nagt', fund: 'Finanziere den Club — die Zahlen sprechen dafür' },
  fr: { notReady: 'Pas encore prêt — développez d’abord l’audience', love: 'Le club paie moins que vos heures — lancez-le par passion, pas pour l’argent', borderline: 'Limite — petit club, lancez simplement', thin: 'Le club paie, mais le rythme pèse', fund: 'Financez le club — les chiffres sont favorables' },
  es: { notReady: 'Aún no — aumenta primero la audiencia', love: 'El club paga menos que tus horas — lánzalo por pasión, no por dinero', borderline: 'Al límite — club pequeño, empieza con poco', thin: 'El club paga, pero el ritmo pesa', fund: 'Financia el club — las cifras lo respaldan' },
  pt: { notReady: 'Ainda não — aumente primeiro a audiência', love: 'O clube paga menos do que as suas horas — lance-o por paixão, não pelo dinheiro', borderline: 'No limite — clube pequeno, comece de forma simples', thin: 'O clube paga, mas o ritmo pesa', fund: 'Financie o clube — os números apoiam a decisão' },
};

export function getMembershipFeeStackLabel(locale: string, key: string, fallback: string): string { return FEE_STACK_LABELS[languageOf(locale)]?.[key] ?? fallback; }
export function getMembershipScenarioLabel(locale: string, label: string, fallback: string): string { return MEMBERSHIP_SITE_COPY[languageOf(locale)].channels[label === 'worst' ? 'low' : label === 'best' ? 'high' : 'realistic'] ?? fallback; }
export function getMembershipFlagTitle(locale: string, code: string, fallback: string): string { return FLAG_TITLES[languageOf(locale)]?.[code] ?? fallback; }

export function getMembershipVerdict(locale: string, verdict: string): string {
  const labels = VERDICT_LABELS[languageOf(locale)];
  if (verdict.startsWith('Not ready')) return labels.notReady;
  if (verdict.startsWith('Club pays less')) return labels.love;
  if (verdict.startsWith('Borderline')) return labels.borderline;
  if (verdict.startsWith('Club pays')) return labels.thin;
  if (verdict.startsWith('Fund')) return labels.fund;
  return verdict;
}

export function getMembershipFlagDetail(locale: string, code: string, fallback: string, values: { conversion: number; audience: number; members: number; churn: number; ltv: number; fees: number; feeShare: number; net: number; hours: number; rate: number; monthlyPrice: number; annualShare: number; annualMonthly: number }): string {
  const lang = languageOf(locale);
  const n = (v: number) => number(locale, v);
  const m = (v: number) => money(locale, v);
  const templates: Record<LanguageCode, Record<string, string>> = {
    en: { 'MS-01': `At ${values.conversion * 100}% conversion of ${n(values.audience)} engaged followers you'd have ≈${n(values.members)} members. Small clubs meaningfully work from ≈30–50 members. Grow the free-audience funnel first.`, 'MS-02': `Median free-to-paid conversion is lower than this ${values.conversion * 100}% assumption. Model 3% as the realistic band before spending on acquisition.`, 'MS-03': `At ${values.churn * 100}% monthly churn a member stays ≈${n(1 / values.churn)} months, worth only ${m(values.ltv)} lifetime. Prioritize onboarding and retention before acquisition.`, 'MS-04': `Fees take ${values.feeShare.toFixed(0)}% of revenue, or ${m(values.fees)}/mo. Small monthly prices bleed hardest; compare annual pricing or a lower-overhead host.`, 'MS-05': `The club nets ${m(values.net)}/mo but ${n(values.hours)} hours at ${m(values.rate)}/hr cost more. Run the club for audience value, not unpaid hours.`, 'MS-06': `More than half of members use the annual plan at an effective ${m(values.annualMonthly)}/mo price, compressing blended revenue and flexibility.`, 'MS-07': `${n(values.members)} members at your quality bar need pattern support and moderation. Even 2–4 hours/month protects retention.` },
    de: { 'MS-01': `Bei ${values.conversion * 100}% Konversion von ${n(values.audience)} engagierten Followern hättest du etwa ${n(values.members)} Mitglieder. Baue zuerst den kostenlosen Publikumsaufbau aus.`, 'MS-02': `Die mittlere Konversion von kostenlos zu bezahlt liegt unter dieser Annahme von ${values.conversion * 100} %. Nutze 3 % als realistische Basis.`, 'MS-03': `Bei ${values.churn * 100} % monatlicher Abwanderung bleibt ein Mitglied etwa ${n(1 / values.churn)} Monate und ist ${m(values.ltv)} wert. Stärke zuerst Bindung und Einstieg.`, 'MS-04': `Gebühren verbrauchen ${values.feeShare.toFixed(0)} % des Umsatzes, also ${m(values.fees)}/Monat. Vergleiche Jahrespreise oder einen Anbieter mit geringeren Nebenkosten.`, 'MS-05': `Der Club bringt ${m(values.net)}/Monat ein, aber ${n(values.hours)} Stunden zu ${m(values.rate)}/Stunde kosten mehr. Starte ihn für den Publikumswert, nicht für unbezahlte Stunden.`, 'MS-06': `Mehr als die Hälfte nutzt den Jahresplan zum effektiven Preis von ${m(values.annualMonthly)}/Monat. Das verringert Umsatz und Flexibilität.`, 'MS-07': `${n(values.members)} Mitglieder brauchen Support und Moderation. Schon 2–4 Stunden pro Monat schützen die Bindung.` },
    fr: { 'MS-01': `Avec ${values.conversion * 100} % de conversion sur ${n(values.audience)} abonnés engagés, vous auriez environ ${n(values.members)} membres. Développez d’abord l’audience gratuite.`, 'MS-02': `La conversion médiane du gratuit au payant est inférieure à cette hypothèse de ${values.conversion * 100} %. Modélisez 3 % comme base réaliste.`, 'MS-03': `Avec ${values.churn * 100} % de churn mensuel, un membre reste environ ${n(1 / values.churn)} mois et vaut ${m(values.ltv)}. Renforcez l’accueil et la rétention.`, 'MS-04': `Les frais absorbent ${values.feeShare.toFixed(0)} % du revenu, soit ${m(values.fees)}/mois. Comparez le prix annuel ou un hébergeur moins coûteux.`, 'MS-05': `Le club rapporte ${m(values.net)}/mois, mais ${n(values.hours)} heures à ${m(values.rate)}/heure coûtent davantage. Lancez-le pour la valeur communautaire, pas pour des heures gratuites.`, 'MS-06': `Plus de la moitié des membres paient annuellement à un prix effectif de ${m(values.annualMonthly)}/mois, ce qui réduit le revenu et la flexibilité.`, 'MS-07': `${n(values.members)} membres nécessitent du support et de la modération. Même 2 à 4 heures par mois protègent la rétention.` },
    es: { 'MS-01': `Con una conversión del ${values.conversion * 100} % de ${n(values.audience)} seguidores activos tendrías unos ${n(values.members)} miembros. Aumenta primero la audiencia gratuita.`, 'MS-02': `La conversión mediana de gratuito a pago es menor que esta hipótesis del ${values.conversion * 100} %. Usa el 3 % como base realista.`, 'MS-03': `Con una baja mensual del ${values.churn * 100} %, un miembro permanece unos ${n(1 / values.churn)} meses y vale ${m(values.ltv)}. Refuerza la incorporación y la retención.`, 'MS-04': `Las comisiones consumen el ${values.feeShare.toFixed(0)} % de los ingresos, ${m(values.fees)}/mes. Compara el precio anual o un proveedor con menos costes.`, 'MS-05': `El club genera ${m(values.net)}/mes, pero ${n(values.hours)} horas a ${m(values.rate)}/hora cuestan más. Lánzalo por el valor de la comunidad, no por horas sin pagar.`, 'MS-06': `Más de la mitad usa el plan anual a un precio efectivo de ${m(values.annualMonthly)}/mes, lo que reduce ingresos y flexibilidad.`, 'MS-07': `${n(values.members)} miembros necesitan soporte y moderación. Incluso 2–4 horas al mes protegen la retención.` },
    pt: { 'MS-01': `Com ${values.conversion * 100}% de conversão de ${n(values.audience)} seguidores envolvidos, teria cerca de ${n(values.members)} membros. Aumente primeiro a audiência gratuita.`, 'MS-02': `A conversão mediana de gratuito para pago é inferior a esta hipótese de ${values.conversion * 100}%. Use 3% como base realista.`, 'MS-03': `Com churn mensal de ${values.churn * 100}%, um membro fica cerca de ${n(1 / values.churn)} meses e vale ${m(values.ltv)}. Reforce a integração e a retenção.`, 'MS-04': `As taxas consomem ${values.feeShare.toFixed(0)}% da receita, ou ${m(values.fees)}/mês. Compare preços anuais ou um fornecedor com menos custos.`, 'MS-05': `O clube rende ${m(values.net)}/mês, mas ${n(values.hours)} horas a ${m(values.rate)}/hora custam mais. Lance-o pelo valor da comunidade, não por horas não pagas.`, 'MS-06': `Mais de metade usa o plano anual ao preço efetivo de ${m(values.annualMonthly)}/mês, reduzindo receita e flexibilidade.`, 'MS-07': `${n(values.members)} membros precisam de apoio e moderação. Mesmo 2–4 horas por mês protegem a retenção.` },
  };
  return templates[lang]?.[code] ?? fallback;
}

export function getMembershipVerdictNote(locale: string, verdict: string, values: { audience: number; realisticConversion: number; members: number; net: number; monthlyCost: number; hours: number; rate: number; breakEven: number; treadmillGap: number; blended: number; feeShare: number; ltv: number }): string {
  const lang = languageOf(locale);
  const n = (v: number) => number(locale, v);
  const m = (v: number) => money(locale, v);
  const notes: Record<LanguageCode, Record<string, string>> = {
    en: { notReady: `A club monetizes the audience you already have. At ${n(values.audience)} engaged followers, even an 8% conversion is under 20 members. Build the free-pattern funnel until the audience supports ≈30+ members at a realistic 3% conversion — around ${values.breakEven === Infinity ? '∞' : n(values.breakEven)} followers for your numbers.`, love: `At realistic conversion the club nets ${m(values.net)}/mo against ${m(values.monthlyCost)} in content-hours cost — the treadmill costs ${m(Math.abs(values.treadmillGap))} more per month than selling patterns outright would pay for those hours. Launch lean if the community itself is worth it.`, borderline: `≈${n(values.members)} members at ${m(values.blended)}/mo blended nets ${m(values.net)}/mo after fees — real money, but small enough that one bad month of churn bites hard. Start monthly-only and cap the content treadmill.`, thin: `The club nets ${m(values.net)}/mo — ${m(values.treadmillGap)} over the cost of ${n(values.hours)} hours at ${m(values.rate)}/hr. The margin is thin; lengthen member lifetime before adding patterns.`, fund: `≈${n(values.members)} members at realistic conversion net ${m(values.net)}/mo after the ${values.feeShare.toFixed(0)}% fee stack — ${m(values.treadmillGap)} over content-hours cost, with ${m(values.ltv)} LTV per member. Lock annual pricing from day one.` },
    de: { notReady: `Ein Club monetarisiert dein bestehendes Publikum. Bei ${n(values.audience)} engagierten Followern bringt selbst eine Konversion von 8 % weniger als 20 Mitglieder. Baue den kostenlosen Muster-Funnel aus; für 30+ Mitglieder brauchst du etwa ${values.breakEven === Infinity ? '∞' : n(values.breakEven)} Follower.`, love: `Bei realistischer Konversion bringt der Club ${m(values.net)}/Monat gegenüber ${m(values.monthlyCost)} Stundenkosten. Starte schlank, wenn die Community selbst den Wert liefert.`, borderline: `Etwa ${n(values.members)} Mitglieder zu ${m(values.blended)}/Monat bringen nach Gebühren ${m(values.net)}/Monat. Starte zunächst nur monatlich und begrenze den Inhaltsaufwand.`, thin: `Der Club bringt ${m(values.net)}/Monat, ${m(values.treadmillGap)} über den Kosten von ${n(values.hours)} Stunden zu ${m(values.rate)}/Stunde. Stärke zuerst die Mitgliedsdauer.`, fund: `Etwa ${n(values.members)} Mitglieder bringen netto ${m(values.net)}/Monat nach ${values.feeShare.toFixed(0)} % Gebühren; das liegt ${m(values.treadmillGap)} über den Stundenkosten. Die Zahlen sprechen für den Club.` },
    fr: { notReady: `Un club monétise l’audience existante. Avec ${n(values.audience)} abonnés engagés, même 8 % de conversion donnent moins de 20 membres. Développez le tunnel gratuit jusqu’à environ ${values.breakEven === Infinity ? '∞' : n(values.breakEven)} abonnés pour atteindre 30 membres.`, love: `À conversion réaliste, le club rapporte ${m(values.net)}/mois face à ${m(values.monthlyCost)} de coût horaire. Lancez-le simplement si la communauté apporte sa propre valeur.`, borderline: `Environ ${n(values.members)} membres à ${m(values.blended)}/mois produisent ${m(values.net)}/mois après frais. Commencez au mois et limitez le rythme de contenu.`, thin: `Le club rapporte ${m(values.net)}/mois, soit ${m(values.treadmillGap)} au-dessus du coût de ${n(values.hours)} heures à ${m(values.rate)}/heure. Renforcez la durée membre avant d’ajouter des modèles.`, fund: `Environ ${n(values.members)} membres produisent ${m(values.net)}/mois net après ${values.feeShare.toFixed(0)} % de frais, soit ${m(values.treadmillGap)} au-dessus du coût horaire. Les chiffres sont favorables.` },
    es: { notReady: `Un club monetiza la audiencia que ya tienes. Con ${n(values.audience)} seguidores activos, incluso una conversión del 8 % queda por debajo de 20 miembros. Aumenta el embudo gratuito hasta unos ${values.breakEven === Infinity ? '∞' : n(values.breakEven)} seguidores para llegar a 30 miembros.`, love: `Con conversión realista el club genera ${m(values.net)}/mes frente a ${m(values.monthlyCost)} de coste horario. Empieza con poco si la comunidad aporta valor por sí misma.`, borderline: `Unos ${n(values.members)} miembros a ${m(values.blended)}/mes generan ${m(values.net)}/mes después de comisiones. Empieza solo con mensualidades y limita el ritmo de contenido.`, thin: `El club genera ${m(values.net)}/mes, ${m(values.treadmillGap)} por encima del coste de ${n(values.hours)} horas a ${m(values.rate)}/hora. Mejora la duración del miembro antes de añadir patrones.`, fund: `Unos ${n(values.members)} miembros generan ${m(values.net)}/mes netos después del ${values.feeShare.toFixed(0)} % de comisiones, ${m(values.treadmillGap)} sobre el coste horario. Las cifras lo respaldan.` },
    pt: { notReady: `Um clube monetiza a audiência existente. Com ${n(values.audience)} seguidores envolvidos, mesmo 8% de conversão dá menos de 20 membros. Aumente o funil gratuito até cerca de ${values.breakEven === Infinity ? '∞' : n(values.breakEven)} seguidores para chegar a 30 membros.`, love: `Com conversão realista, o clube rende ${m(values.net)}/mês contra ${m(values.monthlyCost)} de custo horário. Comece de forma simples se a comunidade tiver valor próprio.`, borderline: `Cerca de ${n(values.members)} membros a ${m(values.blended)}/mês geram ${m(values.net)}/mês após taxas. Comece apenas com mensalidades e limite o ritmo de conteúdo.`, thin: `O clube rende ${m(values.net)}/mês, ${m(values.treadmillGap)} acima do custo de ${n(values.hours)} horas a ${m(values.rate)}/hora. Aumente a duração dos membros antes de adicionar padrões.`, fund: `Cerca de ${n(values.members)} membros geram ${m(values.net)}/mês líquidos após ${values.feeShare.toFixed(0)}% de taxas, ${m(values.treadmillGap)} acima do custo horário. Os números apoiam a decisão.` },
  };
  const copy = notes[lang] ?? notes.en;
  if (verdict.startsWith('Not ready')) return copy.notReady;
  if (verdict.startsWith('Club pays less')) return copy.love;
  if (verdict.startsWith('Borderline')) return copy.borderline;
  if (verdict.startsWith('Club pays')) return copy.thin;
  if (verdict.startsWith('Fund')) return copy.fund;
  return verdict;
}
