import type { LanguageCode } from '@/lib/i18n';
export interface PatternClubCopy { title:string; description:string; club:string; magazine:string; soloPlatform:string; month12Net:string; soloLost:string; netVsSolo:string; membersNeeded:string; faq:string; editorReply:string; copy:string; copied:string; copyHint:string; offeredFee:string; exclusivity:string; production:string; soloCopies:string; soloPrice:string; techCovered:string; techCost:string; designHours:string; hourlyRate:string; netFee:string; incomeLost:string; minFee:string; effectiveRate:string 
  '$0FreeTrial': string;
  '$0MonthlyOnlyAnnual': string;
  '0NoneNickiS': string;
  '1StandardClubCadence': string;
  '55%ForPatreon': string;
  'afterLaunchAtYour': string;
  'citedBandKnitty$200–$300': string;
  'citedKnitty3Laine': string;
  'foundingCohortYourLaunch': string;
  'liveSessionsSupportGroup': string;
  'marketBand$5–$19Mo': string;
  'membershipClubsTypicallyChurn': string;
  'ravelryGiftCodesEmail': string;
  'samePriceInAll': string;
  'techEditLayoutPhotography': string;
  'techEditMediaIf': string;
  'usedForTheEffective': string;
  'whatThisPatternSells': string;
  'yourRealisticSteadyState': string;
}
const en:PatternClubCopy={title:'Pattern Club & Magazine Lockout',description:'Compare a club against selling the same patterns solo, then test whether a magazine fee beats the income lost during exclusivity.',club:'Pattern Club',magazine:'Magazine Offer',soloPlatform:'Solo platform',month12Net:'Month-12 club net',soloLost:'Solo income lost / mo',netVsSolo:'Net vs selling solo',membersNeeded:'Steady-state members needed',faq:'Paste-ready club FAQ',editorReply:'Paste-ready reply to the editor',copy:'Copy',copied:'Copied',copyHint:'Ready to paste wherever you need it.',offeredFee:'Offered fee ($)',exclusivity:'Exclusivity window (months)',production:'Pattern production you pay ($)',soloCopies:'Pattern sells solo (copies/mo)',soloPrice:'Solo price ($)',techCovered:'Publisher covers tech editing',techCost:'Your tech-edit cost ($) if not covered',designHours:'Design hours',hourlyRate:'Your hourly rate ($/hr)',netFee:'Net fee (after your costs)',incomeLost:'Income lost in the window',minFee:'Minimum fee worth accepting',effectiveRate:'Effective rate / hour','$0FreeTrial': '$0 = free trial.','$0MonthlyOnlyAnnual': '$0 = monthly only. Annual ≈ 2× monthly is the market norm ($77/yr on $7/mo).','0NoneNickiS': '0 = none; Nicki\'s runs 7-day trials, clubs often offer one free month.','1StandardClubCadence': '1 = standard club cadence.','55%ForPatreon': '5 = 5% for Patreon/Payhip-style billing.',afterLaunchAtYour: 'After launch, at your current marketing effort.','citedBandKnitty$200–$300': 'Cited band: Knitty $200–$300, Farm & Fiber $200–$750 by garment size.',citedKnitty3Laine: 'Cited: Knitty ~3, Laine 5, I Like Knitting 6, Farm & Fiber 12.',foundingCohortYourLaunch: 'Founding cohort — your launch list, realistically.',liveSessionsSupportGroup: 'Live sessions, support, group moderation — $0 if none.','marketBand$5–$19Mo': 'Market band: $5–$19/mo (Double The Stitches $7, Crochet Spot $10).',membershipClubsTypicallyChurn: 'Membership clubs typically churn 5–15%/mo.',ravelryGiftCodesEmail: 'Ravelry gift codes + email copy per member per pattern.',samePriceInAll: 'Same price in all languages.',techEditLayoutPhotography: 'Tech edit + layout + photography, outsourced or your valued time.',techEditMediaIf: 'Tech edit + media if the publisher doesn\'t cover them.',usedForTheEffective: 'Used for the effective rate check.',whatThisPatternSells: 'What this pattern sells per month if you don\'t put it in the club.',yourRealisticSteadyState: 'Your realistic steady state after the window ends.',};
const de:PatternClubCopy={...en,title:'Musterclub & Magazinsperre',description:'Vergleiche einen Club mit dem Einzelverkauf und prüfe, ob ein Magazinangebot den Einkommensverlust während der Exklusivität ausgleicht.',club:'Musterclub',magazine:'Magazinangebot',soloPlatform:'Einzelplattform',month12Net:'Club-Netto im 12. Monat',soloLost:'Verlorenes Einzelverkaufs-Einkommen/Monat',netVsSolo:'Netto gegenüber Einzelverkauf',membersNeeded:'Benötigte Mitglieder im Dauerbetrieb',faq:'Club-FAQ zum Einfügen',editorReply:'Antwort an die Redaktion zum Einfügen',copied:'Kopiert',copyHint:'Bereit zum Einfügen.',offeredFee:'Angebotene Gebühr ($)',exclusivity:'Exklusivitätszeitraum (Monate)',production:'Von dir bezahlte Musterproduktion ($)',soloCopies:'Muster-Einzelverkäufe (Exemplare/Monat)',soloPrice:'Einzelpreis ($)',techCovered:'Verlag übernimmt technische Bearbeitung',techCost:'Deine Kosten für technische Bearbeitung',designHours:'Designstunden',hourlyRate:'Dein Stundensatz ($/Std.)',netFee:'Netto-Gebühr (nach Kosten)',incomeLost:'Einkommensverlust im Zeitraum',minFee:'Mindestens akzeptable Gebühr',effectiveRate:'Effektiver Stundensatz','$0FreeTrial': '0 $ = kostenlose Probezeit.','$0MonthlyOnlyAnnual': '0 $ = nur monatlich. Jahresabo ≈ 2× monatlich ist die Marktnorm (77 $/Jahr bei 7 $/Monat).','0NoneNickiS': '0 = keine; Nicki’s bietet 7-Tage-Testläufe, Clubs geben oft einen Gratismonat.','1StandardClubCadence': '1 = Standard-Club-Rhythmus.','55%ForPatreon': '5 = 5 % für Patreon/Payhip-ähnliche Abrechnung.',afterLaunchAtYour: 'Nach dem Launch, mit deinem aktuellen Marketingaufwand.','citedBandKnitty$200–$300': 'Zitierte Spanne: Knitty 200–300 $, Farm & Fiber 200–750 $ je nach Kleidungsstück.',citedKnitty3Laine: 'Zitiert: Knitty ~3, Laine 5, I Like Knitting 6, Farm & Fiber 12.',foundingCohortYourLaunch: 'Gründungskohorte — realistisch deine Launch-Liste.',liveSessionsSupportGroup: 'Live-Sessions, Support, Gruppenmoderation — 0 $, falls nicht vorhanden.','marketBand$5–$19Mo': 'Marktspanne: 5–19 $/Monat (Double The Stitches 7 $, Crochet Spot 10 $).',membershipClubsTypicallyChurn: 'Mitglieder-Clubs verlieren typischerweise 5–15 %/Monat.',ravelryGiftCodesEmail: 'Ravelry-Geschenkcodes + E-Mail-Texte je Mitglied je Muster.',samePriceInAll: 'Gleicher Preis in allen Sprachen.',techEditLayoutPhotography: 'Technische Bearbeitung + Layout + Fotografie, outsourced oder deine wertvolle Zeit.',techEditMediaIf: 'Technische Bearbeitung + Medien, falls der Verlag sie nicht übernimmt.',usedForTheEffective: 'Wird für die Prüfung des effektiven Stundensatzes verwendet.',whatThisPatternSells: 'Was dieses Muster pro Monat verkauft, wenn es nicht im Club ist.',yourRealisticSteadyState: 'Dein realistischer Gleichgewichtszustand nach Ablauf des Fensters.',};
const fr:PatternClubCopy={...en,title:'Club de patrons et exclusivité magazine',description:'Comparez un club à la vente individuelle, puis vérifiez si l’offre d’un magazine compense le revenu perdu pendant l’exclusivité.',club:'Club de patrons',magazine:'Offre magazine',soloPlatform:'Plateforme individuelle',month12Net:'Net du club au 12e mois',soloLost:'Revenu individuel perdu/mois',netVsSolo:'Net par rapport à la vente individuelle',membersNeeded:'Membres nécessaires en régime établi',faq:'FAQ du club prête à coller',editorReply:'Réponse à la rédaction prête à coller',copied:'Copié',copyHint:'Prêt à être collé.',offeredFee:'Rémunération proposée ($)',exclusivity:'Période d’exclusivité (mois)',production:'Production du patron à votre charge ($)',soloCopies:'Ventes individuelles (exemplaires/mois)',soloPrice:'Prix individuel ($)',techCovered:'L’éditeur couvre la correction technique',techCost:'Votre coût de correction technique',designHours:'Heures de création',hourlyRate:'Votre tarif horaire ($/h)',netFee:'Rémunération nette (après coûts)',incomeLost:'Revenu perdu pendant la période',minFee:'Rémunération minimale acceptable',effectiveRate:'Tarif effectif par heure','$0FreeTrial': '0 $ = essai gratuit.','$0MonthlyOnlyAnnual': '0 $ = mensuel uniquement. L’annuel ≈ 2× le mensuel est la norme du marché (77 $/an sur 7 $/mois).','0NoneNickiS': '0 = aucun ; Nicki’s propose des essais de 7 jours, les clubs offrent souvent un mois gratuit.','1StandardClubCadence': '1 = cadence standard de club.','55%ForPatreon': '5 = 5 % pour la facturation type Patreon/Payhip.',afterLaunchAtYour: 'Après le lancement, à votre effort marketing actuel.','citedBandKnitty$200–$300': 'Fourchette citée : Knitty 200–300 $, Farm & Fiber 200–750 $ selon le vêtement.',citedKnitty3Laine: 'Cité : Knitty ~3, Laine 5, I Like Knitting 6, Farm & Fiber 12.',foundingCohortYourLaunch: 'Cohorte fondatrice — en pratique, votre liste de lancement.',liveSessionsSupportGroup: 'Sessions en direct, support, modération de groupe — 0 $ si aucun.','marketBand$5–$19Mo': 'Fourchette du marché : 5–19 $/mois (Double The Stitches 7 $, Crochet Spot 10 $).',membershipClubsTypicallyChurn: 'Les clubs membres perdent typiquement 5–15 %/mois.',ravelryGiftCodesEmail: 'Codes cadeaux Ravelry + texte d’email par membre par patron.',samePriceInAll: 'Même prix dans toutes les langues.',techEditLayoutPhotography: 'Correction technique + mise en page + photographie, externalisée ou votre temps valorisé.',techEditMediaIf: 'Correction technique + médias si l’éditeur ne les couvre pas.',usedForTheEffective: 'Utilisé pour la vérification du taux effectif.',whatThisPatternSells: 'Ce que ce patron vend par mois si vous ne le mettez pas dans le club.',yourRealisticSteadyState: 'Votre état stable réaliste après la fin de la fenêtre.',};
const es:PatternClubCopy={...en,title:'Club de patrones y bloqueo editorial',description:'Compara un club con vender los mismos patrones por separado y comprueba si la oferta editorial compensa el ingreso perdido durante la exclusividad.',club:'Club de patrones',magazine:'Oferta editorial',soloPlatform:'Plataforma individual',month12Net:'Neto del club en el mes 12',soloLost:'Ingreso individual perdido/mes',netVsSolo:'Neto frente a vender por separado',membersNeeded:'Miembros necesarios en régimen estable',faq:'Preguntas frecuentes listas para pegar',editorReply:'Respuesta a la editorial lista para pegar',copied:'Copiado',copyHint:'Listo para pegar.',offeredFee:'Pago ofrecido ($)',exclusivity:'Periodo de exclusividad (meses)',production:'Producción del patrón a tu cargo ($)',soloCopies:'Ventas individuales (copias/mes)',soloPrice:'Precio individual ($)',techCovered:'La editorial cubre la edición técnica',techCost:'Tu coste de edición técnica',designHours:'Horas de diseño',hourlyRate:'Tu tarifa por hora ($/h)',netFee:'Pago neto (después de costes)',incomeLost:'Ingreso perdido durante el periodo',minFee:'Pago mínimo aceptable',effectiveRate:'Tarifa efectiva por hora','$0FreeTrial': '$0 = prueba gratuita.','$0MonthlyOnlyAnnual': '$0 = solo mensual. El anual ≈ 2× mensual es la norma del mercado ($77/año sobre $7/mes).','0NoneNickiS': '0 = ninguno; Nicki’s corre pruebas de 7 días, los clubs suelen ofrecer un mes gratis.','1StandardClubCadence': '1 = cadencia estándar de club.','55%ForPatreon': '5 = 5% para facturación tipo Patreon/Payhip.',afterLaunchAtYour: 'Después del lanzamiento, con tu esfuerzo de marketing actual.','citedBandKnitty$200–$300': 'Banda citada: Knitty $200–$300, Farm & Fiber $200–$750 por tamaño de prenda.',citedKnitty3Laine: 'Citado: Knitty ~3, Laine 5, I Like Knitting 6, Farm & Fiber 12.',foundingCohortYourLaunch: 'Cohorte fundadora — realisticamente, tu lista de lanzamiento.',liveSessionsSupportGroup: 'Sesiones en vivo, soporte, moderación del grupo — $0 si no hay.','marketBand$5–$19Mo': 'Banda de mercado: $5–$19/mes (Double The Stitches $7, Crochet Spot $10).',membershipClubsTypicallyChurn: 'Los clubs de membresía típicamente tienen 5–15%/mes de abandono.',ravelryGiftCodesEmail: 'Códigos de regalo de Ravelry + texto de email por miembro por patrón.',samePriceInAll: 'Mismo precio en todos los idiomas.',techEditLayoutPhotography: 'Edición técnica + maquetación + fotografía, externalizada o tu tiempo valorado.',techEditMediaIf: 'Edición técnica + medios si la editorial no los cubre.',usedForTheEffective: 'Se usa para la verificación de la tasa efectiva.',whatThisPatternSells: 'Lo que este patrón vende al mes si no lo pones en el club.',yourRealisticSteadyState: 'Tu estado estable realista después de que termina la ventana.',};
const pt:PatternClubCopy={...en,title:'Clube de padrões e exclusividade editorial',description:'Compare um clube com a venda individual e verifique se a oferta de uma revista compensa o rendimento perdido durante a exclusividade.',club:'Clube de padrões',magazine:'Oferta editorial',soloPlatform:'Plataforma individual',month12Net:'Líquido do clube no mês 12',soloLost:'Rendimento individual perdido/mês',netVsSolo:'Líquido face à venda individual',membersNeeded:'Membros necessários em regime estável',faq:'FAQ do clube pronta a colar',editorReply:'Resposta à redação pronta a colar',copied:'Copiado',copyHint:'Pronto a colar.',offeredFee:'Valor oferecido ($)',exclusivity:'Período de exclusividade (meses)',production:'Produção do padrão paga por si ($)',soloCopies:'Vendas individuais (cópias/mês)',soloPrice:'Preço individual ($)',techCovered:'A editora cobre a revisão técnica',techCost:'Custo da sua revisão técnica',designHours:'Horas de design',hourlyRate:'O seu valor por hora ($/h)',netFee:'Valor líquido (após custos)',incomeLost:'Rendimento perdido no período',minFee:'Valor mínimo aceitável',effectiveRate:'Valor efetivo por hora','$0FreeTrial': '$0 = teste gratuito.','$0MonthlyOnlyAnnual': '$0 = apenas mensal. O anual ≈ 2× mensal é a norma do mercado ($77/ano sobre $7/mês).','0NoneNickiS': '0 = nenhum; o Nicki’s faz testes de 7 dias, os clubes costumam oferecer um mês grátis.','1StandardClubCadence': '1 = cadência padrão de clube.','55%ForPatreon': '5 = 5% para faturação tipo Patreon/Payhip.',afterLaunchAtYour: 'Após o lançamento, com o seu esforço de marketing atual.','citedBandKnitty$200–$300': 'Banda citada: Knitty $200–$300, Farm & Fiber $200–$750 por tamanho de peça.',citedKnitty3Laine: 'Citado: Knitty ~3, Laine 5, I Like Knitting 6, Farm & Fiber 12.',foundingCohortYourLaunch: 'Coorte fundadora — realisticamente, a sua lista de lançamento.',liveSessionsSupportGroup: 'Sessões ao vivo, suporte, moderação do grupo — $0 se não houver.','marketBand$5–$19Mo': 'Banda de mercado: $5–$19/mês (Double The Stitches $7, Crochet Spot $10).',membershipClubsTypicallyChurn: 'Os clubes de membros tipicamente perdem 5–15%/mês.',ravelryGiftCodesEmail: 'Códigos de oferta Ravelry + texto de email por membro por padrão.',samePriceInAll: 'Mesmo preço em todos os idiomas.',techEditLayoutPhotography: 'Revisão técnica + layout + fotografia, terceirizada ou o seu tempo valorizado.',techEditMediaIf: 'Revisão técnica + media se a editora não os cobrir.',usedForTheEffective: 'Usado para a verificação da taxa efetiva.',whatThisPatternSells: 'O que este padrão vende por mês se não o colocar no clube.',yourRealisticSteadyState: 'O seu estado estável realista após o fim da janela.',};
export const COPY:Record<LanguageCode,PatternClubCopy>={en,de,fr,es,pt};

export const PATTERN_CLUB_COPY = COPY;
