import type { LanguageCode } from '@/lib/i18n';

export interface PatternDraftCopy {
  title: string; description: string; saved: string; savedHint: string; copied: string; copiedHint: string; copyBlocked: string; copyBlockedHint: string; loadSample: string; placeholder: string; hidePreview: string; showPreview: string; save: string; copyPattern: string; footer: string;
}

const en: PatternDraftCopy = { title:'Pattern Draft', description:'Write your pattern in plain text. Placeholders resolve live against your grading tables — change a measurement and the pattern updates with it.', saved:'Draft saved locally', savedHint:'It reopens with your project.', copied:'Pattern text copied', copiedHint:'Paste it into Ravelry, Etsy, or your tech editor.', copyBlocked:'Copy blocked', copyBlockedHint:'Your browser blocked clipboard access.', loadSample:'Load sample draft', placeholder:'Start typing your pattern text… e.g. Work {Size.XS.bust.stitch} sts across.', hidePreview:'Hide preview', showPreview:'Show preview', save:'Save Draft', copyPattern:'Copy Pattern', footer:'Numbers are computed from your live grading tables — never typed twice, never out of sync.' };
const de: PatternDraftCopy = { ...en, title:'Musterentwurf', description:'Schreibe dein Muster als Text. Platzhalter werden live aus deinen Größentabellen aufgelöst — ändere ein Maß und das Muster aktualisiert sich.', saved:'Entwurf lokal gespeichert', savedHint:'Er wird mit deinem Projekt wieder geöffnet.', copied:'Mustertext kopiert', copiedHint:'Füge ihn in Ravelry, Etsy oder deinen technischen Editor ein.', copyBlocked:'Kopieren blockiert', copyBlockedHint:'Dein Browser hat den Zugriff auf die Zwischenablage blockiert.', loadSample:'Beispielentwurf laden', placeholder:'Beginne mit deinem Mustertext … z. B. {Size.XS.bust.stitch} Maschen anschlagen.', hidePreview:'Vorschau ausblenden', showPreview:'Vorschau anzeigen', save:'Entwurf speichern', copyPattern:'Muster kopieren', footer:'Zahlen werden aus deinen Live-Größentabellen berechnet — nie doppelt eingegeben, nie veraltet.' };
const fr: PatternDraftCopy = { ...en, title:'Brouillon de patron', description:'Rédigez votre patron en texte brut. Les espaces réservés suivent vos tableaux de tailles — modifiez une mesure et le patron se met à jour.', saved:'Brouillon enregistré localement', savedHint:'Il se rouvrira avec votre projet.', copied:'Texte du patron copié', copiedHint:'Collez-le dans Ravelry, Etsy ou votre éditeur technique.', copyBlocked:'Copie bloquée', copyBlockedHint:'Votre navigateur a bloqué l’accès au presse-papiers.', loadSample:'Charger un brouillon exemple', placeholder:'Commencez à rédiger votre patron… par ex. tricotez {Size.XS.bust.stitch} mailles.', hidePreview:'Masquer l’aperçu', showPreview:'Afficher l’aperçu', save:'Enregistrer le brouillon', copyPattern:'Copier le patron', footer:'Les nombres viennent de vos tableaux de tailles — jamais saisis deux fois, jamais désynchronisés.' };
const es: PatternDraftCopy = { ...en, title:'Borrador del patrón', description:'Escribe tu patrón en texto plano. Los marcadores se actualizan con tus tablas de tallas — cambia una medida y el patrón también cambia.', saved:'Borrador guardado localmente', savedHint:'Se abrirá de nuevo con tu proyecto.', copied:'Texto del patrón copiado', copiedHint:'Pégalo en Ravelry, Etsy o tu editor técnico.', copyBlocked:'Copia bloqueada', copyBlockedHint:'Tu navegador bloqueó el acceso al portapapeles.', loadSample:'Cargar borrador de ejemplo', placeholder:'Empieza a escribir tu patrón… p. ej., trabaja {Size.XS.bust.stitch} puntos.', hidePreview:'Ocultar vista previa', showPreview:'Mostrar vista previa', save:'Guardar borrador', copyPattern:'Copiar patrón', footer:'Los números se calculan con tus tablas de tallas — nunca se escriben dos veces ni quedan desfasados.' };
const pt: PatternDraftCopy = { ...en, title:'Rascunho do padrão', description:'Escreva o seu padrão em texto simples. Os marcadores acompanham as tabelas de tamanhos — altere uma medida e o padrão atualiza-se.', saved:'Rascunho guardado localmente', savedHint:'Será reaberto com o seu projeto.', copied:'Texto do padrão copiado', copiedHint:'Cole-o no Ravelry, Etsy ou no seu editor técnico.', copyBlocked:'Cópia bloqueada', copyBlockedHint:'O navegador bloqueou o acesso à área de transferência.', loadSample:'Carregar rascunho de exemplo', placeholder:'Comece a escrever o padrão… por ex., trabalhe {Size.XS.bust.stitch} malhas.', hidePreview:'Ocultar pré-visualização', showPreview:'Mostrar pré-visualização', save:'Guardar rascunho', copyPattern:'Copiar padrão', footer:'Os números são calculados nas suas tabelas de tamanhos — nunca são introduzidos duas vezes nem ficam desatualizados.' };

export const COPY: Record<LanguageCode, PatternDraftCopy> = { en, de, fr, es, pt };

export const PATTERN_DRAFT_COPY = COPY;
