import type { LanguageCode } from '@/lib/i18n';

export interface PaybackCopy {
  title: string; description: string; empty: string; designLedger: string; receiptLab: string;
  rateLabel: string; rateAria: string; apply: string; rateTip: (rate: number) => string;
  totalInvested: string; totalNet: string; paidBack: string; noCosts: string;
  all: string; winners: string; recouping: string; localFirst: string;
  paidBackBadge: string; recoupingBadge: string; bleedingBadge: string; noNet: string;
  invested: string; netEarned: string; copiesSold: string; avgNet: string;
  needs: (copies: string) => string; netSalesAtAverage: string; outOfPocket: string; overhead: string; timeCost: string;
  aheadBy: string; deficit: string; costCopies: string; costOnly: string; monthsSinceSale: string; lastSale: string;
  whatIf: string; plus10: (projected: string, current: string) => string; plus20: (projected: string, current: string) => string;
  staleSale: (months: number) => string; designHours: string;
}

const en: PaybackCopy = {
  title: 'Payback Lab', description: 'Your time has a price. This lab counts every pound, dollar and hour you put into a pattern — and tells you the exact moment it pays you back.', empty: 'Nothing to recoup yet. Add designs and costs in the Design Ledger tab and record sales in the Receipt Lab — this lab watches them both and updates automatically.', designLedger: 'Design Ledger', receiptLab: 'Receipt Lab', rateLabel: 'Your hourly rate (currency/hour)', rateAria: 'Hourly rate', apply: 'Apply', rateTip: (rate) => `Tip: even ${rate}/h is honest — your skill took years to build.`, totalInvested: 'Total invested', totalNet: 'Total net earned', paidBack: 'Patterns paid back', noCosts: 'No pattern has recorded costs or sales yet.', all: 'All patterns', winners: 'Winners', recouping: 'Recouping', localFirst: 'Local-first: everything is computed from your Design Ledger and Receipt Lab data on this device. No cloud, no subscription, no guesswork — just the math of when your work pays you back.', paidBackBadge: 'Paid back', recoupingBadge: 'Recouping', bleedingBadge: 'Bleeding', noNet: 'No net on sales yet', invested: 'Invested', netEarned: 'Net earned', copiesSold: 'Copies sold', avgNet: 'Avg net / sale', needs: (copies) => `Needs ${copies} net sales to recoup`, netSalesAtAverage: 'Needs ∞ net sales at this average', outOfPocket: 'Out of pocket', overhead: 'Overhead share', timeCost: 'Time cost', aheadBy: 'Ahead by', deficit: 'Still in deficit', costCopies: 'Cost-only copies', costOnly: 'recovers out-of-pocket only', monthsSinceSale: 'Months since last sale', lastSale: 'last sale', whatIf: 'What-if: price the pattern higher', plus10: (projected, current) => `+10% net → recoup in ${projected} copies (was ${current})`, plus20: (projected, current) => `+20% net → recoup in ${projected} copies (was ${current})`, staleSale: (months) => `No sale in ${months} months — the Promo Lab and Re-Price Lab can give this pattern a second life.`, designHours: 'Design hours (knitting + writing + revising)'
};
const de: PaybackCopy = { ...en, title:'Amortisations-Labor', description:'Deine Zeit hat einen Wert. Dieses Labor zählt jedes Pfund, jeden Euro und jede Stunde, die du in ein Muster steckst — und zeigt dir genau, wann es sich amortisiert.', empty:'Noch nichts zu amortisieren. Füge Designs und Kosten im Design-Ledger hinzu und erfasse Verkäufe im Beleg-Labor — dieses Labor beobachtet beide und aktualisiert sich automatisch.', designLedger:'Design-Ledger', receiptLab:'Beleg-Labor', rateLabel:'Dein Stundenwert (Währung/Stunde)', rateAria:'Stundenwert', apply:'Anwenden', rateTip:(rate)=>`Tipp: Selbst ${rate}/Std. ist ehrlich — deine Fähigkeiten wurden über Jahre aufgebaut.`, totalInvested:'Gesamt investiert', totalNet:'Gesamter Nettoerlös', paidBack:'Amortisierte Muster', noCosts:'Für kein Muster sind bisher Kosten oder Verkäufe erfasst.', all:'Alle Muster', winners:'Gewinner', recouping:'Amortisierung', localFirst:'Lokal zuerst: Alles wird auf diesem Gerät aus deinen Design- und Belegdaten berechnet. Keine Cloud, kein Abo, keine Schätzung — nur die Rechnung, wann sich deine Arbeit auszahlt.', paidBackBadge:'Amortisiert', recoupingBadge:'Amortisiert sich', bleedingBadge:'Verlust', noNet:'Noch kein Nettoerlös', invested:'Investiert', netEarned:'Nettoerlös', copiesSold:'Verkaufte Exemplare', avgNet:'Durchschn. netto / Verkauf', needs:(copies)=>`Benötigt ${copies} Nettoverkäufe zur Amortisierung`, netSalesAtAverage:'Bei diesem Durchschnitt sind ∞ Nettoverkäufe nötig', outOfPocket:'Direkte Kosten', overhead:'Gemeinkostenanteil', timeCost:'Zeitkosten', aheadBy:'Überschuss', deficit:'Noch im Defizit', costCopies:'Nur-Kosten-Exemplare', costOnly:'decken nur direkte Kosten', monthsSinceSale:'Monate seit letztem Verkauf', lastSale:'letzter Verkauf', whatIf:'Was wäre, wenn: Musterpreis erhöhen', plus10:(p,c)=>`+10 % netto → Amortisierung in ${p} Exemplaren (bisher ${c})`, plus20:(p,c)=>`+20 % netto → Amortisierung in ${p} Exemplaren (bisher ${c})`, staleSale:(m)=>`Seit ${m} Monaten kein Verkauf — Promo- und Re-Preis-Labor können diesem Muster ein zweites Leben geben.`, designHours:'Designstunden (Stricken + Schreiben + Überarbeiten)' };
const fr: PaybackCopy = { ...en, title:'Laboratoire de rentabilisation', description:'Votre temps a une valeur. Ce laboratoire compte chaque livre, euro et heure consacrés à un patron — et indique le moment exact où il devient rentable.', empty:'Rien à rentabiliser pour l’instant. Ajoutez les créations et coûts dans le registre des créations et les ventes dans le laboratoire des reçus — les deux sont suivis automatiquement.', designLedger:'Registre des créations', receiptLab:'Laboratoire des reçus', rateLabel:'Votre taux horaire (devise/heure)', rateAria:'Taux horaire', apply:'Appliquer', rateTip:(rate)=>`Conseil : même ${rate}/h est honnête — votre savoir-faire a demandé des années.`, totalInvested:'Total investi', totalNet:'Total net gagné', paidBack:'Patrons rentabilisés', noCosts:'Aucun patron n’a encore enregistré de coûts ou de ventes.', all:'Tous les patrons', winners:'Rentables', recouping:'En rentabilisation', localFirst:'Local d’abord : tout est calculé sur cet appareil à partir de vos données du registre des créations et des reçus. Pas de cloud, pas d’abonnement, pas de devinette — seulement le calcul de rentabilité.', paidBackBadge:'Rentabilisé', recoupingBadge:'En rentabilisation', bleedingBadge:'En perte', noNet:'Pas encore de net sur les ventes', invested:'Investi', netEarned:'Net gagné', copiesSold:'Exemplaires vendus', avgNet:'Net moyen / vente', needs:(copies)=>`Il faut ${copies} ventes nettes pour rentabiliser`, netSalesAtAverage:'Il faudrait ∞ ventes nettes à cette moyenne', outOfPocket:'Dépenses directes', overhead:'Part des frais généraux', timeCost:'Coût du temps', aheadBy:'Excédent', deficit:'Encore déficitaire', costCopies:'Exemplaires pour les coûts', costOnly:'couvrent seulement les dépenses directes', monthsSinceSale:'Mois depuis la dernière vente', lastSale:'dernière vente', whatIf:'Et si : augmenter le prix du patron', plus10:(p,c)=>`+10 % net → rentabilité en ${p} exemplaires (contre ${c})`, plus20:(p,c)=>`+20 % net → rentabilité en ${p} exemplaires (contre ${c})`, staleSale:(m)=>`Aucune vente depuis ${m} mois — les laboratoires Promo et Re-tarification peuvent relancer ce patron.`, designHours:'Heures de création (tricot + rédaction + révision)' };
const es: PaybackCopy = { ...en, title:'Laboratorio de recuperación', description:'Tu tiempo tiene un precio. Este laboratorio cuenta cada libra, dólar y hora que inviertes en un patrón y te indica el momento exacto en que se recupera.', empty:'Aún no hay nada que recuperar. Añade diseños y costes en el Libro de diseños y registra ventas en el Laboratorio de recibos; ambos se actualizan automáticamente.', designLedger:'Libro de diseños', receiptLab:'Laboratorio de recibos', rateLabel:'Tu tarifa por hora (moneda/hora)', rateAria:'Tarifa por hora', apply:'Aplicar', rateTip:(rate)=>`Consejo: incluso ${rate}/h es honesto; tu habilidad tardó años en construirse.`, totalInvested:'Total invertido', totalNet:'Total neto ganado', paidBack:'Patrones recuperados', noCosts:'Ningún patrón tiene costes o ventas registrados todavía.', all:'Todos los patrones', winners:'Ganadores', recouping:'Recuperando', localFirst:'Local primero: todo se calcula en este dispositivo con los datos de tu Libro de diseños y Laboratorio de recibos. Sin nube, sin suscripción y sin conjeturas: solo las matemáticas de cuándo se recupera tu trabajo.', paidBackBadge:'Recuperado', recoupingBadge:'Recuperando', bleedingBadge:'En pérdida', noNet:'Aún sin neto en ventas', invested:'Invertido', netEarned:'Neto ganado', copiesSold:'Copias vendidas', avgNet:'Neto medio / venta', needs:(copies)=>`Necesita ${copies} ventas netas para recuperarse`, netSalesAtAverage:'Necesita ∞ ventas netas con esta media', outOfPocket:'Coste directo', overhead:'Parte de gastos generales', timeCost:'Coste del tiempo', aheadBy:'Superávit', deficit:'Aún en déficit', costCopies:'Copias solo de costes', costOnly:'recuperan solo el coste directo', monthsSinceSale:'Meses desde la última venta', lastSale:'última venta', whatIf:'Qué pasaría: subir el precio del patrón', plus10:(p,c)=>`+10 % neto → recuperación en ${p} copias (antes ${c})`, plus20:(p,c)=>`+20 % neto → recuperación en ${p} copias (antes ${c})`, staleSale:(m)=>`Sin ventas en ${m} meses; los laboratorios de Promoción y Reprecio pueden darle una segunda vida al patrón.`, designHours:'Horas de diseño (tejer + escribir + revisar)' };
const pt: PaybackCopy = { ...en, title:'Laboratório de retorno', description:'O seu tempo tem um preço. Este laboratório conta cada libra, euro e hora investidos num padrão — e indica o momento exato em que ele se paga.', empty:'Ainda não há nada a recuperar. Adicione designs e custos no Registo de designs e registe vendas no Laboratório de recibos — ambos são acompanhados e atualizados automaticamente.', designLedger:'Registo de designs', receiptLab:'Laboratório de recibos', rateLabel:'A sua taxa horária (moeda/hora)', rateAria:'Taxa horária', apply:'Aplicar', rateTip:(rate)=>`Dica: até ${rate}/h é honesto — a sua competência levou anos a construir.`, totalInvested:'Total investido', totalNet:'Total líquido ganho', paidBack:'Padrões recuperados', noCosts:'Ainda não há custos ou vendas registados para nenhum padrão.', all:'Todos os padrões', winners:'Vencedores', recouping:'A recuperar', localFirst:'Local primeiro: tudo é calculado neste dispositivo a partir dos dados do Registo de designs e do Laboratório de recibos. Sem nuvem, sem subscrição, sem palpites — apenas a matemática de quando o seu trabalho se paga.', paidBackBadge:'Recuperado', recoupingBadge:'A recuperar', bleedingBadge:'Em perda', noNet:'Ainda sem líquido nas vendas', invested:'Investido', netEarned:'Líquido ganho', copiesSold:'Cópias vendidas', avgNet:'Líquido médio / venda', needs:(copies)=>`Precisa de ${copies} vendas líquidas para recuperar`, netSalesAtAverage:'Precisa de ∞ vendas líquidas nesta média', outOfPocket:'Custo direto', overhead:'Parte dos custos gerais', timeCost:'Custo do tempo', aheadBy:'Excedente', deficit:'Ainda em défice', costCopies:'Cópias só de custos', costOnly:'recuperam apenas o custo direto', monthsSinceSale:'Meses desde a última venda', lastSale:'última venda', whatIf:'E se: aumentar o preço do padrão', plus10:(p,c)=>`+10% líquido → recuperação em ${p} cópias (antes ${c})`, plus20:(p,c)=>`+20% líquido → recuperação em ${p} cópias (antes ${c})`, staleSale:(m)=>`Sem vendas há ${m} meses — os Laboratórios de Promoção e Repreço podem dar uma segunda vida a este padrão.`, designHours:'Horas de design (tricotar + escrever + rever)' };
export const COPY: Record<LanguageCode, PaybackCopy> = { en, de, fr, es, pt };

export const PAYBACK_COPY = COPY;
