import type { LanguageCode } from '@/lib/i18n';
export interface PlatformMixCopy { title:string; description:string; copied:string; copyFailed:string; sales:string; price:string; rate:string; hours:string; international:string; offsite:string; gross:string; fees:string; maintenance:string; net:string }
const en={title:'Platform Mix Planner',description:'Every listing is a maintenance bill. Model your monthly mix net of each platform’s fees, maintenance hours, offsite ads, and VAT administration.',copied:'Copied — paste it into your notes or planning document.',copyFailed:'Copy failed — select the text manually.',sales:'Monthly sales (all platforms)',price:'Average pattern price ($)',rate:'Your design rate ($/hr)',hours:'Marketing hours / month',international:'International sales (%)',offsite:'Charge Etsy offsite ads (15%) — mandatory once you cross $10k/yr',gross:'Gross / mo',fees:'Fees & ads',maintenance:'Maintenance',net:'Net after all of it'};
const de={...en,title:'Plattform-Mix-Planer',description:'Jedes Angebot verursacht Pflegeaufwand. Berechne deinen Monatsmix nach Plattformgebühren, Pflegezeit, Offsite-Werbung und Mehrwertsteuerverwaltung.',copied:'Kopiert — in Notizen oder Planungsdokument einfügen.',copyFailed:'Kopieren fehlgeschlagen — Text manuell auswählen.',sales:'Monatliche Verkäufe (alle Plattformen)',price:'Durchschnittspreis des Musters ($)',rate:'Dein Designsatz ($/Std.)',hours:'Marketingstunden/Monat',international:'Internationale Verkäufe (%)',offsite:'Etsy-Offsite-Werbung berechnen (15 %) — ab 10.000 $/Jahr verpflichtend',gross:'Brutto/Monat',fees:'Gebühren & Werbung',maintenance:'Pflege',net:'Netto nach allem'};
const fr={...en,title:'Planificateur de mix des plateformes',description:'Chaque annonce demande du suivi. Modélisez votre mix mensuel après frais, heures de maintenance, publicité externe et administration de TVA.',copied:'Copié — collez-le dans vos notes ou votre document de planification.',copyFailed:'Échec de la copie — sélectionnez le texte manuellement.',sales:'Ventes mensuelles (toutes plateformes)',price:'Prix moyen du patron ($)',rate:'Votre tarif de création ($/h)',hours:'Heures marketing/mois',international:'Ventes internationales (%)',offsite:'Facturer la publicité externe Etsy (15 %) — obligatoire au-delà de 10 000 $/an',gross:'Brut/mois',fees:'Frais et publicités',maintenance:'Maintenance',net:'Net après tout'};
const es={...en,title:'Planificador de mezcla de plataformas',description:'Cada anuncio requiere mantenimiento. Modela tu mezcla mensual después de comisiones, horas de mantenimiento, anuncios externos y gestión del IVA.',copied:'Copiado — pégalo en tus notas o documento de planificación.',copyFailed:'No se pudo copiar — selecciona el texto manualmente.',sales:'Ventas mensuales (todas las plataformas)',price:'Precio medio del patrón ($)',rate:'Tu tarifa de diseño ($/h)',hours:'Horas de marketing/mes',international:'Ventas internacionales (%)',offsite:'Cobrar anuncios externos de Etsy (15 %) — obligatorio al superar 10.000 $/año',gross:'Bruto/mes',fees:'Comisiones y anuncios',maintenance:'Mantenimiento',net:'Neto después de todo'};
const pt={...en,title:'Planeador do mix de plataformas',description:'Cada anúncio exige manutenção. Modele o seu mix mensal após taxas, horas de manutenção, anúncios externos e administração de IVA.',copied:'Copiado — cole nas suas notas ou documento de planeamento.',copyFailed:'Falha ao copiar — selecione o texto manualmente.',sales:'Vendas mensais (todas as plataformas)',price:'Preço médio do padrão ($)',rate:'O seu valor de design ($/h)',hours:'Horas de marketing/mês',international:'Vendas internacionais (%)',offsite:'Cobrar anúncios externos do Etsy (15%) — obrigatório acima de $10 mil/ano',gross:'Bruto/mês',fees:'Taxas e anúncios',maintenance:'Manutenção',net:'Líquido depois de tudo'};
export const COPY:Record<LanguageCode,typeof en>={en,de,fr,es,pt};

export const PLATFORM_MIX_COPY = COPY;
