import type { LanguageCode } from '@/lib/i18n';

export interface SettingsCopy {
  unitsDescription: string; inches: string; centimeters: string; projectOverride: string;
  gradingDescription: string; cycName: string; cycDescription: string; custom: string; customDescription: string;
  cycValue: (value: string | number) => string; light: string; dark: string; system: string;
  restartOnboarding: string; exportWorkspace: string; exportDescription: string; restoreBackup: string; restoreDescription: string;
}

const COPY: Record<LanguageCode, SettingsCopy> = {
  en: { unitsDescription: 'Choose the primary unit for your workspace.', inches: 'Inches', centimeters: 'Centimeters', projectOverride: 'You can override this setting per-project.', gradingDescription: 'The grading standard your patterns are built from.', cycName: 'Craft Yarn Council', cycDescription: 'The published CYC body-measurement chart.', custom: 'Custom', customDescription: 'Your own measurement chart.', cycValue: (value) => `CYC value: ${value}\"`, light: 'Light', dark: 'Dark', system: 'System', restartOnboarding: 'Restart Onboarding', exportWorkspace: 'Export Workspace', exportDescription: 'Download a JSON file containing all your patterns and settings.', restoreBackup: 'Restore from Backup', restoreDescription: 'Merges with your workspace — your existing patterns are never deleted or overwritten.' },
  de: { unitsDescription: 'Wähle die bevorzugte Einheit für deine Arbeitsumgebung.', inches: 'Zoll', centimeters: 'Zentimeter', projectOverride: 'Diese Einstellung kann pro Projekt überschrieben werden.', gradingDescription: 'Der Gradierungsstandard, auf dem deine Muster basieren.', cycName: 'Craft Yarn Council', cycDescription: 'Die veröffentlichte CYC-Körpermaßtafel.', custom: 'Benutzerdefiniert', customDescription: 'Deine eigene Maßtabelle.', cycValue: (value) => `CYC-Wert: ${value}\"`, light: 'Hell', dark: 'Dunkel', system: 'System', restartOnboarding: 'Onboarding neu starten', exportWorkspace: 'Arbeitsumgebung exportieren', exportDescription: 'Lade eine JSON-Datei mit allen Mustern und Einstellungen herunter.', restoreBackup: 'Aus Sicherung wiederherstellen', restoreDescription: 'Wird mit deiner Arbeitsumgebung zusammengeführt — vorhandene Muster werden nie gelöscht oder überschrieben.' },
  fr: { unitsDescription: 'Choisissez l’unité principale de votre espace de travail.', inches: 'Pouces', centimeters: 'Centimètres', projectOverride: 'Cette option peut être remplacée pour chaque projet.', gradingDescription: 'Le standard de gradation utilisé par vos patrons.', cycName: 'Craft Yarn Council', cycDescription: 'Le tableau publié des mesures corporelles du CYC.', custom: 'Personnalisé', customDescription: 'Votre propre tableau de mesures.', cycValue: (value) => `Valeur CYC : ${value}\"`, light: 'Clair', dark: 'Sombre', system: 'Système', restartOnboarding: 'Redémarrer l’onboarding', exportWorkspace: 'Exporter l’espace de travail', exportDescription: 'Téléchargez un fichier JSON contenant tous vos patrons et réglages.', restoreBackup: 'Restaurer une sauvegarde', restoreDescription: 'Fusionne votre espace de travail — vos patrons existants ne sont jamais supprimés ni remplacés.' },
  es: { unitsDescription: 'Elige la unidad principal de tu espacio de trabajo.', inches: 'Pulgadas', centimeters: 'Centímetros', projectOverride: 'Puedes cambiar esta opción por proyecto.', gradingDescription: 'El estándar de gradación en el que se basan tus patrones.', cycName: 'Craft Yarn Council', cycDescription: 'La tabla publicada de medidas corporales del CYC.', custom: 'Personalizado', customDescription: 'Tu propia tabla de medidas.', cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Oscuro', system: 'Sistema', restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espacio de trabajo', exportDescription: 'Descarga un archivo JSON con todos tus patrones y ajustes.', restoreBackup: 'Restaurar desde una copia', restoreDescription: 'Se combina con tu espacio de trabajo; tus patrones existentes nunca se eliminan ni se sobrescriben.' },
  pt: { unitsDescription: 'Escolha a unidade principal do seu espaço de trabalho.', inches: 'Polegadas', centimeters: 'Centímetros', projectOverride: 'Pode substituir esta definição em cada projeto.', gradingDescription: 'O padrão de graduação em que os seus padrões são baseados.', cycName: 'Craft Yarn Council', cycDescription: 'A tabela publicada de medidas corporais do CYC.', custom: 'Personalizado', customDescription: 'A sua própria tabela de medidas.', cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Escuro', system: 'Sistema', restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espaço de trabalho', exportDescription: 'Descarregue um ficheiro JSON com todos os seus padrões e definições.', restoreBackup: 'Restaurar a partir de cópia', restoreDescription: 'É fundido com o seu espaço de trabalho — os padrões existentes nunca são eliminados nem substituídos.' },
};

export function getSettingsCopy(locale: string): SettingsCopy {
  return COPY[locale.toLowerCase().split('-')[0] as LanguageCode] ?? COPY.en;
}

