import type { LanguageCode } from '@/lib/i18n';

export interface SettingsCopy {
  unitsTitle: string; unitsDescription: string; inches: string; centimeters: string; projectOverride: string;
  gradingTitle: string; gradingDescription: string; cycName: string; cycDescription: string; custom: string; customDescription: string;
  cycValue: (value: string | number) => string; light: string; dark: string; system: string;
  restartOnboarding: string; exportWorkspace: string; exportDescription: string; restoreBackup: string; restoreDescription: string;
  customHelper: string; resetAll: string; futureStandards: string; recognitionTitle: string; recognitionToggle: string; recognitionDescription: string;
  onboardingTitle: string; onboardingDescription: string; restartGuide: string; restartGuideDescription: string;
  dataTitle: string; dataDescription: string; downloadBackup: string; uploadFile: string;
  storageHealthTitle: string; storageHealthDesc: string; browserStorage: string; offlineCache: string;
  projectsCount: (count: number) => string; projectCount: (count: number) => string;
  storesInSync: string; storesOutOfSync: string; syncSuccess: string; syncDiff: string;
  reconcile: string; neverBackedUp: string; backedUpToday: string;
  backedUpDays: (days: number) => string; backedUpDay: (days: number) => string;
  backupOverdue: string; backupInstruction: string; backupInsurance: string;
  storageProtectionTitle: string; storageProtectionDescription: string; storageProtectionAction: string;
  storageProtectionNotNow: string; storageProtectionDismiss: string;
  storageProtectionProtected: string; storageProtectionDeclined: string; storageProtectionUnavailable: string; storageProtectionError: string;
  dangerZone: string; dangerZoneDesc: string; deleteAllData: string; deleteAllConfirm: string; deleteAllWarning: string;
  restorePreview: string; restoreReady: string; restoreSummary: (projects: number, settings: number) => string;
  confirmRestore: string; cancelRestore: string;
  developerTitle: string; developerDescription: string; mcpEndpointTitle: string; mcpEndpointDescription: string;
  mcpStatusActive: string; mcpStatusInactive: string; mcpInstructionsTitle: string; mcpInstructionsDescription: string;
  copyEndpoint: string; endpointCopied: string;
}

export const COPY: Record<LanguageCode, SettingsCopy> = {
  en: {
    unitsTitle: 'Measurement Defaults', unitsDescription: 'Choose the primary unit for your workspace.', inches: 'Inches', centimeters: 'Centimeters', projectOverride: 'You can override this setting per-project.',
    gradingTitle: 'Sizing Standard', gradingDescription: 'The grading standard your patterns are built from.', cycName: 'Craft Yarn Council', cycDescription: 'The published CYC body-measurement chart.', custom: 'Custom', customDescription: 'Your own measurement chart.',
    cycValue: (value) => `CYC value: ${value}\"`, light: 'Light', dark: 'Dark', system: 'System',
    restartOnboarding: 'Restart Onboarding', exportWorkspace: 'Export Workspace', exportDescription: 'Download a JSON file containing all your patterns and settings.', restoreBackup: 'Restore from Backup', restoreDescription: 'Merges with your workspace — your existing patterns are never deleted or overwritten.',
    customHelper: 'Every value starts as a copy of the CYC chart. Edit only where your own patterns run differently — everything else keeps grading exactly like CYC until you change it.',
    resetAll: 'Reset all', futureStandards: 'Additional international standards (UK, EU, Japanese) will become available through future updates.', recognitionTitle: 'Quiet acknowledgments', recognitionToggle: 'Show quiet acknowledgments', recognitionDescription: 'Show a private, dismissible note after this project receives its first clean grade. Turning this off keeps local evidence and does not change grading or exports.',
    onboardingTitle: 'Onboarding', onboardingDescription: 'Re-run the setup guide to review your workspace configuration.', restartGuide: 'Restart Guide', restartGuideDescription: 'Walk through the setup guide again — sizing standard, units, workspace tour.',
    dataTitle: 'Data & Backups', dataDescription: 'Your patterns live right here in this browser — nothing\'s uploaded unless you choose to. Back them up regularly, just in case.',
    downloadBackup: 'Download Backup', uploadFile: 'Upload File',
    storageHealthTitle: 'Storage Health', storageHealthDesc: 'Where your patterns live, whether both copies agree, and when you last backed up.',
    browserStorage: 'Browser storage', offlineCache: 'Offline cache',
    projectsCount: (count) => `${count} projects`, projectCount: (count) => `${count} project`,
    storesInSync: 'Stores in sync', storesOutOfSync: 'Stores out of sync',
    syncSuccess: 'Both locations hold the same projects.', syncDiff: 'The two copies differ — reconcile to make them match.',
    reconcile: 'Reconcile', neverBackedUp: 'Never backed up', backedUpToday: 'Backed up today',
    backedUpDays: (days) => `Backed up ${days} days ago`, backedUpDay: (days) => `Backed up ${days} day ago`,
    backupOverdue: 'Overdue', backupInstruction: 'Exports are stored as JSON files — download one to be safe.',
    backupInsurance: 'Stitch & Scale keeps two independent copies of your work on this device — each can recover the other. A backup file is still your true insurance: it\'s the one copy you control outside the browser.',
    storageProtectionTitle: 'Protect this browser’s local work', storageProtectionDescription: 'Your first saved project is stored on this device. Ask the browser to protect this site’s local storage from automatic eviction where supported. This is not a backup.', storageProtectionAction: 'Protect local work', storageProtectionNotNow: 'Not now', storageProtectionDismiss: 'Dismiss storage protection notice', storageProtectionProtected: 'This browser reports that this site’s storage is protected from automatic eviction. Keep exporting backups; this is not a backup.', storageProtectionDeclined: 'The browser did not grant storage protection. Your local work still saves normally. Keep exporting backups.', storageProtectionUnavailable: 'This browser does not offer storage protection here. Your local work still saves normally. Keep exporting backups.', storageProtectionError: 'The browser could not complete the storage-protection request. Your local work still saves normally. Keep exporting backups.',
    dangerZone: 'Danger Zone',
    dangerZoneDesc: 'Irreversible data actions. Use with extreme caution.',
    deleteAllData: 'Delete all local data',
    deleteAllConfirm: 'Are you absolutely sure? This will permanently erase all projects and settings from this browser.',
    deleteAllWarning: 'This action cannot be undone. Make sure you have a backup first.',
    restorePreview: 'Restore Preview',
    restoreReady: 'Ready to import',
    restoreSummary: (p: number, s: number) => `Found ${p} projects and ${s} settings keys.`,
    confirmRestore: 'Confirm Restore',
    cancelRestore: 'Cancel',
    developerTitle: 'Developer & MCP',
    developerDescription: 'Advanced settings for connecting external AI assistants via Model Context Protocol.',
    mcpEndpointTitle: 'Production MCP Endpoint',
    mcpEndpointDescription: 'The live URL for external AI tools to access your local workspace patterns and standards.',
    mcpStatusActive: 'Endpoint Active',
    mcpStatusInactive: 'Endpoint Inactive',
    mcpInstructionsTitle: 'How to use',
    mcpInstructionsDescription: 'Copy this URL into your AI assistant\'s MCP configuration (e.g. Claude Desktop or Manus Connectors) to allow it to read and grade your patterns.',
    copyEndpoint: 'Copy URL',
    endpointCopied: 'Endpoint URL copied to clipboard',
  },
  de: {
    unitsTitle: 'Standard-Maßeinheiten', unitsDescription: 'Wähle die bevorzugte Einheit für deine Arbeitsumgebung.', inches: 'Zoll', centimeters: 'Zentimeter', projectOverride: 'Diese Einstellung kann pro Projekt überschrieben werden.',
    gradingTitle: 'Größenstandard', gradingDescription: 'Der Gradierungsstandard, auf dem deine Muster basieren.', cycName: 'Craft Yarn Council', cycDescription: 'Die veröffentlichte CYC-Körpermaßtafel.', custom: 'Benutzerdefiniert', customDescription: 'Deine eigene Maßtabelle.',
    cycValue: (value) => `CYC-Wert: ${value}\"`, light: 'Hell', dark: 'Dunkel', system: 'System',
    restartOnboarding: 'Onboarding neu starten', exportWorkspace: 'Arbeitsumgebung exportieren', exportDescription: 'Lade eine JSON-Datei mit allen Mustern und Einstellungen herunter.', restoreBackup: 'Aus Sicherung wiederherstellen', restoreDescription: 'Wird mit deiner Arbeitsumgebung zusammengeführt — vorhandene Muster werden nie gelöscht oder überschrieben.',
    customHelper: 'Jeder Wert beginnt als Kopie der CYC-Tabelle. Bearbeite nur dort, wo deine eigenen Muster abweichen — alles andere wird genau wie CYC gradiert, bis du es änderst.',
    resetAll: 'Alles zurücksetzen', futureStandards: 'Weitere internationale Standards (UK, EU, Japanisch) werden in zukünftigen Updates verfügbar sein.', recognitionTitle: 'Ruhige Hinweise', recognitionToggle: 'Ruhige Hinweise anzeigen', recognitionDescription: 'Zeige einen privaten, schließbaren Hinweis, wenn dieses Projekt erstmals sauber gradiert ist. Das Ausschalten bewahrt lokale Nachweise und ändert weder Gradierung noch Exporte.',
    onboardingTitle: 'Onboarding', onboardingDescription: 'Starte den Einrichtungsassistenten neu, um deine Arbeitsumgebung zu überprüfen.', restartGuide: 'Guide neu starten', restartGuideDescription: 'Gehe den Einrichtungsassistenten noch einmal durch — Größenstandard, Einheiten, Tour durch den Arbeitsbereich.',
    dataTitle: 'Daten & Backups', dataDescription: 'Deine Muster leben direkt hier in diesem Browser — nichts wird hochgeladen, außer du entscheidest dich dazu. Sichere sie regelmäßig ab.',
    downloadBackup: 'Backup herunterladen', uploadFile: 'Datei hochladen',
    storageHealthTitle: 'Speicherzustand', storageHealthDesc: 'Wo deine Muster gespeichert sind, ob beide Kopien übereinstimmen und wann du zuletzt gesichert hast.',
    browserStorage: 'Browser-Speicher', offlineCache: 'Offline-Cache',
    projectsCount: (count) => `${count} Projekte`, projectCount: (count) => `${count} Projekt`,
    storesInSync: 'Speicher synchron', storesOutOfSync: 'Speicher nicht synchron',
    syncSuccess: 'Beide Orte enthalten die gleichen Projekte.', syncDiff: 'Die zwei Kopien unterscheiden sich — abgleichen, um sie anzugleichen.',
    reconcile: 'Abgleichen', neverBackedUp: 'Noch nie gesichert', backedUpToday: 'Heute gesichert',
    backedUpDays: (days) => `Vor ${days} Tagen gesichert`, backedUpDay: (days) => `Vor ${days} Tag gesichert`,
    backupOverdue: 'Überfällig', backupInstruction: 'Exporte werden als JSON-Dateien gespeichert — lade eine herunter, um sicher zu gehen.',
    backupInsurance: 'Stitch & Scale bewahrt zwei unabhängige Kopien deiner Arbeit auf diesem Gerät auf — jede kann die andere wiederherstellen. Eine Backup-Datei ist dennoch deine wahre Versicherung: Es ist die einzige Kopie, die du außerhalb des Browsers kontrollierst.',
    storageProtectionTitle: 'Lokale Arbeit in diesem Browser schützen', storageProtectionDescription: 'Dein erstes gespeichertes Projekt liegt auf diesem Gerät. Bitte den Browser, den lokalen Speicher dieser Website – sofern unterstützt – vor automatischer Löschung zu schützen. Das ist kein Backup.', storageProtectionAction: 'Lokale Arbeit schützen', storageProtectionNotNow: 'Jetzt nicht', storageProtectionDismiss: 'Hinweis zum Speicherschutz schließen', storageProtectionProtected: 'Dieser Browser meldet, dass der Speicher dieser Website vor automatischer Löschung geschützt ist. Erstelle weiterhin Backups; dies ist kein Backup.', storageProtectionDeclined: 'Der Browser hat den Speicherschutz nicht gewährt. Deine lokale Arbeit wird weiterhin normal gespeichert. Erstelle weiterhin Backups.', storageProtectionUnavailable: 'Dieser Browser bietet hier keinen Speicherschutz an. Deine lokale Arbeit wird weiterhin normal gespeichert. Erstelle weiterhin Backups.', storageProtectionError: 'Der Browser konnte die Speicherschutz-Anfrage nicht abschließen. Deine lokale Arbeit wird weiterhin normal gespeichert. Erstelle weiterhin Backups.',
    dangerZone: 'Gefahrenzone',
    dangerZoneDesc: 'Unwiderrufliche Datenaktionen. Mit äußerster Vorsicht verwenden.',
    deleteAllData: 'Alle lokalen Daten löschen',
    deleteAllConfirm: 'Bist du absolut sicher? Dies wird alle Projekte und Einstellungen dauerhaft aus diesem Browser löschen.',
    deleteAllWarning: 'Diese Aktion kann nicht rückgängig gemacht werden. Stelle sicher, dass du zuerst ein Backup hast.',
    restorePreview: 'Vorschau wiederherstellen',
    restoreReady: 'Bereit zum Importieren',
    restoreSummary: (p: number, s: number) => `${p} Projekte und ${s} Einstellungsschlüssel gefunden.`,
    confirmRestore: 'Wiederherstellung bestätigen',
    cancelRestore: 'Abbrechen',
    developerTitle: 'Entwickler & MCP',
    developerDescription: 'Erweiterte Einstellungen für die Verbindung externer KI-Assistenten über das Model Context Protocol.',
    mcpEndpointTitle: 'Produktions-MCP-Endpunkt',
    mcpEndpointDescription: 'Die Live-URL, über die externe KI-Tools auf deine lokalen Muster und Standards zugreifen können.',
    mcpStatusActive: 'Endpunkt Aktiv',
    mcpStatusInactive: 'Endpunkt Inaktiv',
    mcpInstructionsTitle: 'Verwendung',
    mcpInstructionsDescription: 'Kopiere diese URL in die MCP-Konfiguration deines KI-Assistenten (z. B. Claude Desktop oder Manus Connectors), um ihm das Lesen und Gradieren deiner Muster zu ermöglichen.',
    copyEndpoint: 'URL kopieren',
    endpointCopied: 'Endpunkt-URL in die Zwischenablage kopiert',
  },
  fr: {
    unitsTitle: 'Unités par défaut', unitsDescription: 'Choisissez l’unité principale de votre espace de travail.', inches: 'Pouces', centimeters: 'Centimètres', projectOverride: 'Cette option peut être remplacée pour chaque projet.',
    gradingTitle: 'Standard de taille', gradingDescription: 'Le standard de gradation utilisé par vos patrons.', cycName: 'Craft Yarn Council', cycDescription: 'Le tableau publié des mesures corporelles du CYC.', custom: 'Personnalisé', customDescription: 'Votre propre tableau de mesures.',
    cycValue: (value) => `Valeur CYC : ${value}\"`, light: 'Clair', dark: 'Sombre', system: 'Système',
    restartOnboarding: 'Redémarrer l’onboarding', exportWorkspace: 'Exporter l’espace de travail', exportDescription: 'Téléchargez un fichier JSON contenant tous vos patrons et réglages.', restoreBackup: 'Restaurer une sauvegarde', restoreDescription: 'Fusionne votre espace de travail — vos patrons existants ne sont jamais supprimés ni remplacés.',
    customHelper: 'Chaque valeur commence par une copie du tableau CYC. Modifiez uniquement là où vos propres patrons diffèrent — tout le reste continue de grader exactement comme le CYC jusqu\'à ce que vous le changiez.',
    resetAll: 'Tout réinitialiser', futureStandards: 'D\'autres standards internationaux (UK, EU, Japonais) seront disponibles dans les futures mises à jour.', recognitionTitle: 'Repères discrets', recognitionToggle: 'Afficher les repères discrets', recognitionDescription: 'Affichez une note privée et fermable lorsque ce projet obtient sa première gradation propre. La désactivation conserve les preuves locales et ne modifie ni la gradation ni les exportations.',
    onboardingTitle: 'Onboarding', onboardingDescription: 'Relancez le guide d\'installation pour revoir la configuration de votre espace de travail.', restartGuide: 'Redémarrer le guide', restartGuideDescription: 'Suivez à nouveau le guide d\'installation — standard de taille, unités, visite de l\'espace de travail.',
    dataTitle: 'Données & Sauvegardes', dataDescription: 'Vos patrons vivent ici même dans ce navigateur — rien n\'est téléchargé sauf si vous le choisissez. Sauvegardez-les régulièrement.',
    downloadBackup: 'Télécharger la sauvegarde', uploadFile: 'Charger un fichier',
    storageHealthTitle: 'Santé du stockage', storageHealthDesc: 'Où vos patrons sont stockés, si les deux copies concordent, et quand vous avez sauvegardé pour la dernière fois.',
    browserStorage: 'Stockage navigateur', offlineCache: 'Cache hors ligne',
    projectsCount: (count) => `${count} projets`, projectCount: (count) => `${count} projet`,
    storesInSync: 'Stockages synchronisés', storesOutOfSync: 'Stockages désynchronisés',
    syncSuccess: 'Les deux emplacements contiennent les mêmes projets.', syncDiff: 'Les deux copies diffèrent — réconciliez-les pour qu\'elles correspondent.',
    reconcile: 'Réconcilier', neverBackedUp: 'Jamais sauvegardé', backedUpToday: 'Sauvegardé aujourd\'hui',
    backedUpDays: (days) => `Sauvegardé il y a ${days} jours`, backedUpDay: (days) => `Sauvegardé il y a ${days} jour`,
    backupOverdue: 'En retard', backupInstruction: 'Les exportations sont stockées sous forme de fichiers JSON — téléchargez-en un pour plus de sécurité.',
    backupInsurance: 'Stitch & Scale conserve deux copies indépendantes de votre travail sur cet appareil — chacune peut restaurer l\'autre. Un fichier de sauvegarde reste votre véritable assurance : c\'est la seule copie que vous contrôlez en dehors du navigateur.',
    storageProtectionTitle: 'Protéger le travail local de ce navigateur', storageProtectionDescription: 'Votre premier projet enregistré est conservé sur cet appareil. Demandez au navigateur de protéger le stockage local de ce site contre la suppression automatique lorsque cette protection est disponible. Ce n’est pas une sauvegarde.', storageProtectionAction: 'Protéger le travail local', storageProtectionNotNow: 'Pas maintenant', storageProtectionDismiss: 'Fermer l’avis de protection du stockage', storageProtectionProtected: 'Ce navigateur indique que le stockage de ce site est protégé contre la suppression automatique. Continuez à exporter des sauvegardes : ceci n’est pas une sauvegarde.', storageProtectionDeclined: 'Le navigateur n’a pas accordé la protection du stockage. Votre travail local continue d’être enregistré normalement. Continuez à exporter des sauvegardes.', storageProtectionUnavailable: 'Ce navigateur ne propose pas la protection du stockage ici. Votre travail local continue d’être enregistré normalement. Continuez à exporter des sauvegardes.', storageProtectionError: 'Le navigateur n’a pas pu terminer la demande de protection du stockage. Votre travail local continue d’être enregistré normalement. Continuez à exporter des sauvegardes.',
    dangerZone: 'Zone de danger',
    dangerZoneDesc: 'Actions sur les données irréversibles. À utiliser avec une extrême prudence.',
    deleteAllData: 'Supprimer toutes les données locales',
    deleteAllConfirm: 'Êtes-vous absolument sûr ? Cela effacera définitivement tous les projets et réglages de ce navigateur.',
    deleteAllWarning: 'Cette action est irréversible. Assurez-vous d’avoir d’abord une sauvegarde.',
    restorePreview: 'Aperçu de la restauration',
    restoreReady: 'Prêt à importer',
    restoreSummary: (p: number, s: number) => `${p} projets et ${s} clés de réglages trouvés.`,
    confirmRestore: 'Confirmer la restauration',
    cancelRestore: 'Annuler',
    developerTitle: 'Développeur & MCP',
    developerDescription: 'Paramètres avancés pour connecter des assistants IA externes via le Model Context Protocol.',
    mcpEndpointTitle: 'Point de terminaison MCP de production',
    mcpEndpointDescription: 'L\'URL en direct permettant aux outils IA externes d\'accéder à vos patrons et standards locaux.',
    mcpStatusActive: 'Point de terminaison actif',
    mcpStatusInactive: 'Point de terminaison inactif',
    mcpInstructionsTitle: 'Comment utiliser',
    mcpInstructionsDescription: 'Copiez cette URL dans la configuration MCP de votre assistant IA (par exemple, Claude Desktop ou Manus Connectors) pour lui permettre de lire et de grader vos patrons.',
    copyEndpoint: 'Copier l\'URL',
    endpointCopied: 'URL du point de terminaison copiée dans le presse-papiers',
  },
  es: {
    unitsTitle: 'Unidades predeterminadas', unitsDescription: 'Elige la unidad principal de tu espacio de trabajo.', inches: 'Pulgadas', centimeters: 'Centímetros', projectOverride: 'Puedes cambiar esta opción por proyecto.',
    gradingTitle: 'Estándar de tallas', gradingDescription: 'El estándar de gradación en el que se basan tus patrones.', cycName: 'Craft Yarn Council', cycDescription: 'La tabla publicada de medidas corporales del CYC.', custom: 'Personalizado', customDescription: 'Tu propia tabla de medidas.',
    cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Oscuro', system: 'Sistema',
    restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espacio de trabajo', exportDescription: 'Descarga un archivo JSON con todos tus patrones y ajustes.', restoreBackup: 'Restaurar desde una copia', restoreDescription: 'Se combina con tu espacio de trabajo; tus patrones existentes nunca se eliminan ni se sobrescriben.',
    customHelper: 'Cada valor comienza como una copia de la tabla CYC. Edita solo donde tus propios patrones sean diferentes; todo lo demás se seguirá graduando exactamente como CYC hasta que lo cambies.',
    resetAll: 'Restablecer todo', futureStandards: 'Otros estándares internacionales (Reino Unido, UE, japonés) estarán disponibles en futuras actualizaciones.', recognitionTitle: 'Referencias tranquilas', recognitionToggle: 'Mostrar referencias tranquilas', recognitionDescription: 'Muestra una nota privada y descartable cuando este proyecto consiga su primera gradación limpia. Desactivarlo conserva la evidencia local y no cambia la gradación ni las exportaciones.',
    onboardingTitle: 'Onboarding', onboardingDescription: 'Vuelve a ejecutar la guía de configuración para revisar tu espacio de trabajo.', restartGuide: 'Reiniciar guía', restartGuideDescription: 'Vuelve a recorrer la guía de configuración: estándar de tallas, unidades, recorrido por el espacio de trabajo.',
    dataTitle: 'Datos y copias de seguridad', dataDescription: 'Tus patrones viven aquí mismo en este navegador; no se sube nada a menos que tú lo decidas. Haz copias de seguridad con regularidad.',
    downloadBackup: 'Descargar copia', uploadFile: 'Subir archivo',
    storageHealthTitle: 'Salud del almacenamiento', storageHealthDesc: 'Dónde viven tus patrones, si ambas copias coinciden y cuándo hiciste la última copia de seguridad.',
    browserStorage: 'Almacenamiento del navegador', offlineCache: 'Caché sin conexión',
    projectsCount: (count) => `${count} proyectos`, projectCount: (count) => `${count} proyecto`,
    storesInSync: 'Almacenes sincronizados', storesOutOfSync: 'Almacenes desincronizados',
    syncSuccess: 'Ambas ubicaciones contienen los mismos proyectos.', syncDiff: 'Las dos copias difieren; reconcílialas para que coincidan.',
    reconcile: 'Reconciliar', neverBackedUp: 'Sin copias de seguridad', backedUpToday: 'Copia realizada hoy',
    backedUpDays: (days) => `Copia hace ${days} días`, backedUpDay: (days) => `Copia hace ${days} día`,
    backupOverdue: 'Atrasado', backupInstruction: 'Las exportaciones se guardan como archivos JSON; descarga uno para mayor seguridad.',
    backupInsurance: 'Stitch & Scale guarda dos copias independientes de tu trabajo en este dispositivo; cada una puede recuperar la otra. Un archivo de respaldo sigue siendo tu verdadero seguro: es la única copia que controlas fuera del navegador.',
    storageProtectionTitle: 'Proteger el trabajo local de este navegador', storageProtectionDescription: 'Tu primer proyecto guardado se almacena en este dispositivo. Pide al navegador que proteja el almacenamiento local de este sitio frente a la eliminación automática cuando sea compatible. Esto no es una copia de seguridad.', storageProtectionAction: 'Proteger trabajo local', storageProtectionNotNow: 'Ahora no', storageProtectionDismiss: 'Cerrar aviso de protección del almacenamiento', storageProtectionProtected: 'Este navegador indica que el almacenamiento de este sitio está protegido frente a la eliminación automática. Sigue exportando copias de seguridad; esto no es una copia de seguridad.', storageProtectionDeclined: 'El navegador no concedió la protección del almacenamiento. Tu trabajo local se sigue guardando con normalidad. Sigue exportando copias de seguridad.', storageProtectionUnavailable: 'Este navegador no ofrece protección del almacenamiento aquí. Tu trabajo local se sigue guardando con normalidad. Sigue exportando copias de seguridad.', storageProtectionError: 'El navegador no pudo completar la solicitud de protección del almacenamiento. Tu trabajo local se sigue guardando con normalidad. Sigue exportando copias de seguridad.',
    dangerZone: 'Zona de peligro',
    dangerZoneDesc: 'Acciones de datos irreversibles. Usar con extrema precaución.',
    deleteAllData: 'Eliminar todos los datos locales',
    deleteAllConfirm: '¿Estás absolutamente seguro? Esto borrará permanentemente todos los proyectos y ajustes de este navegador.',
    deleteAllWarning: 'Esta acción no se puede deshacer. Asegúrate de tener una copia de seguridad primero.',
    restorePreview: 'Vista previa de restauración',
    restoreReady: 'Listo para importar',
    restoreSummary: (p: number, s: number) => `Se han encontrado ${p} proyectos y ${s} claves de ajustes.`,
    confirmRestore: 'Confirmar restauración',
    cancelRestore: 'Cancelar',
    developerTitle: 'Desarrollador y MCP',
    developerDescription: 'Ajustes avanzados para conectar asistentes de IA externos a través del Model Context Protocol.',
    mcpEndpointTitle: 'Punto de conexión MCP de producción',
    mcpEndpointDescription: 'La URL en vivo para que las herramientas de IA externas accedan a tus patrones y estándares locales.',
    mcpStatusActive: 'Punto de conexión activo',
    mcpStatusInactive: 'Punto de conexión inactivo',
    mcpInstructionsTitle: 'Cómo usar',
    mcpInstructionsDescription: 'Copia esta URL en la configuración MCP de tu asistente de IA (por ejemplo, Claude Desktop o Manus Connectors) para permitirle leer y graduar tus patrones.',
    copyEndpoint: 'Copiar URL',
    endpointCopied: 'URL del punto de conexión copiada al portapapeles',
  },
  pt: {
    unitsTitle: 'Unidades predefinidas', unitsDescription: 'Escolha a unidade principal do seu espaço de trabalho.', inches: 'Polegadas', centimeters: 'Centimètres', projectOverride: 'Pode substituir esta definição em cada projeto.',
    gradingTitle: 'Padrão de tamanhos', gradingDescription: 'O padrão de graduação em que os seus padrões são baseados.', cycName: 'Craft Yarn Council', cycDescription: 'A tabela publicada de medidas corporais do CYC.', custom: 'Personalizado', customDescription: 'A sua própria tabela de medidas.',
    cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Escuro', system: 'Sistema',
    restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espaço de trabalho', exportDescription: 'Descarregue um ficheiro JSON com todos os seus padrões e definições.', restoreBackup: 'Restaurar a partir de cópia', restoreDescription: 'É fundido com o seu espaço de trabalho — os padrões existentes nunca são eliminados nem substituídos.',
    customHelper: 'Cada valor começa como uma cópia da tabela CYC. Edite apenas onde os seus próprios padrões forem diferentes — tudo o resto continuará a graduar exatamente como o CYC até que o altere.',
    resetAll: 'Repor tudo', futureStandards: 'Outros padrões internacionais (Reino Unido, UE, japonês) estarão disponíveis em futuras atualizações.', recognitionTitle: 'Reconhecimentos discretos', recognitionToggle: 'Mostrar reconhecimentos discretos', recognitionDescription: 'Mostre uma nota privada e fechável quando este projeto obtiver a sua primeira graduação limpa. Desativar mantém as provas locais e não altera a graduação nem as exportações.',
    onboardingTitle: 'Onboarding', onboardingDescription: 'Execute novamente o guia de configuração para rever o seu espaço de trabalho.', restartGuide: 'Reiniciar guia', restartGuideDescription: 'Percorra novamente o guia de configuração — padrão de tamanhos, unidades, visita ao espaço de trabalho.',
    dataTitle: 'Dados e Cópias de Segurança', dataDescription: 'Os seus padrões vivem aqui mesmo neste navegador — nada é carregado a menos que você escolha fazê-lo. Faça cópias de segurança regularmente.',
    downloadBackup: 'Descarregar cópia', uploadFile: 'Carregar ficheiro',
    storageHealthTitle: 'Saúde do armazenamento', storageHealthDesc: 'Onde os seus padrões vivem, se ambas as cópias coincidem e quando foi feita a última cópia de segurança.',
    browserStorage: 'Armazenamento do navegador', offlineCache: 'Cache offline',
    projectsCount: (count) => `${count} projetos`, projectCount: (count) => `${count} projeto`,
    storesInSync: 'Armazéns sincronizados', storesOutOfSync: 'Armazéns dessincronizados',
    syncSuccess: 'Ambos os locais contêm os mesmos projetos.', syncDiff: 'As duas cópias diferem — reconcilie para que coincidam.',
    reconcile: 'Reconciliar', neverBackedUp: 'Sem cópias de segurança', backedUpToday: 'Cópia feita hoje',
    backedUpDays: (days) => `Cópia há ${days} dias`, backedUpDay: (days) => `Cópia há ${days} dia`,
    backupOverdue: 'Em atraso', backupInstruction: 'As exportações são guardadas como ficheiros JSON — descarregue um para maior segurança.',
    backupInsurance: 'O Stitch & Scale guarda duas cópias independentes do seu trabalho neste dispositivo — cada uma pode recuperar a outra. Um ficheiro de cópia de segurança continua a ser o seu verdadeiro seguro: é a única cópia que controla fora do navegador.',
    storageProtectionTitle: 'Proteger o trabalho local deste navegador', storageProtectionDescription: 'O seu primeiro projeto guardado fica neste dispositivo. Peça ao navegador para proteger o armazenamento local deste site contra eliminação automática quando houver suporte. Isto não é uma cópia de segurança.', storageProtectionAction: 'Proteger trabalho local', storageProtectionNotNow: 'Agora não', storageProtectionDismiss: 'Fechar aviso de proteção do armazenamento', storageProtectionProtected: 'Este navegador indica que o armazenamento deste site está protegido contra eliminação automática. Continue a exportar cópias de segurança; isto não é uma cópia de segurança.', storageProtectionDeclined: 'O navegador não concedeu proteção do armazenamento. O seu trabalho local continua a ser guardado normalmente. Continue a exportar cópias de segurança.', storageProtectionUnavailable: 'Este navegador não oferece proteção do armazenamento aqui. O seu trabalho local continua a ser guardado normalmente. Continue a exportar cópias de segurança.', storageProtectionError: 'O navegador não conseguiu concluir o pedido de proteção do armazenamento. O seu trabalho local continua a ser guardado normalmente. Continue a exportar cópias de segurança.',
    dangerZone: 'Zona de Perigo',
    dangerZoneDesc: 'Ações de dados irreversíveis. Utilize com extrema cautela.',
    deleteAllData: 'Eliminar todos os dados locais',
    deleteAllConfirm: 'Tem a certeza absoluta? Isto apagará permanentemente todos os projetos e definições deste navegador.',
    deleteAllWarning: 'Esta ação não pode ser desfeita. Certifique-se de que tem uma cópia de segurança primeiro.',
    restorePreview: 'Pré-visualização de restauro',
    restoreReady: 'Pronto para importar',
    restoreSummary: (p: number, s: number) => `Encontrados ${p} projetos e ${s} chaves de definições.`,
    confirmRestore: 'Confirmar restauro',
    cancelRestore: 'Cancelar',
    developerTitle: 'Programador e MCP',
    developerDescription: 'Definições avançadas para ligar assistentes de IA externos através do Model Context Protocol.',
    mcpEndpointTitle: 'Ponto de extremidade MCP de produção',
    mcpEndpointDescription: 'O URL em direto para ferramentas de IA externas acederem aos seus padrões e padrões locais.',
    mcpStatusActive: 'Ponto de extremidade ativo',
    mcpStatusInactive: 'Ponto de extremidade inativo',
    mcpInstructionsTitle: 'Como utilizar',
    mcpInstructionsDescription: 'Copie este URL para a configuração MCP do seu assistente de IA (por exemplo, Claude Desktop ou Manus Connectors) para permitir que este leia e gradue os seus padrões.',
    copyEndpoint: 'Copiar URL',
    endpointCopied: 'URL do ponto de extremidade copiado para a área de transferência',
  },
};

export function getSettingsCopy(locale: string): SettingsCopy {
  return COPY[locale.toLowerCase().split('-')[0] as LanguageCode] ?? COPY.en;
}

