import type { LanguageCode } from '@/lib/i18n';

export interface SettingsCopy {
  unitsDescription: string; inches: string; centimeters: string; projectOverride: string;
  gradingDescription: string; cycName: string; cycDescription: string; custom: string; customDescription: string;
  cycValue: (value: string | number) => string; light: string; dark: string; system: string;
  restartOnboarding: string; exportWorkspace: string; exportDescription: string; restoreBackup: string; restoreDescription: string; backupDownloaded: (projects: number) => string; restoreSuccessful: (imported: number, existingKept: number) => string; restoreFailed: string; restorePreviewTitle: string; restorePreviewProjects: string; restorePreviewRecords: string; restorePreviewSettings: string; restorePreviewWarning: string; restorePreviewCancel: string; restorePreviewConfirm: string;
}

const COPY: Record<LanguageCode, SettingsCopy> = {
  en: { unitsDescription: 'Choose the primary unit for your workspace.', inches: 'Inches', centimeters: 'Centimeters', projectOverride: 'You can override this setting per-project.', gradingDescription: 'The grading standard your patterns are built from.', cycName: 'Craft Yarn Council', cycDescription: 'The published CYC body-measurement chart.', custom: 'Custom', customDescription: 'Your own measurement chart.', cycValue: (value) => `CYC value: ${value}\"`, light: 'Light', dark: 'Dark', system: 'System', restartOnboarding: 'Restart Onboarding', exportWorkspace: 'Export Workspace', exportDescription: 'Download a JSON file containing all your patterns and settings.', restoreBackup: 'Restore from Backup', restoreDescription: 'Merges with your workspace — your existing patterns and project records are never deleted or overwritten.', backupDownloaded: (projects) => `Backup downloaded — ${projects} project${projects === 1 ? '' : 's'} and their local records saved.`, restoreSuccessful: (imported, existingKept) => `Restored ${imported} new project${imported === 1 ? '' : 's'}; ${existingKept} existing project${existingKept === 1 ? '' : 's'} and their records were preserved.`, restoreFailed: 'The backup could not be read or restored.', restorePreviewTitle: 'Backup preview', restorePreviewProjects: 'Projects in this file', restorePreviewRecords: 'Operational records', restorePreviewSettings: 'Workspace settings included', restorePreviewWarning: 'This will merge new projects and their records into this workspace. Existing projects and records will be preserved.', restorePreviewCancel: 'Cancel restore', restorePreviewConfirm: 'Merge backup' },
  de: { unitsDescription: 'Wähle die bevorzugte Einheit für deine Arbeitsumgebung.', inches: 'Zoll', centimeters: 'Zentimeter', projectOverride: 'Diese Einstellung kann pro Projekt überschrieben werden.', gradingDescription: 'Der Gradierungsstandard, auf dem deine Muster basieren.', cycName: 'Craft Yarn Council', cycDescription: 'Die veröffentlichte CYC-Körpermaßtafel.', custom: 'Benutzerdefiniert', customDescription: 'Deine eigene Maßtabelle.', cycValue: (value) => `CYC-Wert: ${value}\"`, light: 'Hell', dark: 'Dunkel', system: 'System', restartOnboarding: 'Onboarding neu starten', exportWorkspace: 'Arbeitsumgebung exportieren', exportDescription: 'Lade eine JSON-Datei mit allen Mustern und Einstellungen herunter.', restoreBackup: 'Aus Sicherung wiederherstellen', restoreDescription: 'Wird mit deiner Arbeitsumgebung zusammengeführt — vorhandene Muster und Projektaufzeichnungen werden nie gelöscht oder überschrieben.', backupDownloaded: (projects) => `Sicherung heruntergeladen — ${projects} Projekt${projects === 1 ? '' : 'e'} und die lokalen Aufzeichnungen wurden gespeichert.`, restoreSuccessful: (imported, existingKept) => `${imported} neue(s) Projekt(e) wiederhergestellt; ${existingKept} vorhandene(s) Projekt(e) und deren Aufzeichnungen wurden bewahrt.`, restoreFailed: 'Die Sicherung konnte nicht gelesen oder wiederhergestellt werden.', restorePreviewTitle: 'Sicherungsvorschau', restorePreviewProjects: 'Projekte in dieser Datei', restorePreviewRecords: 'Betriebliche Aufzeichnungen', restorePreviewSettings: 'Arbeitsumgebungseinstellungen enthalten', restorePreviewWarning: 'Neue Projekte und ihre Aufzeichnungen werden mit dieser Arbeitsumgebung zusammengeführt. Vorhandene Projekte und Aufzeichnungen bleiben erhalten.', restorePreviewCancel: 'Wiederherstellung abbrechen', restorePreviewConfirm: 'Sicherung zusammenführen' },
  fr: { unitsDescription: 'Choisissez l’unité principale de votre espace de travail.', inches: 'Pouces', centimeters: 'Centimètres', projectOverride: 'Cette option peut être remplacée pour chaque projet.', gradingDescription: 'Le standard de gradation utilisé par vos patrons.', cycName: 'Craft Yarn Council', cycDescription: 'Le tableau publié des mesures corporelles du CYC.', custom: 'Personnalisé', customDescription: 'Votre propre tableau de mesures.', cycValue: (value) => `Valeur CYC : ${value}\"`, light: 'Clair', dark: 'Sombre', system: 'Système', restartOnboarding: 'Redémarrer l’onboarding', exportWorkspace: 'Exporter l’espace de travail', exportDescription: 'Téléchargez un fichier JSON contenant tous vos patrons et réglages.', restoreBackup: 'Restaurer une sauvegarde', restoreDescription: 'Fusionne votre espace de travail — vos patrons et registres de projet existants ne sont jamais supprimés ni remplacés.', backupDownloaded: (projects) => `Sauvegarde téléchargée — ${projects} projet${projects === 1 ? '' : 's'} et leurs registres locaux enregistrés.`, restoreSuccessful: (imported, existingKept) => `${imported} nouveau${imported === 1 ? '' : 'x'} projet${imported === 1 ? '' : 's'} restauré${imported === 1 ? '' : 's'} ; ${existingKept} projet${existingKept === 1 ? '' : 's'} existant${existingKept === 1 ? '' : 's'} et leurs registres préservés.`, restoreFailed: 'La sauvegarde n’a pas pu être lue ou restaurée.', restorePreviewTitle: 'Aperçu de la sauvegarde', restorePreviewProjects: 'Projets dans ce fichier', restorePreviewRecords: 'Registres opérationnels', restorePreviewSettings: 'Réglages de l’espace inclus', restorePreviewWarning: 'Les nouveaux projets et leurs registres seront fusionnés dans cet espace. Les projets et registres existants seront préservés.', restorePreviewCancel: 'Annuler la restauration', restorePreviewConfirm: 'Fusionner la sauvegarde' },
  es: { unitsDescription: 'Elige la unidad principal de tu espacio de trabajo.', inches: 'Pulgadas', centimeters: 'Centímetros', projectOverride: 'Puedes cambiar esta opción por proyecto.', gradingDescription: 'El estándar de gradación en el que se basan tus patrones.', cycName: 'Craft Yarn Council', cycDescription: 'La tabla publicada de medidas corporales del CYC.', custom: 'Personalizado', customDescription: 'Tu propia tabla de medidas.', cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Oscuro', system: 'Sistema', restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espacio de trabajo', exportDescription: 'Descarga un archivo JSON con todos tus patrones y ajustes.', restoreBackup: 'Restaurar desde una copia', restoreDescription: 'Se combina con tu espacio de trabajo; tus patrones y registros de proyecto existentes nunca se eliminan ni se sobrescriben.', backupDownloaded: (projects) => `Copia descargada: se guardaron ${projects} proyecto${projects === 1 ? '' : 's'} y sus registros locales.`, restoreSuccessful: (imported, existingKept) => `Se restauraron ${imported} proyecto${imported === 1 ? '' : 's'} nuevo${imported === 1 ? '' : 's'}; se conservaron ${existingKept} proyecto${existingKept === 1 ? '' : 's'} existente${existingKept === 1 ? '' : 's'} y sus registros.`, restoreFailed: 'No se pudo leer o restaurar la copia.', restorePreviewTitle: 'Vista previa de la copia', restorePreviewProjects: 'Proyectos en este archivo', restorePreviewRecords: 'Registros operativos', restorePreviewSettings: 'Ajustes del espacio incluidos', restorePreviewWarning: 'Los proyectos nuevos y sus registros se combinarán con este espacio. Los proyectos y registros existentes se conservarán.', restorePreviewCancel: 'Cancelar restauración', restorePreviewConfirm: 'Combinar copia' },
  pt: { unitsDescription: 'Escolha a unidade principal do seu espaço de trabalho.', inches: 'Polegadas', centimeters: 'Centímetros', projectOverride: 'Pode substituir esta definição em cada projeto.', gradingDescription: 'O padrão de graduação em que os seus padrões são baseados.', cycName: 'Craft Yarn Council', cycDescription: 'A tabela publicada de medidas corporais do CYC.', custom: 'Personalizado', customDescription: 'A sua própria tabela de medidas.', cycValue: (value) => `Valor CYC: ${value}\"`, light: 'Claro', dark: 'Escuro', system: 'Sistema', restartOnboarding: 'Reiniciar onboarding', exportWorkspace: 'Exportar espaço de trabalho', exportDescription: 'Descarregue um ficheiro JSON com todos os seus padrões e definições.', restoreBackup: 'Restaurar a partir de cópia', restoreDescription: 'É fundido com o seu espaço de trabalho — os padrões e registos de projeto existentes nunca são eliminados nem substituídos.', backupDownloaded: (projects) => `Cópia descarregada — foram guardados ${projects} projeto${projects === 1 ? '' : 's'} e os respetivos registos locais.`, restoreSuccessful: (imported, existingKept) => `Foram restaurados ${imported} novo${imported === 1 ? '' : 's'} projeto${imported === 1 ? '' : 's'}; ${existingKept} projeto${existingKept === 1 ? '' : 's'} existente${existingKept === 1 ? '' : 's'} e os respetivos registos foram preservados.`, restoreFailed: 'Não foi possível ler ou restaurar a cópia.', restorePreviewTitle: 'Pré-visualização da cópia', restorePreviewProjects: 'Projetos neste ficheiro', restorePreviewRecords: 'Registos operacionais', restorePreviewSettings: 'Definições do espaço incluídas', restorePreviewWarning: 'Os novos projetos e os respetivos registos serão fundidos neste espaço. Os projetos e registos existentes serão preservados.', restorePreviewCancel: 'Cancelar restauro', restorePreviewConfirm: 'Fundir cópia' },
};

export function getSettingsCopy(locale: string): SettingsCopy {
  return COPY[locale.toLowerCase().split('-')[0] as LanguageCode] ?? COPY.en;
}

