import type { LanguageCode } from './i18n';

export interface SpecSheetCopy {
  title: string; description: string; quoteReadiness: string; pomPoints: string; norm: string; yarnBill: string; complete: string; noYardage: string; toleranceBand: string; colourways: string; strengthensQuote: string;
  gaugeConstruction: string; noGauge: string; tolerance: string; machineGauge: string; construction: string; choose: string; notChosen: string; flat: string; circular: string; fullyFashioned: string; yarnWeight: string;
  pomSheet: string; point: string; toleranceShort: string; manual: string; noPom: string; addMeasurements: string; manualPoints: string; addPoint: string; label: string; labelPlaceholder: string; toleranceDefault: string; remove: string; manualHelp: string;
  fibre: string; fibrePlaceholder: string; yardageOverride: string; yarnBillHelp: string; addColourway: string; name: string; namePlaceholder: string; yarnSpec: string; yarnSpecPlaceholder: string; colourwayHelp: string;
  notes: string; notesPlaceholder: string; flags: string; benchmarks: (min: number, max: number, low: number, high: number, freelanceLow: number, freelanceHigh: number, aiLow: number, aiHigh: number) => string;
  verdict: Record<string, string>; severity: Record<string, string>;
}

const en: SpecSheetCopy = {
  title:'Spec Sheet Lab', description:'Turn this project’s graded measurements into a factory-oriented working sheet. It can assemble POM values, tolerances, yarn details and gauge notes; it does not replace a factory review or a complete technical pack.', quoteReadiness:'Quote-readiness', pomPoints:'POM points', norm:'norm', yarnBill:'Yarn bill', complete:'Complete', noYardage:'no yardage', toleranceBand:'Tolerance band', colourways:'Colourways', strengthensQuote:'multiple colourways can make a quote more useful', gaugeConstruction:'Gauge & construction block', noGauge:'No gauge block — numbers remain unverifiable until the project gauge is set.', tolerance:'Tolerance (in)', machineGauge:'Machine gauge (flat-bed)', construction:'Construction', choose:'Choose', notChosen:'— not chosen —', flat:'Flat-bed panels', circular:'Circular knit', fullyFashioned:'Fully-fashioned', yarnWeight:'Yarn weight class', pomSheet:'Points of measure (POM) sheet', point:'Point', toleranceShort:'Tol (in)', manual:'manual', noPom:'No POM points — the sheet is empty. Add graded measurements or manual points before treating it as quote-ready.', addMeasurements:'Factories may request more detail than this sheet contains.', manualPoints:'Manual POM points', addPoint:'Add point', label:'Label', labelPlaceholder:'e.g. “Half Chest, 1 in below armhole”', toleranceDefault:'Tolerance (in, 0 = default)', remove:'Remove', manualHelp:'Manual points use graded values only when a matching grading key exists; unmapped points remain notes for items such as collar spread or button stance.', fibre:'Fibre / composition', fibrePlaceholder:'e.g. “100% superwash merino, worsted”', yardageOverride:'Yardage override (0 = derive from the yardage model)', yarnBillHelp:'Yarn bill values are estimates or user-entered inputs, not a supplier-confirmed bill of materials.', addColourway:'Add colourway', name:'Name', namePlaceholder:'Oatmeal', yarnSpec:'Yarn spec', yarnSpecPlaceholder:'e.g. “merino fingering”', colourwayHelp:'Colourways document options for a quote; they do not prove an order or guarantee vendor interest.', notes:'Sheet notes (finish, blocking, trim)', notesPlaceholder:'e.g. steam-block panels flat; 1x1 rib, 2-ply; no finishing required.', flags:'Sheet flags — S-01 to S-06', benchmarks:(min,max,low,high,fl,fh,al,ah)=>`Reference ranges: sweater sheets are often described with ${min}–${max} POM points; ±0.25 in is a commonly cited knitwear tolerance; flat-bed machines are often described in the ${low}–${high} gauge range. The comparison figures shown here are research framing, not a quote or endorsement. Freelance packs: $${fl}–$${fh}; AI packs: $${al}–$${ah} per pack where completeness varies.`, verdict:{ready:'ready',review:'review',blocked:'blocked'}, severity:{error:'Needs attention',warning:'Review',info:'Recorded'}
};
const de: SpecSheetCopy = {...en,title:'Datenblatt-Labor',description:'Erstelle aus den gradierten Maßen dieses Projekts ein arbeitsfähiges, fabrikorientiertes Datenblatt. Es ersetzt weder die Prüfung durch eine Fabrik noch ein vollständiges Tech-Pack.',quoteReadiness:'Angebotsreife',pomPoints:'POM-Punkte',norm:'Richtwert',yarnBill:'Garnaufstellung',complete:'Vollständig',noYardage:'keine Lauflänge',toleranceBand:'Toleranzband',colourways:'Farbvarianten',strengthensQuote:'mehrere Farbvarianten können ein Angebot brauchbarer machen',gaugeConstruction:'Maschenprobe und Konstruktion',noGauge:'Keine Maschenprobe — Zahlen bleiben nicht überprüfbar, bis die Projektprobe gesetzt ist.',tolerance:'Toleranz (Zoll)',machineGauge:'Maschinenfeinheit (Flachbett)',construction:'Konstruktion',choose:'Auswählen',notChosen:'— nicht gewählt —',flat:'Flachbettteile',circular:'Rundstrick',fullyFashioned:'Fully-fashioned',yarnWeight:'Garnstärke',pomSheet:'Maßtabelle (POM)',point:'Punkt',toleranceShort:'Tol. (Zoll)',manual:'manuell',noPom:'Keine POM-Punkte — das Blatt ist leer. Ergänze Maße, bevor du es als angebotsbereit behandelst.',addMeasurements:'Fabriken können mehr Details verlangen, als dieses Blatt enthält.',manualPoints:'Manuelle POM-Punkte',addPoint:'Punkt hinzufügen',label:'Bezeichnung',labelPlaceholder:'z. B. „Halbe Brust, 2,5 cm unter Armloch“',toleranceDefault:'Toleranz (Zoll, 0 = Standard)',remove:'Entfernen',manualHelp:'Manuelle Punkte erhalten nur bei passendem Gradierschlüssel Werte; nicht zugeordnete Punkte bleiben Hinweise.',fibre:'Faser / Zusammensetzung',fibrePlaceholder:'z. B. „100 % Superwash-Merino, worsted“',yardageOverride:'Lauflängenüberschreibung (0 = aus Modell ableiten)',yarnBillHelp:'Garnwerte sind Schätzungen oder Eingaben, keine bestätigte Lieferanten-Stückliste.',addColourway:'Farbvariante hinzufügen',name:'Name',namePlaceholder:'Hafer',yarnSpec:'Garnangabe',yarnSpecPlaceholder:'z. B. „Merino Fingering“',colourwayHelp:'Farbvarianten dokumentieren Optionen; sie belegen weder einen Auftrag noch das Interesse eines Anbieters.',notes:'Blattnotizen (Finish, Spannen, Besatz)',notesPlaceholder:'z. B. Teile flach dämpfen; 1x1-Rippe, 2-fädig; kein Finish nötig.',flags:'Blatthinweise — S-01 bis S-06',benchmarks:(min,max,low,high,fl,fh,al,ah)=>`Referenzbereiche: ${min}–${max} POM-Punkte werden für Pulloverdatenblätter häufig genannt; ±0,25 Zoll ist ein oft genannter Toleranzwert; Flachbettmaschinen liegen häufig bei ${low}–${high} Gauge. Diese Zahlen sind Einordnung, kein Angebot. Freelancer: $${fl}–$${fh}; KI-Pakete: $${al}–$${ah} je Paket bei unterschiedlicher Vollständigkeit.`};
const fr: SpecSheetCopy = {...en,title:'Laboratoire de fiche technique',description:'Transformez les mesures gradées de ce projet en fiche de travail orientée usine. Elle ne remplace ni la revue d’une usine ni un tech pack complet.',quoteReadiness:'Préparation au devis',pomPoints:'points POM',norm:'référence',yarnBill:'Fiche fil',complete:'Complète',noYardage:'pas de métrage',toleranceBand:'Tolérance',colourways:'Coloris',strengthensQuote:'plusieurs coloris peuvent rendre un devis plus exploitable',gaugeConstruction:'Échantillon et construction',noGauge:'Pas d’échantillon — les chiffres restent invérifiables tant que l’échantillon du projet n’est pas défini.',tolerance:'Tolérance (po)',machineGauge:'Jauge machine (lit plat)',construction:'Construction',choose:'Choisir',notChosen:'— non choisi —',flat:'Panneaux au tricot rectiligne',circular:'Tricot circulaire',fullyFashioned:'Fully-fashioned',yarnWeight:'Catégorie de fil',pomSheet:'Tableau des mesures (POM)',point:'Point',toleranceShort:'Tol. (po)',manual:'manuel',noPom:'Aucun point POM — la fiche est vide. Ajoutez des mesures avant de la considérer prête pour un devis.',addMeasurements:'Une usine peut demander plus de détails que cette fiche n’en contient.',manualPoints:'Points POM manuels',addPoint:'Ajouter un point',label:'Libellé',labelPlaceholder:'ex. « Demi-poitrine, 2,5 cm sous l’emmanchure »',toleranceDefault:'Tolérance (po, 0 = défaut)',remove:'Supprimer',manualHelp:'Les points manuels ne reçoivent des valeurs que si une clé de gradation correspond ; sinon ils restent des notes.',fibre:'Fibre / composition',fibrePlaceholder:'ex. « 100 % mérinos superwash, worsted »',yardageOverride:'Métrage forcé (0 = dériver du modèle)',yarnBillHelp:'Les valeurs de fil sont des estimations ou saisies, pas une nomenclature confirmée par un fournisseur.',addColourway:'Ajouter un coloris',name:'Nom',namePlaceholder:'Avoine',yarnSpec:'Référence du fil',yarnSpecPlaceholder:'ex. « mérinos fingering »',colourwayHelp:'Les coloris documentent des options ; ils ne prouvent ni commande ni intérêt d’un fournisseur.',notes:'Notes de fiche (finition, blocage, garniture)',notesPlaceholder:'ex. bloquer les panneaux à plat ; côtes 1x1, 2 brins ; aucune finition.',flags:'Alertes de fiche — S-01 à S-06',benchmarks:(min,max,low,high,fl,fh,al,ah)=>`Repères : ${min}–${max} points POM sont souvent cités pour un pull ; ±0,25 po est une tolérance fréquemment citée ; les machines à plat sont souvent dans la plage ${low}–${high}. Ce cadrage n’est ni un devis ni une recommandation. Freelance : $${fl}–$${fh} ; IA : $${al}–$${ah} par fiche, avec une complétude variable.`};
const es: SpecSheetCopy = {...en,title:'Laboratorio de ficha técnica',description:'Convierte las medidas graduadas de este proyecto en una ficha de trabajo orientada a fábrica. No sustituye la revisión de una fábrica ni un tech pack completo.',quoteReadiness:'Preparación para presupuesto',pomPoints:'puntos POM',norm:'referencia',yarnBill:'Ficha de hilo',complete:'Completa',noYardage:'sin metraje',toleranceBand:'Banda de tolerancia',colourways:'Coloridos',strengthensQuote:'varios coloridos pueden hacer más útil un presupuesto',gaugeConstruction:'Muestra y construcción',noGauge:'No hay muestra — los números no se pueden verificar hasta definir la muestra del proyecto.',tolerance:'Tolerancia (pulg)',machineGauge:'Galga de máquina (cama plana)',construction:'Construcción',choose:'Elegir',notChosen:'— no elegida —',flat:'Paneles de cama plana',circular:'Tejido circular',fullyFashioned:'Fully-fashioned',yarnWeight:'Clase de grosor del hilo',pomSheet:'Tabla de medidas (POM)',point:'Punto',toleranceShort:'Tol. (pulg)',manual:'manual',noPom:'No hay puntos POM — la ficha está vacía. Añade medidas antes de tratarla como lista para presupuesto.',addMeasurements:'Una fábrica puede pedir más detalle del que contiene esta ficha.',manualPoints:'Puntos POM manuales',addPoint:'Añadir punto',label:'Etiqueta',labelPlaceholder:'p. ej., «Media sisa, 2,5 cm bajo la axila»',toleranceDefault:'Tolerancia (pulg, 0 = predeterminada)',remove:'Eliminar',manualHelp:'Los puntos manuales solo reciben valores si existe una clave de graduación coincidente; los demás quedan como notas.',fibre:'Fibra / composición',fibrePlaceholder:'p. ej., «100 % merino superwash, worsted»',yardageOverride:'Metraje manual (0 = derivar del modelo)',yarnBillHelp:'Los valores del hilo son estimaciones o entradas del usuario, no una lista confirmada por proveedor.',addColourway:'Añadir colorido',name:'Nombre',namePlaceholder:'Avena',yarnSpec:'Especificación del hilo',yarnSpecPlaceholder:'p. ej., «merino fingering»',colourwayHelp:'Los coloridos documentan opciones; no prueban un pedido ni el interés de un proveedor.',notes:'Notas de la ficha (acabado, bloqueo, adornos)',notesPlaceholder:'p. ej., vaporizar paneles en plano; canalé 1x1, 2 cabos; sin acabado.',flags:'Avisos de la ficha — S-01 a S-06',benchmarks:(min,max,low,high,fl,fh,al,ah)=>`Referencias: se citan a menudo ${min}–${max} puntos POM para jerséis; ±0,25 pulg es una tolerancia habitual citada; las máquinas de cama plana suelen describirse en ${low}–${high} galgas. Es contexto, no presupuesto ni garantía. Freelance: $${fl}–$${fh}; IA: $${al}–$${ah} por ficha, con completitud variable.`};
const pt: SpecSheetCopy = {...en,title:'Laboratório de ficha técnica',description:'Converta as medidas graduadas deste projeto numa ficha de trabalho orientada para fábrica. Não substitui a revisão de uma fábrica nem um tech pack completo.',quoteReadiness:'Preparação para orçamento',pomPoints:'pontos POM',norm:'referência',yarnBill:'Ficha de fio',complete:'Completa',noYardage:'sem metragem',toleranceBand:'Faixa de tolerância',colourways:'Cores',strengthensQuote:'várias cores podem tornar um orçamento mais útil',gaugeConstruction:'Amostra e construção',noGauge:'Sem amostra — os números não podem ser verificados até definir a amostra do projeto.',tolerance:'Tolerância (pol)',machineGauge:'Finura da máquina (leito plano)',construction:'Construção',choose:'Escolher',notChosen:'— não escolhida —',flat:'Painéis de leito plano',circular:'Tricô circular',fullyFashioned:'Fully-fashioned',yarnWeight:'Classe de espessura do fio',pomSheet:'Tabela de medidas (POM)',point:'Ponto',toleranceShort:'Tol. (pol)',manual:'manual',noPom:'Sem pontos POM — a ficha está vazia. Adicione medidas antes de a tratar como pronta para orçamento.',addMeasurements:'Uma fábrica pode pedir mais detalhes do que esta ficha contém.',manualPoints:'Pontos POM manuais',addPoint:'Adicionar ponto',label:'Etiqueta',labelPlaceholder:'ex.: “Meio peito, 2,5 cm abaixo da cava”',toleranceDefault:'Tolerância (pol, 0 = predefinida)',remove:'Remover',manualHelp:'Os pontos manuais só recebem valores quando existe uma chave de graduação correspondente; os restantes ficam como notas.',fibre:'Fibra / composição',fibrePlaceholder:'ex.: “100% merino superwash, worsted”',yardageOverride:'Metragem manual (0 = derivar do modelo)',yarnBillHelp:'Os valores do fio são estimativas ou entradas do utilizador, não uma lista confirmada pelo fornecedor.',addColourway:'Adicionar cor',name:'Nome',namePlaceholder:'Aveia',yarnSpec:'Especificação do fio',yarnSpecPlaceholder:'ex.: “merino fingering”',colourwayHelp:'As cores documentam opções; não provam uma encomenda nem o interesse de um fornecedor.',notes:'Notas da ficha (acabamento, bloqueio, guarnição)',notesPlaceholder:'ex.: vaporizar painéis planos; canelado 1x1, 2 fios; sem acabamento.',flags:'Alertas da ficha — S-01 a S-06',benchmarks:(min,max,low,high,fl,fh,al,ah)=>`Referências: citam-se frequentemente ${min}–${max} pontos POM para camisolas; ±0,25 pol é uma tolerância comum; máquinas de leito plano são frequentemente descritas na faixa ${low}–${high}. É contexto, não orçamento nem garantia. Freelance: $${fl}–$${fh}; IA: $${al}–$${ah} por ficha, com completude variável.`};

export const COPY: Record<LanguageCode, SpecSheetCopy> = { en, de, fr, es, pt };

function lang(locale: string): LanguageCode { const key = locale.toLowerCase().split('-')[0] as LanguageCode; return SPEC_SHEET_COPY[key] ? key : 'en'; }

export function getSpecSheetCopy(locale: string): SpecSheetCopy { return SPEC_SHEET_COPY[lang(locale)]; }

export function getSpecFlagTitle(locale: string, code: string): string {
  const titles: Record<LanguageCode, Record<string,string>> = {
    en:{'S-01':'POM coverage','S-02':'Tolerance band','S-03':'Colourway depth','S-04':'Yarn bill completeness','S-05':'Gauge block','S-06':'Quote readiness'},
    de:{'S-01':'POM-Abdeckung','S-02':'Toleranzband','S-03':'Tiefe der Farbvarianten','S-04':'Vollständigkeit der Garnaufstellung','S-05':'Maschenprobenblock','S-06':'Angebotsreife'},
    fr:{'S-01':'Couverture POM','S-02':'Bande de tolérance','S-03':'Profondeur des coloris','S-04':'Complétude de la fiche fil','S-05':'Bloc d’échantillon','S-06':'Préparation au devis'},
    es:{'S-01':'Cobertura POM','S-02':'Banda de tolerancia','S-03':'Profundidad de coloridos','S-04':'Completitud de la ficha de hilo','S-05':'Bloque de muestra','S-06':'Preparación para presupuesto'},
    pt:{'S-01':'Cobertura POM','S-02':'Faixa de tolerância','S-03':'Profundidade das cores','S-04':'Completude da ficha de fio','S-05':'Bloco de amostra','S-06':'Preparação para orçamento'},
  };
  return titles[lang(locale)][code] ?? code;
}

export function getSpecFlagMessage(locale: string, code: string, message: string): string {
  const c = getSpecSheetCopy(locale);
  const n = (message.match(/\d+(?:\.\d+)?/g) ?? []).map(Number);
  const [a,b,c2] = n;
  const name = message.match(/\(([^)]+)\)/)?.[1] ?? '';
  const suffix = name && code === 'S-03' ? ` (${name})` : '';
  if (code === 'S-01') return a !== undefined && b !== undefined ? `${a} ${c.pomPoints} — ${a < 8 ? c.addMeasurements : c.norm} (${b}–${n[2] ?? b}).` : message;
  if (code === 'S-02') return a !== undefined ? `±${a} in.` : message;
  if (code === 'S-03') return a !== undefined ? `${a} ${c.colourways}${suffix} — ${c.strengthensQuote}.` : message;
  if (code === 'S-04') return message.includes('complete') || message.includes('complete:') ? `${c.yarnBill}: ${c.complete}.` : c.yarnBillHelp;
  if (code === 'S-05') return a !== undefined ? `${c.machineGauge}: ${a} — ${c.yarnBillHelp}` : c.noGauge;
  if (code === 'S-06') return `${c.quoteReadiness}: ${a ?? '—'}/6.`;
  return message;
}

export function getSpecVerdictReason(locale: string, verdict: string, score: number): string {
  const c = getSpecSheetCopy(locale);
  const labels = c.verdict;
  const key = lang(locale);
  if (key === 'de') {
    if (verdict === 'ready') return `${labels.ready}: ${score}/6 — die erforderlichen Eingaben sind vorhanden; prüfe das Blatt trotzdem mit der Fabrik.`;
    if (verdict === 'review') return `${labels.review}: ${score}/6 — prüfe die fehlenden Eingaben vor einer Angebotsanfrage.`;
    return `${labels.blocked}: ${score}/6 — behebe die markierten Eingaben vor einer Angebotsanfrage.`;
  }
  if (key === 'fr') {
    if (verdict === 'ready') return `${labels.ready} : ${score}/6 — les champs requis sont présents, mais vérifiez la fiche avec l’usine.`;
    if (verdict === 'review') return `${labels.review} : ${score}/6 — vérifiez les champs manquants avant de demander un devis.`;
    return `${labels.blocked} : ${score}/6 — corrigez les champs signalés avant de demander un devis.`;
  }
  if (key === 'es') {
    if (verdict === 'ready') return `${labels.ready}: ${score}/6 — las entradas necesarias están presentes, pero confirma la ficha con la fábrica.`;
    if (verdict === 'review') return `${labels.review}: ${score}/6 — revisa las entradas que faltan antes de pedir presupuesto.`;
    return `${labels.blocked}: ${score}/6 — resuelve las entradas señaladas antes de pedir presupuesto.`;
  }
  if (key === 'pt') {
    if (verdict === 'ready') return `${labels.ready}: ${score}/6 — os dados necessários estão presentes, mas confirme a ficha com a fábrica.`;
    if (verdict === 'review') return `${labels.review}: ${score}/6 — reveja os dados em falta antes de pedir um orçamento.`;
    return `${labels.blocked}: ${score}/6 — resolva os dados assinalados antes de pedir um orçamento.`;
  }
  if (verdict === 'ready') return `${labels.ready}: ${score}/6 — required inputs are present, but confirm the sheet with the factory before relying on it.`;
  if (verdict === 'review') return `${labels.review}: ${score}/6 — review the missing inputs before requesting a quote.`;
  return `${labels.blocked}: ${score}/6 — resolve the flagged inputs before requesting a quote.`;
}

export function getSpecYarnLabel(locale: string, label: string): string {
  const labels: Record<LanguageCode, Record<string,string>> = {
    en:{'Fibre / composition':'Fibre / composition','Yarn weight class':'Yarn weight class','Estimated yardage (base size)':'Estimated yardage (base size)'},
    de:{'Fibre / composition':'Faser / Zusammensetzung','Yarn weight class':'Garnstärke','Estimated yardage (base size)':'Geschätzte Lauflänge (Grundgröße)'},
    fr:{'Fibre / composition':'Fibre / composition','Yarn weight class':'Catégorie de fil','Estimated yardage (base size)':'Métrage estimé (taille de base)'},
    es:{'Fibre / composition':'Fibra / composición','Yarn weight class':'Clase de grosor','Estimated yardage (base size)':'Metraje estimado (talla base)'},
    pt:{'Fibre / composition':'Fibra / composição','Yarn weight class':'Classe de espessura','Estimated yardage (base size)':'Metragem estimada (tamanho base)'},
  };
  return labels[lang(locale)][label] ?? label;
}

export function getSpecGaugeLine(locale: string, line: string): string {
  const c = getSpecSheetCopy(locale);
  if (line.startsWith('Gauge:')) return line.replace('Gauge:', locale.startsWith('de') ? 'Maschenprobe:' : locale.startsWith('fr') ? 'Échantillon :' : locale.startsWith('es') ? 'Muestra:' : locale.startsWith('pt') ? 'Amostra:' : 'Gauge:');
  if (line.startsWith('Machine gauge:')) return line.replace('Machine gauge:', `${c.machineGauge}:`);
  if (line.startsWith('Construction:')) return line.replace('Construction:', `${c.construction}:`);
  return line;
}

export const SPEC_SHEET_COPY = COPY;
