import type { LanguageCode } from './i18n';
export interface StorageCopy { localOnly:string; aria:string; title:string; warning:string; backup:string; }
const en={localOnly:'Local only',aria:'Local storage status and backup',title:'Your patterns live only on this device',warning:"Nothing is uploaded anywhere. Switching to a laptop or another device? Use the Export tool in Settings to move your workspace first. Clearing browser data or reinstalling will delete everything — unless you've exported first.",backup:'Back up all patterns now'};
const de={localOnly:'Nur lokal',aria:'Status und Sicherung des lokalen Speichers',title:'Deine Muster liegen nur auf diesem Gerät',warning:'Nichts wird hochgeladen. Wechselst du auf einen Laptop oder ein anderes Gerät? Nutze zuerst das Export-Tool in den Einstellungen, um deine Arbeitsumgebung zu übertragen. Browserdaten löschen oder neu installieren entfernt alles — außer du hast vorher exportiert.',backup:'Alle Muster jetzt sichern'};
const fr={localOnly:'Local uniquement',aria:'État du stockage local et sauvegarde',title:'Vos patrons restent uniquement sur cet appareil',warning:'Rien n’est envoyé nulle part. Vous passez sur un ordinateur ou un autre appareil ? Utilisez l’outil d’exportation dans les Préférences pour transférer votre espace de travail. Effacer les données supprimera tout — sauf si vous avez exporté d’abord.',backup:'Sauvegarder tous les patrons maintenant'};
const es={localOnly:'Solo local',aria:'Estado del almacenamiento local y copia de seguridad',title:'Tus patrones solo están en este dispositivo',warning:'No se sube nada a ningún sitio. ¿Vas a cambiar a un portátil u otro dispositivo? Usa la herramienta de Exportar en Preferencias para mover tu espacio de trabajo primero. Borrar datos borrará todo — salvo que hayas exportado antes.',backup:'Hacer copia de todos los patrones ahora'};
const pt={localOnly:'Apenas local',aria:'Estado do armazenamento local e cópia de segurança',title:'Os seus padrões vivem apenas neste dispositivo',warning:'Nada é carregado para lado nenhum. Vai mudar para um portátil ou outro dispositivo? Use a ferramenta de Exportar nas Preferências para mover o seu espaço de trabalho primeiro. Limpar dados apagará tudo — a menos que tenha exportado antes.',backup:'Fazer cópia de segurança de todos os padrões agora'};
export const COPY:Record<LanguageCode,StorageCopy>={en,de,fr,es,pt};

export const STORAGE_COPY = COPY;
