import type { LanguageCode } from '@/lib/i18n';

const LABELS: Partial<Record<LanguageCode, Record<string, string>>> = {
  de: {
    sections: 'Abschnitte', preview: 'Vorschau', yarn: 'Garn', notes: 'Notizen', snapshots: 'Schnappschüsse', readiness: 'Bereitschaft', income: 'Einnahmen',
 draft: 'Entwurf', pricing: 'Preisgestaltung', publish: 'Veröffentlichen', testknit: 'Teststrick', techedit: 'Technische Redaktion', finish: 'Fertigstellen', deals: 'Angebote', launch: 'Launch', trunkshow: 'Trunk Show', transbundle: 'Übersetzen & bündeln', patternclub: 'Musterclub', kits: 'Kits', pipeline: 'Pipeline', kalroi: 'KAL & Kooperation', channels: 'Kanäle', clubrev: 'Club-Umsatz', wsbook: 'Großhandel & Buch', hireself: 'Anstellen oder selbst machen', inclusive: 'Inklusiv', licenceit: 'Lizenzieren', members: 'Mitglieder', promo: 'Werbung', pricewin: 'Preisvorteil', repeat: 'Wiederholung', mix: 'Mix', collab: 'Kooperation', bookit: 'Buchen', protect: 'Schützen', teach: 'Lehren', partners: 'Partner', yarnbuy: 'Garn einkaufen', kal: 'KAL-Planer', gradinglab: 'Gradierungs-Labor', chartlab: 'Diagramm-Labor', testdesk: 'Teststrick-Schreibtisch', submissions: 'Einreichungen', lookbook: 'Lookbook', specsheet: 'Spezifikationsblatt', subdist: 'Verteilung', listingseo: 'Listing-SEO', adlab: 'Werbe-Break-even', samplelaunch: 'Muster & Launch', dealmath: 'Kooperationsrechnung', photolab: 'Foto-ROI', videosocial: 'Video & Social', showroi: 'Messe-ROI', wholesale: 'Großhandels-Labor', preorder: 'Vorbestell-Labor', 'listing-test': 'Listing-Test-Labor', 'yarn-pool': 'Garnpool-Labor', 'membership-site': 'Mitgliedschafts-Labor', 'release-timing': 'Launch-Timing-Labor', 'convention-booth': 'Messestand-Labor', 'channel-migration': 'Kanal-Labor', 'workshop-teach': 'Workshop-Labor', 'consignment-reprice': 'Kommissionspreis-Labor', 'pattern-bundle': 'Bündel-Labor', 'retreat-teach': 'Retreat-Labor', 'podcast-affiliate': 'Podcast-Labor', 'magazine-submission': 'Magazin-Labor', 'pricing-psychology': 'Preispsychologie-Labor', 'pod-patterns': 'POD-Muster-Labor', 'marketplace-takerate': 'Marktplatzgebühren-Labor', 'box-inclusion': 'Box-Inklusions-Labor', 'yarn-licensing': 'Garnlizenz-Labor', giftcard: 'Geschenk- & Guthaben-Labor', 'wholesale-pricelist': 'Großhandelslisten-Labor', 'intl-pricing': 'Internationales Preis-Labor', testknitlab: 'Teststrick-Labor', gaugefit: 'Maschenprobe & Passform', receiptlab: 'Quittungs-Labor', designledger: 'Designregister', bragcard: 'Brag Cards', payback: 'Payback-Labor',
  },
  fr: {
    sections: 'Sections', preview: 'Aperçu', yarn: 'Fil', notes: 'Notes', snapshots: 'Instantanés', readiness: 'Disponibilité', income: 'Revenus',
 draft: 'Brouillon', pricing: 'Tarification', publish: 'Publier', testknit: 'Test tricot', techedit: 'Édition technique', finish: 'Finaliser', deals: 'Offres', launch: 'Lancement', trunkshow: 'Trunk show', transbundle: 'Traduction et bundle', patternclub: 'Club de patrons', kits: 'Kits', pipeline: 'Pipeline', kalroi: 'KAL et collaboration', channels: 'Canaux', clubrev: 'Revenus du club', wsbook: 'Grossiste et livre', hireself: 'Embaucher ou faire soi-même', inclusive: 'Inclusif', licenceit: 'Licencier', members: 'Membres', promo: 'Promotion', pricewin: 'Avantage prix', repeat: 'Répétition', mix: 'Mix', collab: 'Collaboration', bookit: 'Réserver', protect: 'Protéger', teach: 'Enseigner', partners: 'Partenaires', yarnbuy: 'Acheter le fil', kal: 'Planificateur KAL', gradinglab: 'Labo de gradation', chartlab: 'Labo de diagrammes', testdesk: 'Bureau de test tricot', submissions: 'Soumissions', lookbook: 'Lookbook', specsheet: 'Fiche technique', subdist: 'Distribution', listingseo: 'SEO de fiche', adlab: 'Seuil de rentabilité pub', samplelaunch: 'Échantillon et lancement', dealmath: 'Calcul de collaboration', photolab: 'ROI photo', videosocial: 'Vidéo et social', showroi: 'ROI salon', wholesale: 'Labo grossiste', preorder: 'Labo précommande', 'listing-test': 'Labo test de fiche', 'yarn-pool': 'Labo réserve de fil', 'membership-site': 'Labo adhésion', 'release-timing': 'Labo calendrier de sortie', 'convention-booth': 'Labo stand', 'channel-migration': 'Labo migration de canal', 'workshop-teach': 'Labo atelier', 'consignment-reprice': 'Labo nouveau prix', 'pattern-bundle': 'Labo bundle', 'retreat-teach': 'Labo retraite', 'podcast-affiliate': 'Labo podcast', 'magazine-submission': 'Labo magazine', 'pricing-psychology': 'Labo psychologie des prix', 'pod-patterns': 'Labo patrons POD', 'marketplace-takerate': 'Labo taux marketplace', 'box-inclusion': 'Labo inclusion box', 'yarn-licensing': 'Labo licence fil', giftcard: 'Labo cartes cadeau', 'wholesale-pricelist': 'Labo liste grossiste', 'intl-pricing': 'Labo prix internationaux', testknitlab: 'Labo test tricot', gaugefit: 'Échantillon et aisance', receiptlab: 'Labo des reçus', designledger: 'Registre de design', bragcard: 'Brag Cards', payback: 'Labo retour sur investissement',
  },
  es: {
    sections: 'Secciones', preview: 'Vista previa', yarn: 'Hilo', notes: 'Notas', snapshots: 'Instantáneas', readiness: 'Disponibilidad', income: 'Ingresos',
 draft: 'Borrador', pricing: 'Precios', publish: 'Publicar', testknit: 'Prueba de tejido', techedit: 'Edición técnica', finish: 'Finalizar', deals: 'Ofertas', launch: 'Lanzamiento', trunkshow: 'Trunk show', transbundle: 'Traducir y agrupar', patternclub: 'Club de patrones', kits: 'Kits', pipeline: 'Pipeline', kalroi: 'KAL y colaboración', channels: 'Canales', clubrev: 'Ingresos del club', wsbook: 'Mayorista y libro', hireself: 'Contratar o hacerlo uno mismo', inclusive: 'Inclusivo', licenceit: 'Licenciar', members: 'Miembros', promo: 'Promoción', pricewin: 'Ventaja de precio', repeat: 'Repetición', mix: 'Mezcla', collab: 'Colaboración', bookit: 'Reservar', protect: 'Proteger', teach: 'Enseñar', partners: 'Socios', yarnbuy: 'Comprar hilo', kal: 'Planificador KAL', gradinglab: 'Laboratorio de gradación', chartlab: 'Laboratorio de gráficos', testdesk: 'Mesa de pruebas', submissions: 'Envíos', lookbook: 'Lookbook', specsheet: 'Ficha técnica', subdist: 'Distribución', listingseo: 'SEO del anuncio', adlab: 'Punto de equilibrio del anuncio', samplelaunch: 'Muestra y lanzamiento', dealmath: 'Cálculo de colaboración', photolab: 'ROI de fotografía', videosocial: 'Vídeo y redes', showroi: 'ROI de feria', wholesale: 'Laboratorio mayorista', preorder: 'Laboratorio de preventa', 'listing-test': 'Laboratorio de prueba del anuncio', 'yarn-pool': 'Laboratorio de reserva de hilo', 'membership-site': 'Laboratorio de membresías', 'release-timing': 'Laboratorio de calendario de lanzamiento', 'convention-booth': 'Laboratorio de stand', 'channel-migration': 'Laboratorio de canales', 'workshop-teach': 'Laboratorio de talleres', 'consignment-reprice': 'Laboratorio de repricing', 'pattern-bundle': 'Laboratorio de paquetes', 'retreat-teach': 'Laboratorio de retiros', 'podcast-affiliate': 'Laboratorio de pódcast', 'magazine-submission': 'Laboratorio de revistas', 'pricing-psychology': 'Laboratorio de psicología de precios', 'pod-patterns': 'Laboratorio de patrones POD', 'marketplace-takerate': 'Laboratorio de comisiones', 'box-inclusion': 'Laboratorio de inclusión en cajas', 'yarn-licensing': 'Laboratorio de licencias de hilo', giftcard: 'Laboratorio de regalos y crédito', 'wholesale-pricelist': 'Laboratorio de listas mayoristas', 'intl-pricing': 'Laboratorio de precios internacionales', testknitlab: 'Laboratorio de prueba de tejido', gaugefit: 'Muestra y ajuste', receiptlab: 'Laboratorio de recibos', designledger: 'Registro de diseños', bragcard: 'Brag Cards', payback: 'Laboratorio de recuperación',
  },
  pt: {
    sections: 'Secções', preview: 'Pré-visualização', yarn: 'Fio', notes: 'Notas', snapshots: 'Instantâneos', readiness: 'Prontidão', income: 'Receitas',
 draft: 'Rascunho', pricing: 'Preços', publish: 'Publicar', testknit: 'Teste de tricô', techedit: 'Edição técnica', finish: 'Finalizar', deals: 'Ofertas', launch: 'Lançamento', trunkshow: 'Trunk show', transbundle: 'Traduzir e agrupar', patternclub: 'Clube de padrões', kits: 'Kits', pipeline: 'Pipeline', kalroi: 'KAL e colaboração', channels: 'Canais', clubrev: 'Receita do clube', wsbook: 'Grossista e livro', hireself: 'Contratar ou fazer sozinho', inclusive: 'Inclusivo', licenceit: 'Licenciar', members: 'Membros', promo: 'Promoção', pricewin: 'Vantagem de preço', repeat: 'Repetição', mix: 'Mistura', collab: 'Colaboração', bookit: 'Reservar', protect: 'Proteger', teach: 'Ensinar', partners: 'Parceiros', yarnbuy: 'Comprar fio', kal: 'Planeador KAL', gradinglab: 'Laboratório de graduação', chartlab: 'Laboratório de gráficos', testdesk: 'Mesa de teste', submissions: 'Submissões', lookbook: 'Lookbook', specsheet: 'Ficha técnica', subdist: 'Distribuição', listingseo: 'SEO do anúncio', adlab: 'Ponto de equilíbrio do anúncio', samplelaunch: 'Amostra e lançamento', dealmath: 'Cálculo de colaboração', photolab: 'ROI de fotografia', videosocial: 'Vídeo e redes sociais', showroi: 'ROI de feira', wholesale: 'Laboratório grossista', preorder: 'Laboratório de pré-encomenda', 'listing-test': 'Laboratório de teste do anúncio', 'yarn-pool': 'Laboratório de reserva de fio', 'membership-site': 'Laboratório de membros', 'release-timing': 'Laboratório de calendário de lançamento', 'convention-booth': 'Laboratório de banca', 'channel-migration': 'Laboratório de canais', 'workshop-teach': 'Laboratório de workshops', 'consignment-reprice': 'Laboratório de novo preço', 'pattern-bundle': 'Laboratório de bundles', 'retreat-teach': 'Laboratório de retiros', 'podcast-affiliate': 'Laboratório de podcast', 'magazine-submission': 'Laboratório de revistas', 'pricing-psychology': 'Laboratório de psicologia de preços', 'pod-patterns': 'Laboratório de padrões POD', 'marketplace-takerate': 'Laboratório de comissões', 'box-inclusion': 'Laboratório de inclusão em caixas', 'yarn-licensing': 'Laboratório de licenciamento de fio', giftcard: 'Laboratório de presentes e crédito', 'wholesale-pricelist': 'Laboratório de listas grossistas', 'intl-pricing': 'Laboratório de preços internacionais', testknitlab: 'Laboratório de teste de tricô', gaugefit: 'Amostra e ajuste', receiptlab: 'Laboratório de recibos', designledger: 'Registo de designs', bragcard: 'Brag Cards', payback: 'Laboratório de recuperação',
  },
};

export function getWorkspaceTabLabel(locale: string, value: string, fallback: string): string {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  return LABELS[language]?.[value] ?? fallback;
}

export function getWorkspaceTabCoverage(locale: string): number {
  const language = locale.toLowerCase().split('-')[0] as LanguageCode;
  return Object.keys(LABELS[language] ?? {}).length;
}
